const STRIVER_A2Z_DATA = [
  {
    topic: "Learn the basics - Things to Know in C++/Java/Python or any language",
    icon: "📘",
    questions: [
      { name: "User Input / Output", url: "https://takeuforward.org/c/c-basic-input-output/" },
      { name: "Data Types", url: "" },
      { name: "If Else statements", url: "https://takeuforward.org/if-else/if-else-statements/" },
      { name: "Switch Statement", url: "https://takeuforward.org/switch-case/switch-case-statements/" },
      { name: "What are arrays, strings?", url: "" },
      { name: "For loops", url: "https://takeuforward.org/for-loop/understanding-for-loop/" },
      { name: "While loops", url: "https://takeuforward.org/while-loop/while-loops-in-programming/" },
      { name: "Functions (Pass by Reference and Value)", url: "" },
      { name: "Time Complexity [Learn Basics, and then analyse in next Steps]", url: "https://takeuforward.org/time-complexity/time-and-space-complexity-strivers-a2z-dsa-course/" },
    ],
  },
  {
    topic: "Learn the basics - Build-up Logical Thinking",
    icon: "📘",
    questions: [
      { name: "Patterns", url: "https://takeuforward.org/strivers-a2z-dsa-course/must-do-pattern-problems-before-starting-dsa/" },
    ],
  },
  {
    topic: "Learn the basics - Learn STL/Java-Collections or similar thing in your language",
    icon: "📘",
    questions: [
      { name: "C++ STL", url: "https://takeuforward.org/c/c-stl-tutorial-most-frequent-used-stl-containers/" },
      { name: "Java Collections", url: "" },
    ],
  },
  {
    topic: "Learn the basics - Know Basic Maths",
    icon: "📘",
    questions: [
      { name: "Count Digits", url: "https://takeuforward.org/data-structure/count-digits-in-a-number/" },
      { name: "Reverse a Number", url: "https://takeuforward.org/maths/reverse-digits-of-a-number", lcUrl: "https://leetcode.com/problems/reverse-integer/" },
      { name: "Check Palindrome", url: "https://takeuforward.org/data-structure/check-if-a-number-is-palindrome-or-not/", lcUrl: "https://leetcode.com/problems/palindrome-number/" },
      { name: "GCD Or HCF", url: "https://takeuforward.org/data-structure/find-gcd-of-two-numbers/", lcUrl: "https://leetcode.com/problems/find-greatest-common-divisor-of-array/", gfgUrl: "https://www.geeksforgeeks.org/problems/gcd-of-two-numbers3459/1" },
      { name: "Armstrong Numbers", url: "https://takeuforward.org/maths/check-if-a-number-is-armstrong-number-or-not/", gfgUrl: "https://www.geeksforgeeks.org/problems/armstrong-numbers2727/1" },
      { name: "Print all Divisors", url: "https://takeuforward.org/data-structure/print-all-divisors-of-a-given-number/" },
      { name: "Check for Prime", url: "https://takeuforward.org/data-structure/check-if-a-number-is-prime-or-not/", gfgUrl: "https://www.geeksforgeeks.org/problems/prime-number2314/1" },
    ],
  },
  {
    topic: "Learn the basics - Learn Basic Recursion",
    icon: "📘",
    questions: [
      { name: "Understand recursion by print something N times", url: "https://takeuforward.org/recursion/introduction-to-recursion-understand-recursion-by-printing-something-n-times/" },
      { name: "Print name N times using recursion", url: "https://takeuforward.org/recursion/print-name-n-times-using-recursion/" },
      { name: "Print 1 to N using recursion", url: "https://takeuforward.org/recursion/print-1-to-n-using-recursion/" },
      { name: "Print N to 1 using recursion", url: "https://takeuforward.org/recursion/print-n-to-1-using-recursion/" },
      { name: "Sum of first N numbers", url: "https://takeuforward.org/data-structure/sum-of-first-n-natural-numbers/" },
      { name: "Factorial of N numbers", url: "https://takeuforward.org/data-structure/factorial-of-a-number-iterative-and-recursive/" },
      { name: "Reverse an array", url: "https://takeuforward.org/data-structure/reverse-a-given-array/" },
      { name: "Check if a string is palindrome or not", url: "https://takeuforward.org/data-structure/check-if-the-given-string-is-palindrome-or-not/" },
      { name: "Fibonacci Number", url: "https://takeuforward.org/arrays/print-fibonacci-series-up-to-nth-term/", lcUrl: "https://leetcode.com/problems/fibonacci-number/" },
    ],
  },
  {
    topic: "Learn the basics - Learn Basic Hashing",
    icon: "📘",
    questions: [
      { name: "Hashing Theory", url: "https://takeuforward.org/hashing/hashing-maps-time-complexity-collisions-division-rule-of-hashing-strivers-a2z-dsa-course/" },
      { name: "Counting frequencies of array elements", url: "https://takeuforward.org/data-structure/count-frequency-of-each-element-in-the-array/" },
      { name: "Find the highest/lowest frequency element", url: "https://takeuforward.org/arrays/find-the-highest-lowest-frequency-element/" },
    ],
  },
  {
    topic: "Learn Important Sorting Techniques - Sorting-I",
    icon: "🔢",
    questions: [
      { name: "Selection Sort", url: "https://takeuforward.org/sorting/selection-sort-algorithm/" },
      { name: "Bubble Sort", url: "https://takeuforward.org/data-structure/bubble-sort-algorithm/" },
      { name: "Insertion Sort", url: "https://takeuforward.org/data-structure/insertion-sort-algorithm/" },
    ],
  },
  {
    topic: "Learn Important Sorting Techniques - Sorting-II",
    icon: "🔢",
    questions: [
      { name: "Merge Sort", url: "https://takeuforward.org/data-structure/merge-sort-algorithm/" },
      { name: "Recursive Bubble Sort", url: "https://takeuforward.org/arrays/recursive-bubble-sort-algorithm/" },
      { name: "Recursive Insertion Sort", url: "https://takeuforward.org/arrays/recursive-insertion-sort-algorithm/" },
      { name: "Quick Sort", url: "https://takeuforward.org/data-structure/quick-sort-algorithm/" },
    ],
  },
  {
    topic: "Solve Problems on Arrays [Easy -> Medium -> Hard] - Easy",
    icon: "📊",
    questions: [
      { name: "Largest Element in an Array", url: "https://takeuforward.org/data-structure/find-the-largest-element-in-an-array/", lcUrl: "https://leetcode.com/problems/largest-number-at-least-twice-of-others/", gfgUrl: "https://www.geeksforgeeks.org/problems/largest-element-in-array4009/1" },
      { name: "Second Largest Element in an Array without sorting", url: "https://takeuforward.org/data-structure/find-second-smallest-and-second-largest-element-in-an-array/", gfgUrl: "https://www.geeksforgeeks.org/problems/second-largest3735/1" },
      { name: "Check if the array is sorted", url: "https://takeuforward.org/data-structure/check-if-an-array-is-sorted/", lcUrl: "https://leetcode.com/problems/check-if-array-is-sorted-and-rotated/" },
      { name: "Remove duplicates from Sorted array", url: "https://takeuforward.org/data-structure/remove-duplicates-in-place-from-sorted-array/", lcUrl: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/", gfgUrl: "https://www.geeksforgeeks.org/problems/remove-duplicate-elements-from-sorted-array/1" },
      { name: "Left Rotate an array by one place", url: "https://takeuforward.org/data-structure/left-rotate-the-array-by-one/" },
      { name: "Left rotate an array by D places", url: "https://takeuforward.org/data-structure/rotate-array-by-k-elements/", lcUrl: "https://leetcode.com/problems/rotate-array/" },
      { name: "Move Zeros to end", url: "https://takeuforward.org/data-structure/move-all-zeros-to-the-end-of-the-array/", lcUrl: "https://leetcode.com/problems/move-zeroes/" },
      { name: "Linear Search", url: "https://takeuforward.org/data-structure/linear-search-in-c/" },
      { name: "Find the Union", url: "https://takeuforward.org/data-structure/union-of-two-sorted-arrays/", gfgUrl: "https://www.geeksforgeeks.org/problems/union-of-two-sorted-arrays-1587115621/1" },
      { name: "Find missing number in an array", url: "https://takeuforward.org/arrays/find-the-missing-number-in-an-array/", lcUrl: "https://leetcode.com/problems/missing-number/", gfgUrl: "https://www.geeksforgeeks.org/problems/missing-number-in-array1416/1" },
      { name: "Maximum Consecutive Ones", url: "https://takeuforward.org/data-structure/count-maximum-consecutive-ones-in-the-array/", lcUrl: "https://leetcode.com/problems/max-consecutive-ones/" },
      { name: "Find the number that appears once, and other numbers twice.", url: "https://takeuforward.org/arrays/find-the-number-that-appears-once-and-the-other-numbers-twice/", lcUrl: "https://leetcode.com/problems/single-number/" },
      { name: "Longest subarray with given sum K(positives)", url: "https://takeuforward.org/data-structure/longest-subarray-with-given-sum-k/", gfgUrl: "https://www.geeksforgeeks.org/problems/longest-sub-array-with-sum-k0809/1" },
      { name: "Longest subarray with sum K (Positives + Negatives)", url: "https://takeuforward.org/arrays/longest-subarray-with-sum-k-postives-and-negatives/" },
    ],
  },
  {
    topic: "Solve Problems on Arrays [Easy -> Medium -> Hard] - Medium",
    icon: "📊",
    questions: [
      { name: "2Sum Problem", url: "https://takeuforward.org/data-structure/two-sum-check-if-a-pair-with-given-sum-exists-in-array/", lcUrl: "https://leetcode.com/problems/two-sum/", gfgUrl: "https://www.geeksforgeeks.org/problems/key-pair5616/1" },
      { name: "Sort an array of 0's 1's and 2's", url: "https://takeuforward.org/data-structure/sort-an-array-of-0s-1s-and-2s/", lcUrl: "https://leetcode.com/problems/sort-colors/", gfgUrl: "https://www.geeksforgeeks.org/problems/sort-an-array-of-0s-1s-and-2s4231/1" },
      { name: "Majority Element (>n/2 times)", url: "https://takeuforward.org/data-structure/find-the-majority-element-that-occurs-more-than-n-2-times/", lcUrl: "https://leetcode.com/problems/majority-element/", gfgUrl: "https://www.geeksforgeeks.org/problems/majority-element-1587115620/1" },
      { name: "Kadane's Algorithm, maximum subarray sum", url: "https://takeuforward.org/data-structure/kadanes-algorithm-maximum-subarray-sum-in-an-array/", lcUrl: "https://leetcode.com/problems/maximum-subarray/", gfgUrl: "https://www.geeksforgeeks.org/problems/kadanes-algorithm-1587115620/1" },
      { name: "Print subarray with maximum subarray sum (extended version of above problem)", url: "https://takeuforward.org/data-structure/kadanes-algorithm-maximum-subarray-sum-in-an-array/", lcUrl: "https://leetcode.com/problems/maximum-subarray/" },
      { name: "Stock Buy and Sell", url: "https://takeuforward.org/data-structure/stock-buy-and-sell/", lcUrl: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", gfgUrl: "https://www.geeksforgeeks.org/problems/buy-stock-2/1" },
      { name: "Rearrange the array in alternating positive and negative items", url: "https://takeuforward.org/arrays/rearrange-array-elements-by-sign/", lcUrl: "https://leetcode.com/problems/rearrange-array-elements-by-sign/" },
      { name: "Next Permutation", url: "https://takeuforward.org/data-structure/next_permutation-find-next-lexicographically-greater-permutation/", lcUrl: "https://leetcode.com/problems/next-permutation/", gfgUrl: "https://www.geeksforgeeks.org/problems/next-permutation5226/1" },
      { name: "Leaders in an Array problem", url: "https://takeuforward.org/data-structure/leaders-in-an-array/", gfgUrl: "https://www.geeksforgeeks.org/problems/leaders-in-an-array-1587115620/1" },
      { name: "Longest Consecutive Sequence in an Array", url: "https://takeuforward.org/data-structure/longest-consecutive-sequence-in-an-array/", lcUrl: "https://leetcode.com/problems/longest-consecutive-sequence/", gfgUrl: "https://www.geeksforgeeks.org/problems/longest-consecutive-subsequence2449/1" },
      { name: "Set Matrix Zeros", url: "https://takeuforward.org/data-structure/set-matrix-zero/", lcUrl: "https://leetcode.com/problems/set-matrix-zeroes/", gfgUrl: "https://www.geeksforgeeks.org/problems/set-matrix-zeroes/1" },
      { name: "Rotate Matrix by 90 degrees", url: "https://takeuforward.org/data-structure/rotate-image-by-90-degree/", lcUrl: "https://leetcode.com/problems/rotate-image/" },
      { name: "Print the matrix in spiral manner", url: "https://takeuforward.org/data-structure/spiral-traversal-of-matrix/", lcUrl: "https://leetcode.com/problems/spiral-matrix/" },
      { name: "Count subarrays with given sum", url: "https://takeuforward.org/arrays/count-subarray-sum-equals-k/", lcUrl: "https://leetcode.com/problems/subarray-sum-equals-k/" },
    ],
  },
  {
    topic: "Solve Problems on Arrays [Easy -> Medium -> Hard] - Hard",
    icon: "📊",
    questions: [
      { name: "Pascal's Triangle", url: "https://takeuforward.org/data-structure/program-to-generate-pascals-triangle/", lcUrl: "https://leetcode.com/problems/pascals-triangle/", gfgUrl: "https://www.geeksforgeeks.org/problems/pascal-triangle0652/1" },
      { name: "Majority Element (n/3 times)", url: "https://takeuforward.org/data-structure/majority-elementsn-3-times-find-the-elements-that-appears-more-than-n-3-times-in-the-array/", lcUrl: "https://leetcode.com/problems/majority-element-ii/", gfgUrl: "https://www.geeksforgeeks.org/problems/majority-vote/1" },
      { name: "3-Sum Problem", url: "https://takeuforward.org/data-structure/3-sum-find-triplets-that-add-up-to-a-zero/", lcUrl: "https://leetcode.com/problems/3sum/", gfgUrl: "https://www.geeksforgeeks.org/problems/triplet-sum-in-array-1587115621/1" },
      { name: "4-Sum Problem", url: "https://takeuforward.org/data-structure/4-sum-find-quads-that-add-up-to-a-target-value/", lcUrl: "https://leetcode.com/problems/4sum/", gfgUrl: "https://www.geeksforgeeks.org/problems/find-all-four-sum-numbers1702/1" },
      { name: "Largest Subarray with 0 Sum", url: "https://takeuforward.org/data-structure/length-of-the-longest-subarray-with-zero-sum/", gfgUrl: "https://www.geeksforgeeks.org/problems/largest-subarray-with-0-sum/1" },
      { name: "Count number of subarrays with given xor K", url: "https://takeuforward.org/data-structure/count-the-number-of-subarrays-with-given-xor-k/" },
      { name: "Merge Overlapping Subintervals", url: "https://takeuforward.org/data-structure/merge-overlapping-sub-intervals/", lcUrl: "https://leetcode.com/problems/merge-intervals/", gfgUrl: "https://www.geeksforgeeks.org/problems/overlapping-intervals--170633/1" },
      { name: "Merge two sorted arrays without extra space", url: "https://takeuforward.org/data-structure/merge-two-sorted-arrays-without-extra-space/", lcUrl: "https://leetcode.com/problems/merge-sorted-array/", gfgUrl: "https://www.geeksforgeeks.org/problems/merge-two-sorted-arrays-1587115620/1" },
      { name: "Find the repeating and missing number", url: "https://takeuforward.org/data-structure/find-the-repeating-and-missing-numbers/", gfgUrl: "https://www.geeksforgeeks.org/problems/find-missing-and-repeating2512/1" },
      { name: "Count Inversions", url: "https://takeuforward.org/data-structure/count-inversions-in-an-array/", gfgUrl: "https://www.geeksforgeeks.org/problems/inversion-of-array-1587115620/1" },
      { name: "Reverse Pairs", url: "https://takeuforward.org/data-structure/count-reverse-pairs/", lcUrl: "https://leetcode.com/problems/reverse-pairs/" },
      { name: "Maximum Product Subarray", url: "https://takeuforward.org/data-structure/maximum-product-subarray-in-an-array/", lcUrl: "https://leetcode.com/problems/maximum-product-subarray/", gfgUrl: "https://www.geeksforgeeks.org/problems/maximum-product-subarray3604/1" },
    ],
  },
  {
    topic: "Binary Search [1D, 2D Arrays, Search Space] - BS on 1D Arrays",
    icon: "🔍",
    questions: [
      { name: "Binary Search to find X in sorted array", url: "https://takeuforward.org/data-structure/binary-search-explained/", lcUrl: "https://leetcode.com/problems/binary-search/" },
      { name: "Implement Lower Bound", url: "https://takeuforward.org/arrays/implement-lower-bound-bs-2/", lcUrl: "https://leetcode.com/problems/search-insert-position/" },
      { name: "Implement Upper Bound", url: "https://takeuforward.org/arrays/implement-upper-bound/" },
      { name: "Search Insert Position", url: "https://takeuforward.org/arrays/search-insert-position/", lcUrl: "https://leetcode.com/problems/search-insert-position/" },
      { name: "Floor/Ceil in Sorted Array", url: "https://takeuforward.org/arrays/floor-and-ceil-in-sorted-array/" },
      { name: "Find the first or last occurrence of a given number in a sorted array", url: "https://takeuforward.org/data-structure/last-occurrence-in-a-sorted-array/", lcUrl: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/" },
      { name: "Count occurrences of a number in a sorted array with duplicates", url: "https://takeuforward.org/data-structure/count-occurrences-in-sorted-array/", gfgUrl: "https://www.geeksforgeeks.org/problems/number-of-occurrence2259/1" },
      { name: "Search in Rotated Sorted Array I", url: "https://takeuforward.org/data-structure/search-element-in-a-rotated-sorted-array/", lcUrl: "https://leetcode.com/problems/search-in-rotated-sorted-array/" },
      { name: "Search in Rotated Sorted Array II", url: "https://takeuforward.org/arrays/search-element-in-rotated-sorted-array-ii/", lcUrl: "https://leetcode.com/problems/search-in-rotated-sorted-array-ii/" },
      { name: "Find minimum in Rotated Sorted Array", url: "https://takeuforward.org/data-structure/minimum-in-rotated-sorted-array/", lcUrl: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/" },
      { name: "Find out how many times has an array been rotated", url: "https://takeuforward.org/arrays/find-out-how-many-times-the-array-has-been-rotated/" },
      { name: "Single element in a Sorted Array", url: "https://takeuforward.org/data-structure/search-single-element-in-a-sorted-array/", lcUrl: "https://leetcode.com/problems/single-element-in-a-sorted-array/" },
      { name: "Find peak element", url: "https://takeuforward.org/data-structure/peak-element-in-array/", lcUrl: "https://leetcode.com/problems/find-peak-element/" },
    ],
  },
  {
    topic: "Binary Search [1D, 2D Arrays, Search Space] - BS on Answers",
    icon: "🔍",
    questions: [
      { name: "Find square root of a number in log n", url: "https://takeuforward.org/binary-search/finding-sqrt-of-a-number-using-binary-search/" },
      { name: "Find the Nth root of a number using binary search", url: "https://takeuforward.org/data-structure/nth-root-of-a-number-using-binary-search/" },
      { name: "Koko Eating Bananas", url: "https://takeuforward.org/binary-search/koko-eating-bananas/", lcUrl: "https://leetcode.com/problems/koko-eating-bananas/" },
      { name: "Minimum days to make M bouquets", url: "https://takeuforward.org/arrays/minimum-days-to-make-m-bouquets/", lcUrl: "https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets/" },
      { name: "Find the smallest Divisor", url: "https://takeuforward.org/arrays/find-the-smallest-divisor-given-a-threshold/", lcUrl: "https://leetcode.com/problems/find-the-smallest-divisor-given-a-threshold/" },
      { name: "Capacity to Ship Packages within D Days", url: "https://takeuforward.org/arrays/capacity-to-ship-packages-within-d-days/", lcUrl: "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/" },
      { name: "Kth Missing Positive Number", url: "https://takeuforward.org/arrays/kth-missing-positive-number/", lcUrl: "https://leetcode.com/problems/kth-missing-positive-number/" },
      { name: "Aggressive Cows", url: "https://takeuforward.org/data-structure/aggressive-cows-detailed-solution/", gfgUrl: "https://www.geeksforgeeks.org/problems/aggressive-cows/0" },
      { name: "Book Allocation Problem", url: "https://takeuforward.org/data-structure/allocate-minimum-number-of-pages/", gfgUrl: "https://www.geeksforgeeks.org/problems/allocate-minimum-number-of-pages0937/1" },
      { name: "Split array - Largest Sum", url: "https://takeuforward.org/arrays/split-array-largest-sum/", lcUrl: "https://leetcode.com/problems/split-array-largest-sum/" },
      { name: "Painter's partition", url: "https://takeuforward.org/arrays/painters-partition-problem/" },
      { name: "Minimize Max Distance to Gas Station", url: "https://takeuforward.org/arrays/minimise-maximum-distance-between-gas-stations/" },
      { name: "Median of 2 sorted arrays", url: "https://takeuforward.org/data-structure/median-of-two-sorted-arrays-of-different-sizes/", lcUrl: "https://leetcode.com/problems/median-of-two-sorted-arrays/", gfgUrl: "https://www.geeksforgeeks.org/problems/median-of-2-sorted-arrays-of-different-sizes/1" },
      { name: "Kth element of 2 sorted arrays", url: "https://takeuforward.org/data-structure/k-th-element-of-two-sorted-arrays/", gfgUrl: "https://www.geeksforgeeks.org/problems/k-th-element-of-two-sorted-array1317/1" },
    ],
  },
  {
    topic: "Binary Search [1D, 2D Arrays, Search Space] - BS on 2D Arrays",
    icon: "🔍",
    questions: [
      { name: "Find the row with maximum number of 1's", url: "https://takeuforward.org/arrays/find-the-row-with-maximum-number-of-1s/" },
      { name: "Search in a 2 D matrix", url: "https://takeuforward.org/data-structure/search-in-a-sorted-2d-matrix/", lcUrl: "https://leetcode.com/problems/search-a-2d-matrix/" },
      { name: "Search in a row and column wise sorted matrix", url: "https://takeuforward.org/arrays/search-in-a-row-and-column-wise-sorted-matrix/", lcUrl: "https://leetcode.com/problems/search-a-2d-matrix-ii/" },
      { name: "Find Peak Element (2D Matrix)", url: "" },
      { name: "Matrix Median", url: "https://takeuforward.org/data-structure/median-of-row-wise-sorted-matrix/", gfgUrl: "https://www.geeksforgeeks.org/problems/median-in-a-row-wise-sorted-matrix1527/1" },
    ],
  },
  {
    topic: "Strings [Basic and Medium] - Basic and Easy String Problems",
    icon: "📝",
    questions: [
      { name: "Remove outermost Paranthesis", url: "", lcUrl: "https://leetcode.com/problems/remove-outermost-parentheses/" },
      { name: "Reverse words in a given string / Palindrome Check", url: "https://takeuforward.org/data-structure/reverse-words-in-a-string/", lcUrl: "https://leetcode.com/problems/reverse-words-in-a-string/" },
      { name: "Largest odd number in a string", url: "", lcUrl: "https://leetcode.com/problems/largest-odd-number-in-string/" },
      { name: "Longest Common Prefix", url: "", lcUrl: "https://leetcode.com/problems/longest-common-prefix/" },
      { name: "Isomorphic String", url: "", lcUrl: "https://leetcode.com/problems/isomorphic-strings/" },
      { name: "check whether one string is a rotation of another", url: "", lcUrl: "https://leetcode.com/problems/rotate-string/" },
      { name: "Check if two strings are anagram of each other", url: "https://takeuforward.org/data-structure/check-if-two-strings-are-anagrams-of-each-other/", lcUrl: "https://leetcode.com/problems/valid-anagram/" },
    ],
  },
  {
    topic: "Strings [Basic and Medium] - Medium String Problems",
    icon: "📝",
    questions: [
      { name: "Sort Characters by frequency", url: "", lcUrl: "https://leetcode.com/problems/sort-characters-by-frequency/" },
      { name: "Maximum Nesting Depth of Paranthesis", url: "", lcUrl: "https://leetcode.com/problems/maximum-nesting-depth-of-the-parentheses/" },
      { name: "Roman Number to Integer and vice versa", url: "", lcUrl: "https://leetcode.com/problems/roman-to-integer/" },
      { name: "Implement Atoi", url: "", lcUrl: "https://leetcode.com/problems/string-to-integer-atoi/" },
      { name: "Count Number of Substrings", url: "" },
      { name: "Longest Palindromic Substring[Do it without DP]", url: "", lcUrl: "https://leetcode.com/problems/longest-palindromic-substring/" },
      { name: "Sum of Beauty of all substring", url: "", lcUrl: "https://leetcode.com/problems/sum-of-beauty-of-all-substrings/" },
      { name: "Reverse Every Word in A String", url: "", lcUrl: "https://leetcode.com/problems/reverse-words-in-a-string/" },
    ],
  },
  {
    topic: "Learn LinkedList [Single LL, Double LL, Medium, Hard Problems] - Learn 1D LinkedList",
    icon: "🔗",
    questions: [
      { name: "Introduction to LinkedList, learn about struct, and how is node represented", url: "https://takeuforward.org/linked-list/linked-list-introduction" },
      { name: "Inserting a node in LinkedList", url: "https://takeuforward.org/linked-list/insert-at-the-head-of-a-linked-list" },
      { name: "Deleting a node in LinkedList", url: "https://takeuforward.org/data-structure/delete-last-node-of-linked-list/" },
      { name: "Find the length of the linkedlist [learn traversal]", url: "https://takeuforward.org/linked-list/find-the-length-of-a-linked-list" },
      { name: "Search an element in the LL", url: "https://takeuforward.org/linked-list/search-an-element-in-a-linked-list" },
    ],
  },
  {
    topic: "Learn LinkedList [Single LL, Double LL, Medium, Hard Problems] - Learn Doubly LinkedList",
    icon: "🔗",
    questions: [
      { name: "Introduction to DLL, learn about struct, and how is node represented", url: "https://takeuforward.org/linked-list/introduction-to-doubly-linked-list" },
      { name: "Insert a node in DLL", url: "https://takeuforward.org/data-structure/insert-at-end-of-doubly-linked-list/" },
      { name: "Delete a node in DLL", url: "https://takeuforward.org/data-structure/delete-last-node-of-a-doubly-linked-list/" },
      { name: "Reverse a DLL", url: "https://takeuforward.org/data-structure/reverse-a-doubly-linked-list/" },
    ],
  },
  {
    topic: "Learn LinkedList [Single LL, Double LL, Medium, Hard Problems] - Medium Problems of LL",
    icon: "🔗",
    questions: [
      { name: "Middle of a LinkedList [TortoiseHare Method]", url: "https://takeuforward.org/data-structure/find-middle-element-in-a-linked-list/", lcUrl: "https://leetcode.com/problems/middle-of-the-linked-list/" },
      { name: "Reverse a LinkedList [Iterative]", url: "https://takeuforward.org/data-structure/reverse-a-linked-list/", lcUrl: "https://leetcode.com/problems/reverse-linked-list/" },
      { name: "Reverse a LL [Recursive]", url: "https://takeuforward.org/data-structure/reverse-a-linked-list/", lcUrl: "https://leetcode.com/problems/reverse-linked-list/" },
      { name: "Detect a loop in LL", url: "https://takeuforward.org/data-structure/detect-a-cycle-in-a-linked-list/", lcUrl: "https://leetcode.com/problems/linked-list-cycle/" },
      { name: "Find the starting point in LL", url: "https://takeuforward.org/data-structure/starting-point-of-loop-in-a-linked-list/", lcUrl: "https://leetcode.com/problems/linked-list-cycle-ii/" },
      { name: "Length of Loop in LL", url: "https://takeuforward.org/linked-list/length-of-loop-in-linked-list" },
      { name: "Check if LL is palindrome or not", url: "https://takeuforward.org/data-structure/check-if-given-linked-list-is-plaindrome/", lcUrl: "https://leetcode.com/problems/palindrome-linked-list/" },
      { name: "Segrregate odd and even nodes in LL", url: "https://takeuforward.org/data-structure/segregate-even-and-odd-nodes-in-linkedlist", lcUrl: "https://leetcode.com/problems/odd-even-linked-list/" },
      { name: "Remove Nth node from the back of the LL", url: "https://takeuforward.org/data-structure/remove-n-th-node-from-the-end-of-a-linked-list/", lcUrl: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/" },
      { name: "Delete the middle node of LL", url: "https://takeuforward.org/linked-list/delete-the-middle-node-of-the-linked-list", lcUrl: "https://leetcode.com/problems/delete-the-middle-node-of-a-linked-list/" },
      { name: "Sort LL", url: "https://takeuforward.org/linked-list/sort-a-linked-list", lcUrl: "https://leetcode.com/problems/sort-list/" },
      { name: "Sort a LL of 0's 1's and 2's by changing links", url: "" },
      { name: "Find the intersection point of Y LL", url: "https://takeuforward.org/data-structure/find-intersection-of-two-linked-lists/", lcUrl: "https://leetcode.com/problems/intersection-of-two-linked-lists/" },
      { name: "Add 1 to a number represented by LL", url: "" },
      { name: "Add 2 numbers in LL", url: "https://takeuforward.org/data-structure/add-two-numbers-represented-as-linked-lists/", lcUrl: "https://leetcode.com/problems/add-two-numbers/" },
    ],
  },
  {
    topic: "Learn LinkedList [Single LL, Double LL, Medium, Hard Problems] - Medium Problems of DLL",
    icon: "🔗",
    questions: [
      { name: "Delete all occurrences of a key in DLL", url: "" },
      { name: "Find pairs with given sum in DLL", url: "" },
      { name: "Remove duplicates from sorted DLL", url: "" },
    ],
  },
  {
    topic: "Learn LinkedList [Single LL, Double LL, Medium, Hard Problems] - Hard Problems of LL",
    icon: "🔗",
    questions: [
      { name: "Reverse LL in group of given size K", url: "https://takeuforward.org/data-structure/reverse-linked-list-in-groups-of-size-k/", lcUrl: "https://leetcode.com/problems/reverse-nodes-in-k-group/" },
      { name: "Rotate a LL", url: "https://takeuforward.org/data-structure/rotate-a-linked-list/", lcUrl: "https://leetcode.com/problems/rotate-list/" },
      { name: "Flattening of LL", url: "https://takeuforward.org/data-structure/flattening-a-linked-list/", gfgUrl: "https://www.geeksforgeeks.org/problems/flattening-a-linked-list/1" },
      { name: "Clone a Linked List with random and next pointer", url: "https://takeuforward.org/data-structure/clone-linked-list-with-random-and-next-pointer/", lcUrl: "https://leetcode.com/problems/copy-list-with-random-pointer/" },
    ],
  },
  {
    topic: "Recursion [PatternWise] - Get a Strong Hold",
    icon: "🔄",
    questions: [
      { name: "Recursive Implementation of atoi()", url: "" },
      { name: "Pow(x, n)", url: "https://takeuforward.org/data-structure/implement-powxn-x-raised-to-the-power-n/", lcUrl: "https://leetcode.com/problems/powx-n/" },
      { name: "Count Good numbers", url: "", lcUrl: "https://leetcode.com/problems/count-good-numbers/" },
      { name: "Sort a stack using recursion", url: "" },
      { name: "Reverse a stack using recursion", url: "" },
    ],
  },
  {
    topic: "Recursion [PatternWise] - Subsequences Pattern",
    icon: "🔄",
    questions: [
      { name: "Generate all binary strings", url: "" },
      { name: "Generate Paranthesis", url: "", lcUrl: "https://leetcode.com/problems/generate-parentheses/" },
      { name: "Print all subsequences/Power Set", url: "https://takeuforward.org/data-structure/power-set-print-all-the-possible-subsequences-of-the-string/" },
      { name: "Learn All Patterns of Subsequences (Theory)", url: "" },
      { name: "Count all subsequences with sum K", url: "" },
      { name: "Check if there exists a subsequence with sum K", url: "" },
      { name: "Combination Sum", url: "https://takeuforward.org/data-structure/combination-sum-1/", lcUrl: "https://leetcode.com/problems/combination-sum/", gfgUrl: "https://www.geeksforgeeks.org/problems/combination-sum-1587115620/1" },
      { name: "Combination Sum-II", url: "https://takeuforward.org/data-structure/combination-sum-ii-find-all-unique-combinations/", lcUrl: "https://leetcode.com/problems/combination-sum-ii/" },
      { name: "Subset Sum-I", url: "https://takeuforward.org/data-structure/subset-sum-sum-of-all-subsets/" },
      { name: "Subset Sum-II", url: "https://takeuforward.org/data-structure/subset-ii-print-all-the-unique-subsets/", lcUrl: "https://leetcode.com/problems/subsets-ii/" },
      { name: "Combination Sum - III", url: "", lcUrl: "https://leetcode.com/problems/combination-sum-iii/" },
      { name: "Letter Combinations of a Phone number", url: "", lcUrl: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/" },
    ],
  },
  {
    topic: "Recursion [PatternWise] - Trying out all Combos / Hard",
    icon: "🔄",
    questions: [
      { name: "Palindrome Partitioning", url: "https://takeuforward.org/data-structure/palindrome-partitioning/", lcUrl: "https://leetcode.com/problems/palindrome-partitioning/" },
      { name: "Word Search", url: "https://takeuforward.org/data-structure/word-search-leetcode/", lcUrl: "https://leetcode.com/problems/word-search/" },
      { name: "N Queen", url: "https://takeuforward.org/data-structure/n-queen-problem-return-all-distinct-solutions-to-the-n-queens-puzzle/", lcUrl: "https://leetcode.com/problems/n-queens/", gfgUrl: "https://www.geeksforgeeks.org/problems/n-queen-problem0315/1" },
      { name: "Rat in a Maze", url: "https://takeuforward.org/data-structure/rat-in-a-maze/", gfgUrl: "https://www.geeksforgeeks.org/problems/rat-in-a-maze-problem/1" },
      { name: "Word Break", url: "", lcUrl: "https://leetcode.com/problems/word-break/" },
      { name: "M Coloring Problem", url: "https://takeuforward.org/data-structure/m-coloring-problem/", gfgUrl: "https://www.geeksforgeeks.org/problems/m-coloring-problem-1587115620/1" },
      { name: "Sudoko Solver", url: "https://takeuforward.org/data-structure/sudoku-solver/", lcUrl: "https://leetcode.com/problems/sudoku-solver/", gfgUrl: "https://www.geeksforgeeks.org/problems/solve-the-sudoku-1587115621/1" },
      { name: "Expression Add Operators", url: "", lcUrl: "https://leetcode.com/problems/expression-add-operators/" },
    ],
  },
  {
    topic: "Bit Manipulation [Concepts & Problems] - Learn Bit Manipulation",
    icon: "🧮",
    questions: [
      { name: "Introduction to Bit Manipulation [Theory]", url: "" },
      { name: "Check if the i-th bit is set or not", url: "" },
      { name: "Check if a number is odd or not", url: "" },
      { name: "Check if a number is power of 2 or not", url: "", lcUrl: "https://leetcode.com/problems/power-of-two/" },
      { name: "Count the number of set bits", url: "", lcUrl: "https://leetcode.com/problems/number-of-1-bits/" },
      { name: "Set/Unset the rightmost unset bit", url: "" },
      { name: "Swap two numbers", url: "" },
      { name: "Divide two integers without using multiplication, division and mod operator", url: "", lcUrl: "https://leetcode.com/problems/divide-two-integers/" },
    ],
  },
  {
    topic: "Bit Manipulation [Concepts & Problems] - Interview Problems",
    icon: "🧮",
    questions: [
      { name: "Count number of bits to be flipped to convert A to B", url: "" },
      { name: "Find the number that appears odd number of times", url: "", lcUrl: "https://leetcode.com/problems/single-number/" },
      { name: "Power Set", url: "", lcUrl: "https://leetcode.com/problems/subsets/" },
      { name: "Find xor of numbers from L to R", url: "" },
      { name: "Find the two numbers appearing odd number of times", url: "" },
    ],
  },
  {
    topic: "Bit Manipulation [Concepts & Problems] - Advanced Maths",
    icon: "🧮",
    questions: [
      { name: "Print Prime Factors of a Number", url: "" },
      { name: "All Divisors of a Number", url: "" },
      { name: "Sieve of Eratosthenes", url: "" },
      { name: "Find Prime Factorisation of a Number using Sieve", url: "" },
      { name: "Power(n, x)", url: "" },
    ],
  },
  {
    topic: "Stack and Queues [Learning, Pre-In-Post-fix, Monotonic Stack, Implementation] - Learning",
    icon: "📚",
    questions: [
      { name: "Implement Stack using Arrays", url: "https://takeuforward.org/data-structure/implement-stack-using-array/" },
      { name: "Implement Queue using Arrays", url: "https://takeuforward.org/data-structure/implement-queue-using-array/" },
      { name: "Implement Stack using Queue", url: "https://takeuforward.org/data-structure/implement-stack-using-single-queue/", lcUrl: "https://leetcode.com/problems/implement-stack-using-queues/" },
      { name: "Implement Queue using Stack", url: "https://takeuforward.org/data-structure/implement-queue-using-stack/", lcUrl: "https://leetcode.com/problems/implement-queue-using-stacks/" },
      { name: "Implement stack using Linkedlist", url: "https://takeuforward.org/data-structure/implement-stack-using-linked-list/" },
      { name: "Implement queue using Linkedlist", url: "https://takeuforward.org/data-structure/implement-queue-using-linked-list/" },
      { name: "Check for balanced paranthesis", url: "https://takeuforward.org/data-structure/check-for-balanced-parentheses/", lcUrl: "https://leetcode.com/problems/valid-parentheses/" },
      { name: "Implement Min Stack", url: "https://takeuforward.org/data-structure/implement-min-stack-o2n-and-on-space-complexity/", lcUrl: "https://leetcode.com/problems/min-stack/" },
    ],
  },
  {
    topic: "Stack and Queues [Learning, Pre-In-Post-fix, Monotonic Stack, Implementation] - Prefix, Infix, PostFix Conversion Problems",
    icon: "📚",
    questions: [
      { name: "Infix to Postfix Conversion using Stack", url: "https://takeuforward.org/data-structure/infix-to-postfix/" },
      { name: "Prefix to Infix Conversion", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2" },
      { name: "Prefix to Postfix Conversion", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2" },
      { name: "Postfix to Prefix Conversion", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2" },
      { name: "Postfix to Infix", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2" },
      { name: "Convert Infix To Prefix Notation", url: "https://takeuforward.org/data-structure/infix-to-prefix/" },
    ],
  },
  {
    topic: "Stack and Queues [Learning, Pre-In-Post-fix, Monotonic Stack, Implementation] - Monotonic Stack/Queue Problems [VVV. Imp]",
    icon: "📚",
    questions: [
      { name: "Next Greater Element", url: "https://takeuforward.org/data-structure/next-greater-element-using-stack/", lcUrl: "https://leetcode.com/problems/next-greater-element-i/" },
      { name: "Next Greater Element 2", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2", lcUrl: "https://leetcode.com/problems/next-greater-element-ii/" },
      { name: "Next Smaller Element", url: "" },
      { name: "Number of NGEs to the right", url: "" },
      { name: "Trapping Rainwater", url: "https://takeuforward.org/data-structure/trapping-rainwater/", lcUrl: "https://leetcode.com/problems/trapping-rain-water/", gfgUrl: "https://www.geeksforgeeks.org/problems/trapping-rain-water-1587115621/1" },
      { name: "Sum of subarray minimum", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2", lcUrl: "https://leetcode.com/problems/sum-of-subarray-minimums/" },
      { name: "Asteroid Collision", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2", lcUrl: "https://leetcode.com/problems/asteroid-collision/" },
      { name: "Sum of subarray ranges", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2", lcUrl: "https://leetcode.com/problems/sum-of-subarray-ranges/" },
      { name: "Remove k Digits", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2", lcUrl: "https://leetcode.com/problems/remove-k-digits/" },
      { name: "Largest rectangle in a histogram", url: "https://takeuforward.org/data-structure/area-of-largest-rectangle-in-histogram/", lcUrl: "https://leetcode.com/problems/largest-rectangle-in-histogram/", gfgUrl: "https://www.geeksforgeeks.org/problems/maximum-rectangular-area-in-a-histogram-1587115620/1" },
      { name: "Maximal Rectangles", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2", lcUrl: "https://leetcode.com/problems/maximal-rectangle/" },
    ],
  },
  {
    topic: "Stack and Queues [Learning, Pre-In-Post-fix, Monotonic Stack, Implementation] - Implementation Problems",
    icon: "📚",
    questions: [
      { name: "Sliding Window maximum", url: "https://takeuforward.org/data-structure/sliding-window-maximum/", lcUrl: "https://leetcode.com/problems/sliding-window-maximum/" },
      { name: "Stock span problem", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2", lcUrl: "https://leetcode.com/problems/online-stock-span/" },
      { name: "The Celebrity Problem", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2", gfgUrl: "https://www.geeksforgeeks.org/problems/the-celebrity-problem/1" },
      { name: "LRU cache (IMPORTANT)", url: "https://takeuforward.org/data-structure/implement-lru-cache/", lcUrl: "https://leetcode.com/problems/lru-cache/" },
      { name: "LFU cache", url: "", lcUrl: "https://leetcode.com/problems/lfu-cache/" },
    ],
  },
  {
    topic: "Sliding Window & Two Pointer Combined Problems - Medium Problems",
    icon: "🪟",
    questions: [
      { name: "Longest Substring Without Repeating Characters", url: "https://takeuforward.org/data-structure/length-of-longest-substring-without-any-repeating-character/", lcUrl: "https://leetcode.com/problems/longest-substring-without-repeating-characters/" },
      { name: "Max Consecutive Ones III", url: "", lcUrl: "https://leetcode.com/problems/max-consecutive-ones-iii/" },
      { name: "Fruit Into Baskets", url: "", lcUrl: "https://leetcode.com/problems/fruit-into-baskets/" },
      { name: "longest repeating character replacement", url: "", lcUrl: "https://leetcode.com/problems/longest-repeating-character-replacement/" },
      { name: "Binary subarray with sum", url: "", lcUrl: "https://leetcode.com/problems/binary-subarrays-with-sum/" },
      { name: "Count number of nice subarrays", url: "", lcUrl: "https://leetcode.com/problems/count-number-of-nice-subarrays/" },
      { name: "Number of substring containing all three characters", url: "", lcUrl: "https://leetcode.com/problems/number-of-substrings-containing-all-three-characters/" },
      { name: "Maximum point you can obtain from cards", url: "", lcUrl: "https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards/" },
    ],
  },
  {
    topic: "Sliding Window & Two Pointer Combined Problems - Hard Problems",
    icon: "🪟",
    questions: [
      { name: "Longest Substring with At Most K Distinct Characters", url: "", lcUrl: "https://leetcode.com/problems/longest-substring-with-at-most-k-distinct-characters/" },
      { name: "Subarray with k different integers", url: "", lcUrl: "https://leetcode.com/problems/subarrays-with-k-different-integers/" },
      { name: "Minimum Window Substring", url: "", lcUrl: "https://leetcode.com/problems/minimum-window-substring/" },
      { name: "Minimum Window Subsequence", url: "", lcUrl: "https://leetcode.com/problems/minimum-window-subsequence/" },
    ],
  },
  {
    topic: "Heaps [Learning, Medium, Hard Problems] - Learning",
    icon: "⚙️",
    questions: [
      { name: "Introduction to Priority Queues using Binary Heaps", url: "" },
      { name: "Min Heap and Max Heap Implementation", url: "" },
      { name: "Check if an array represents a min-heap or not", url: "" },
      { name: "Convert min Heap to max Heap", url: "" },
    ],
  },
  {
    topic: "Heaps [Learning, Medium, Hard Problems] - Medium Problems",
    icon: "⚙️",
    questions: [
      { name: "Kth largest element in an array [use priority queue]", url: "https://takeuforward.org/data-structure/kth-largest-smallest-element-in-an-array/", lcUrl: "https://leetcode.com/problems/kth-largest-element-in-an-array/" },
      { name: "Kth smallest element in an array [use priority queue]", url: "https://takeuforward.org/data-structure/kth-largest-smallest-element-in-an-array/" },
      { name: "Sort K sorted array", url: "" },
      { name: "Merge M sorted Lists", url: "" },
      { name: "Replace each array element by its corresponding rank", url: "https://takeuforward.org/data-structure/replace-elements-by-its-rank-in-the-array/" },
      { name: "Task Scheduler", url: "", lcUrl: "https://leetcode.com/problems/task-scheduler/" },
      { name: "Hands of Straights", url: "", lcUrl: "https://leetcode.com/problems/hand-of-straights/" },
    ],
  },
  {
    topic: "Heaps [Learning, Medium, Hard Problems] - Hard Problems",
    icon: "⚙️",
    questions: [
      { name: "Design twitter", url: "", lcUrl: "https://leetcode.com/problems/design-twitter/" },
      { name: "Connect `n` ropes with minimal cost", url: "" },
      { name: "Kth largest element in a stream of running integers", url: "", lcUrl: "https://leetcode.com/problems/kth-largest-element-in-a-stream/" },
      { name: "Maximum Sum Combination", url: "" },
      { name: "Find Median from Data Stream", url: "", lcUrl: "https://leetcode.com/problems/find-median-from-data-stream/" },
      { name: "K most frequent elements", url: "", lcUrl: "https://leetcode.com/problems/top-k-frequent-elements/" },
    ],
  },
  {
    topic: "Greedy Algorithms [Easy, Medium/Hard] - Easy Problems",
    icon: "💰",
    questions: [
      { name: "Assign Cookies", url: "https://takeuforward.org/Greedy/assign-cookies", lcUrl: "https://leetcode.com/problems/assign-cookies/" },
      { name: "Fractional Knapsack Problem", url: "https://takeuforward.org/data-structure/fractional-knapsack-problem-greedy-approach/", gfgUrl: "https://www.geeksforgeeks.org/problems/fractional-knapsack-1587115620/1" },
      { name: "Greedy algorithm to find minimum number of coins", url: "https://takeuforward.org/data-structure/find-minimum-number-of-coins/" },
      { name: "Lemonade Change", url: "https://takeuforward.org/Greedy/lemonade-change", lcUrl: "https://leetcode.com/problems/lemonade-change/" },
      { name: "Valid Paranthesis Checker", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2" },
    ],
  },
  {
    topic: "Greedy Algorithms [Easy, Medium/Hard] - Medium/Hard",
    icon: "💰",
    questions: [
      { name: "N meetings in one room", url: "https://takeuforward.org/data-structure/n-meetings-in-one-room/", gfgUrl: "https://www.geeksforgeeks.org/problems/n-meetings-in-one-room-1587115620/1" },
      { name: "Jump Game", url: "https://takeuforward.org/Greedy/jump-game-i", lcUrl: "https://leetcode.com/problems/jump-game/" },
      { name: "Jump Game 2", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2", lcUrl: "https://leetcode.com/problems/jump-game-ii/" },
      { name: "Minimum number of platforms required for a railway", url: "https://takeuforward.org/data-structure/minimum-number-of-platforms-required-for-a-railway/", gfgUrl: "https://www.geeksforgeeks.org/problems/minimum-platforms-1587115620/1" },
      { name: "Job sequencing Problem", url: "https://takeuforward.org/data-structure/job-sequencing-problem/", gfgUrl: "https://www.geeksforgeeks.org/problems/job-sequencing-problem-1587115620/1" },
      { name: "Candy", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2", lcUrl: "https://leetcode.com/problems/candy/" },
      { name: "Program for Shortest Job First (or SJF) CPU Scheduling", url: "https://takeuforward.org/Greedy/shortest-job-first-or-sjf-cpu-scheduling" },
      { name: "Program for Least Recently Used (LRU) Page Replacement Algorithm", url: "" },
      { name: "Insert Interval", url: "https://takeuforward.org/?s=Insert+Interval", lcUrl: "https://leetcode.com/problems/insert-interval/" },
      { name: "Merge Intervals", url: "https://takeuforward.org/data-structure/merge-overlapping-sub-intervals/", lcUrl: "https://leetcode.com/problems/merge-intervals/" },
      { name: "Non-overlapping Intervals", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2", lcUrl: "https://leetcode.com/problems/non-overlapping-intervals/" },
    ],
  },
  {
    topic: "Binary Trees [Traversals, Medium and Hard Problems] - Traversals",
    icon: "🌳",
    questions: [
      { name: "Introduction to Trees", url: "https://takeuforward.org/binary-tree/introduction-to-trees/" },
      { name: "Binary Tree Representation in C++", url: "https://takeuforward.org/binary-tree/binary-tree-representation-in-c/" },
      { name: "Binary Tree Representation in Java", url: "https://takeuforward.org/binary-tree/binary-tree-representation-in-java/" },
      { name: "Binary Tree Traversals in Binary Tree", url: "https://takeuforward.org/binary-tree/binary-tree-traversal-inorder-preorder-postorder/" },
      { name: "Preorder Traversal of Binary Tree", url: "https://takeuforward.org/data-structure/preorder-traversal-of-binary-tree/", lcUrl: "https://leetcode.com/problems/binary-tree-preorder-traversal/" },
      { name: "Inorder Traversal of Binary Tree", url: "https://takeuforward.org/data-structure/inorder-traversal-of-binary-tree/", lcUrl: "https://leetcode.com/problems/binary-tree-inorder-traversal/" },
      { name: "Post-order Traversal of Binary Tree", url: "https://takeuforward.org/data-structure/post-order-traversal-of-binary-tree/", lcUrl: "https://leetcode.com/problems/binary-tree-postorder-traversal/" },
      { name: "Level order Traversal / Level order traversal in spiral form", url: "https://takeuforward.org/data-structure/level-order-traversal-of-a-binary-tree/", lcUrl: "https://leetcode.com/problems/binary-tree-level-order-traversal/" },
      { name: "Iterative Preorder Traversal of Binary Tree", url: "https://takeuforward.org/data-structure/iterative-preorder-traversal-of-binary-tree", lcUrl: "https://leetcode.com/problems/binary-tree-preorder-traversal/" },
      { name: "Iterative Inorder Traversal of Binary Tree", url: "https://takeuforward.org/data-structure/inorder-traversal-of-binary-tree/", lcUrl: "https://leetcode.com/problems/binary-tree-inorder-traversal/" },
      { name: "Post-order Traversal of Binary Tree using 2 stack", url: "https://takeuforward.org/data-structure/iterative-postorder-traversal-of-binary-tree-using-2-stack", lcUrl: "https://leetcode.com/problems/binary-tree-postorder-traversal/" },
      { name: "Post-order Traversal of Binary Tree using 1 stack", url: "https://takeuforward.org/data-structure/post-order-traversal-of-binary-tree/", lcUrl: "https://leetcode.com/problems/binary-tree-postorder-traversal/" },
      { name: "Preorder, Inorder, and Postorder Traversal in one Traversal", url: "https://takeuforward.org/data-structure/preorder-inorder-postorder-traversals-in-one-traversal/" },
    ],
  },
  {
    topic: "Binary Trees [Traversals, Medium and Hard Problems] - Medium Problems",
    icon: "🌳",
    questions: [
      { name: "Height of a Binary Tree", url: "https://takeuforward.org/data-structure/maximum-depth-of-a-binary-tree/", lcUrl: "https://leetcode.com/problems/maximum-depth-of-binary-tree/", gfgUrl: "https://www.geeksforgeeks.org/problems/height-of-binary-tree/1" },
      { name: "Check if the Binary tree is height-balanced or not", url: "https://takeuforward.org/data-structure/check-if-the-binary-tree-is-balanced-binary-tree/", lcUrl: "https://leetcode.com/problems/balanced-binary-tree/", gfgUrl: "https://www.geeksforgeeks.org/problems/check-for-balanced-tree/1" },
      { name: "Diameter of Binary Tree", url: "https://takeuforward.org/data-structure/calculate-the-diameter-of-a-binary-tree/", lcUrl: "https://leetcode.com/problems/diameter-of-binary-tree/", gfgUrl: "https://www.geeksforgeeks.org/problems/diameter-of-binary-tree/1" },
      { name: "Maximum path sum", url: "https://takeuforward.org/data-structure/maximum-sum-path-in-binary-tree/", lcUrl: "https://leetcode.com/problems/binary-tree-maximum-path-sum/" },
      { name: "Check if two trees are identical or not", url: "https://takeuforward.org/data-structure/check-if-two-trees-are-identical/", lcUrl: "https://leetcode.com/problems/same-tree/" },
      { name: "Zig Zag Traversal of Binary Tree", url: "https://takeuforward.org/data-structure/zig-zag-traversal-of-binary-tree/", lcUrl: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/" },
      { name: "Boundary Traversal of Binary Tree", url: "https://takeuforward.org/data-structure/boundary-traversal-of-a-binary-tree/", lcUrl: "https://leetcode.com/problems/boundary-of-binary-tree/", gfgUrl: "https://www.geeksforgeeks.org/problems/boundary-traversal-of-binary-tree/1" },
      { name: "Vertical Order Traversal of Binary Tree", url: "https://takeuforward.org/data-structure/vertical-order-traversal-of-binary-tree/", lcUrl: "https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/" },
      { name: "Top View of Binary Tree", url: "https://takeuforward.org/data-structure/top-view-of-a-binary-tree/", gfgUrl: "https://www.geeksforgeeks.org/problems/top-view-of-binary-tree/1" },
      { name: "Bottom View of Binary Tree", url: "https://takeuforward.org/data-structure/bottom-view-of-a-binary-tree/", gfgUrl: "https://www.geeksforgeeks.org/problems/bottom-view-of-binary-tree/1" },
      { name: "Right/Left View of Binary Tree", url: "https://takeuforward.org/data-structure/right-left-view-of-binary-tree/", lcUrl: "https://leetcode.com/problems/binary-tree-right-side-view/", gfgUrl: "https://www.geeksforgeeks.org/problems/left-view-of-binary-tree/1" },
      { name: "Symmetric Binary Tree", url: "https://takeuforward.org/data-structure/check-for-symmetrical-binary-tree/", lcUrl: "https://leetcode.com/problems/symmetric-tree/" },
    ],
  },
  {
    topic: "Binary Trees [Traversals, Medium and Hard Problems] - Hard Problems",
    icon: "🌳",
    questions: [
      { name: "Root to Node Path in Binary Tree", url: "https://takeuforward.org/data-structure/print-root-to-node-path-in-a-binary-tree/" },
      { name: "LCA in Binary Tree", url: "https://takeuforward.org/data-structure/lowest-common-ancestor-for-two-given-nodes/", lcUrl: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/", gfgUrl: "https://www.geeksforgeeks.org/problems/lowest-common-ancestor-in-a-binary-tree/1" },
      { name: "Maximum width of a Binary Tree", url: "https://takeuforward.org/data-structure/maximum-width-of-a-binary-tree/", lcUrl: "https://leetcode.com/problems/maximum-width-of-binary-tree/" },
      { name: "Check for Children Sum Property", url: "https://takeuforward.org/data-structure/check-for-children-sum-property-in-a-binary-tree/", gfgUrl: "https://www.geeksforgeeks.org/problems/children-sum-parent/1" },
      { name: "Print all the Nodes at a distance of K in a Binary Tree", url: "", lcUrl: "https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree/" },
      { name: "Minimum time taken to BURN the Binary Tree from a Node", url: "" },
      { name: "Count total Nodes in a COMPLETE Binary Tree", url: "https://takeuforward.org/binary-tree/count-number-of-nodes-in-a-binary-tree/", lcUrl: "https://leetcode.com/problems/count-complete-tree-nodes/" },
      { name: "Requirements needed to construct a Unique Binary Tree | Theory", url: "" },
      { name: "Construct Binary Tree from inorder and preorder", url: "https://takeuforward.org/data-structure/construct-a-binary-tree-from-inorder-and-preorder-traversal/", lcUrl: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/" },
      { name: "Construct the Binary Tree from Postorder and Inorder Traversal", url: "https://takeuforward.org/data-structure/construct-binary-tree-from-inorder-and-postorder-traversal/", lcUrl: "https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/" },
      { name: "Serialize and deserialize Binary Tree", url: "https://takeuforward.org/data-structure/serialize-and-deserialize-a-binary-tree/", lcUrl: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/" },
      { name: "Morris Preorder Traversal of a Binary Tree", url: "https://takeuforward.org/data-structure/morris-preorder-traversal-of-a-binary-tree/", lcUrl: "https://leetcode.com/problems/binary-tree-preorder-traversal/" },
      { name: "Morris Inorder Traversal of a Binary Tree", url: "https://takeuforward.org/data-structure/morris-inorder-traversal-of-a-binary-tree/", lcUrl: "https://leetcode.com/problems/binary-tree-inorder-traversal/" },
      { name: "Flatten Binary Tree to LinkedList", url: "https://takeuforward.org/data-structure/flatten-binary-tree-to-linked-list/", lcUrl: "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/" },
    ],
  },
  {
    topic: "Binary Search Trees [Concept and Problems] - Concepts",
    icon: "🌲",
    questions: [
      { name: "Introduction to Binary Search Tree", url: "https://takeuforward.org/binary-search-tree/introduction-to-binary-search-trees/" },
      { name: "Search in a Binary Search Tree", url: "https://takeuforward.org/data-structure/search-in-a-binary-search-tree-2/", lcUrl: "https://leetcode.com/problems/search-in-a-binary-search-tree/" },
      { name: "Find Min/Max in BST", url: "" },
    ],
  },
  {
    topic: "Binary Search Trees [Concept and Problems] - Practice Problems",
    icon: "🌲",
    questions: [
      { name: "Ceil in a Binary Search Tree", url: "https://takeuforward.org/binary-search-tree/ceil-in-a-binary-search-tree/" },
      { name: "Floor in a Binary Search Tree", url: "https://takeuforward.org/binary-search-tree/floor-in-a-binary-search-tree/" },
      { name: "Insert a given Node in Binary Search Tree", url: "", lcUrl: "https://leetcode.com/problems/insert-into-a-binary-search-tree/" },
      { name: "Delete a Node in Binary Search Tree", url: "", lcUrl: "https://leetcode.com/problems/delete-node-in-a-bst/" },
      { name: "Find K-th smallest/largest element in BST", url: "https://takeuforward.org/data-structure/kth-largest-smallest-element-in-binary-search-tree/", lcUrl: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/" },
      { name: "Check if a tree is a BST or BT", url: "", lcUrl: "https://leetcode.com/problems/validate-binary-search-tree/" },
      { name: "LCA in Binary Search Tree", url: "", lcUrl: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/" },
      { name: "Construct a BST from a preorder traversal", url: "", lcUrl: "https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/" },
      { name: "Inorder Successor/Predecessor in BST", url: "" },
      { name: "Merge 2 BST's", url: "" },
      { name: "Two Sum In BST | Check if there exists a pair with Sum K", url: "", lcUrl: "https://leetcode.com/problems/two-sum-iv-input-is-a-bst/" },
      { name: "Recover BST | Correct BST with two nodes swapped", url: "", lcUrl: "https://leetcode.com/problems/recover-binary-search-tree/" },
      { name: "Largest BST in Binary Tree", url: "" },
    ],
  },
  {
    topic: "Graphs [Concepts & Problems] - Learning",
    icon: "🕸️",
    questions: [
      { name: "Graph and Types", url: "https://takeuforward.org/graph/introduction-to-graph/" },
      { name: "Graph Representation | C++", url: "https://takeuforward.org/graph/graph-representation-in-c/" },
      { name: "Graph Representation | Java", url: "" },
      { name: "Connected Components | Logic Explanation", url: "https://takeuforward.org/graph/connected-components-in-graphs/" },
      { name: "BFS", url: "https://takeuforward.org/graph/breadth-first-search-bfs-level-order-traversal/", gfgUrl: "https://www.geeksforgeeks.org/problems/bfs-traversal-of-graph/1" },
      { name: "DFS", url: "https://takeuforward.org/data-structure/depth-first-search-dfs/", gfgUrl: "https://www.geeksforgeeks.org/problems/depth-first-traversal-for-a-graph/1" },
    ],
  },
  {
    topic: "Graphs [Concepts & Problems] - Problems on BFS/DFS",
    icon: "🕸️",
    questions: [
      { name: "Number of provinces (leetcode)", url: "https://takeuforward.org/data-structure/number-of-provinces/", lcUrl: "https://leetcode.com/problems/number-of-provinces/" },
      { name: "Connected Components Problem in Matrix", url: "" },
      { name: "Rotten Oranges", url: "https://takeuforward.org/data-structure/rotten-oranges-min-time-to-rot-all-oranges-bfs/", lcUrl: "https://leetcode.com/problems/rotting-oranges/", gfgUrl: "https://www.geeksforgeeks.org/problems/rotten-oranges2536/1" },
      { name: "Flood fill", url: "https://takeuforward.org/graph/flood-fill-algorithm-graphs/", lcUrl: "https://leetcode.com/problems/flood-fill/" },
      { name: "Cycle Detection in unirected Graph (bfs)", url: "https://takeuforward.org/data-structure/detect-cycle-in-an-undirected-graph-using-bfs/", gfgUrl: "https://www.geeksforgeeks.org/problems/detect-cycle-in-an-undirected-graph/1" },
      { name: "Cycle Detection in undirected Graph (dfs)", url: "https://takeuforward.org/data-structure/detect-cycle-in-an-undirected-graph-using-dfs/", gfgUrl: "https://www.geeksforgeeks.org/problems/detect-cycle-in-an-undirected-graph/1" },
      { name: "0/1 Matrix (Bfs Problem)", url: "https://takeuforward.org/graph/distance-of-nearest-cell-having-1/", lcUrl: "https://leetcode.com/problems/01-matrix/" },
      { name: "Surrounded Regions (dfs)", url: "https://takeuforward.org/graph/surrounded-regions-replace-os-with-xs/", lcUrl: "https://leetcode.com/problems/surrounded-regions/" },
      { name: "Number of Enclaves [flood fill implementation - multisource]", url: "https://takeuforward.org/graph/number-of-enclaves/", lcUrl: "https://leetcode.com/problems/number-of-enclaves/" },
      { name: "Word ladder - 1", url: "https://takeuforward.org/graph/word-ladder-i-g-29/", lcUrl: "https://leetcode.com/problems/word-ladder/" },
      { name: "Word ladder - 2", url: "https://takeuforward.org/graph/g-30-word-ladder-ii/", lcUrl: "https://leetcode.com/problems/word-ladder-ii/" },
      { name: "Number of Distinct Islands [dfs multisource]", url: "https://takeuforward.org/data-structure/number-of-islands/", lcUrl: "https://leetcode.com/problems/number-of-distinct-islands/" },
      { name: "Bipartite Graph (DFS)", url: "https://takeuforward.org/graph/bipartite-graph-dfs-implementation/", lcUrl: "https://leetcode.com/problems/is-graph-bipartite/" },
      { name: "Cycle Detection in Directed Graph (DFS)", url: "https://takeuforward.org/data-structure/detect-cycle-in-a-directed-graph-using-dfs-g-19/", lcUrl: "https://leetcode.com/problems/course-schedule/" },
    ],
  },
  {
    topic: "Graphs [Concepts & Problems] - Topo Sort and Problems",
    icon: "🕸️",
    questions: [
      { name: "Topo Sort", url: "https://takeuforward.org/data-structure/topological-sort-algorithm-dfs-g-21/", gfgUrl: "https://www.geeksforgeeks.org/problems/topological-sort/1" },
      { name: "Kahn's Algorithm", url: "https://takeuforward.org/data-structure/kahns-algorithm-topological-sort-algorithm-bfs-g-22/" },
      { name: "Cycle Detection in Directed Graph (BFS)", url: "" },
      { name: "Course Schedule - I", url: "https://takeuforward.org/data-structure/course-schedule-i-and-ii-pre-requisite-tasks-topological-sort-g-24/", lcUrl: "https://leetcode.com/problems/course-schedule/" },
      { name: "Course Schedule - II", url: "https://takeuforward.org/data-structure/course-schedule-i-and-ii-pre-requisite-tasks-topological-sort-g-24/", lcUrl: "https://leetcode.com/problems/course-schedule-ii/" },
      { name: "Find eventual safe states", url: "https://takeuforward.org/data-structure/find-eventual-safe-states-bfs-topological-sort-g-25/", lcUrl: "https://leetcode.com/problems/find-eventual-safe-states/" },
      { name: "Alien dictionary", url: "https://takeuforward.org/data-structure/alien-dictionary-topological-sort-g-26/", gfgUrl: "https://www.geeksforgeeks.org/problems/alien-dictionary/1" },
    ],
  },
  {
    topic: "Graphs [Concepts & Problems] - Shortest Path Algorithms and Problems",
    icon: "🕸️",
    questions: [
      { name: "Shortest Path in UG with unit weights", url: "https://takeuforward.org/data-structure/shortest-path-in-undirected-graph-with-unit-distance-g-28/" },
      { name: "Shortest Path in DAG", url: "https://takeuforward.org/data-structure/shortest-path-in-directed-acyclic-graph-topological-sort-g-27/" },
      { name: "Djisktra's Algorithm", url: "https://takeuforward.org/data-structure/dijkstras-algorithm-using-set-g-33/" },
      { name: "Why priority Queue is used in Djisktra's Algorithm", url: "https://takeuforward.org/data-structure/dijkstras-algorithm-using-priority-queue-g-32/" },
      { name: "Shortest path in a binary maze", url: "https://takeuforward.org/data-structure/g-36-shortest-distance-in-a-binary-maze/", lcUrl: "https://leetcode.com/problems/shortest-path-in-binary-matrix/" },
      { name: "Path with minimum effort", url: "https://takeuforward.org/data-structure/g-37-path-with-minimum-effort/", lcUrl: "https://leetcode.com/problems/path-with-minimum-effort/" },
      { name: "Cheapest flights within k stops", url: "https://takeuforward.org/data-structure/g-38-cheapest-flights-within-k-stops/", lcUrl: "https://leetcode.com/problems/cheapest-flights-within-k-stops/" },
      { name: "Network Delay time", url: "", lcUrl: "https://leetcode.com/problems/network-delay-time/" },
      { name: "Number of ways to arrive at destination", url: "https://takeuforward.org/data-structure/g-40-number-of-ways-to-arrive-at-destination/", lcUrl: "https://leetcode.com/problems/number-of-ways-to-arrive-at-destination/" },
      { name: "Minimum steps to reach end from start by performing multiplication and mod operations with array elements", url: "https://takeuforward.org/graph/g-39-minimum-multiplications-to-reach-end/" },
      { name: "Bellman Ford Algorithm", url: "https://takeuforward.org/data-structure/bellman-ford-algorithm-g-41/", gfgUrl: "https://www.geeksforgeeks.org/problems/distance-from-the-source-bellman-ford-algorithm/1" },
      { name: "Floyd Warshal Algorithm", url: "https://takeuforward.org/data-structure/floyd-warshall-algorithm-g-42/", gfgUrl: "https://www.geeksforgeeks.org/problems/implementing-floyd-warshall2042/1" },
      { name: "Find the city with the smallest number of neighbors in a threshold distance", url: "https://takeuforward.org/data-structure/find-the-city-with-the-smallest-number-of-neighbours-at-a-threshold-distance-g-43/", lcUrl: "https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/" },
    ],
  },
  {
    topic: "Graphs [Concepts & Problems] - MinimumSpanningTree/Disjoint Set and Problems",
    icon: "🕸️",
    questions: [
      { name: "Minimum Spanning Tree", url: "https://takeuforward.org/data-structure/minimum-spanning-tree-theory-g-44/" },
      { name: "Prim's Algorithm", url: "https://takeuforward.org/data-structure/prims-algorithm-minimum-spanning-tree-c-and-java-g-45/", gfgUrl: "https://www.geeksforgeeks.org/problems/minimum-spanning-tree/1" },
      { name: "Disjoint Set [Union by Rank]", url: "https://takeuforward.org/data-structure/disjoint-set-union-by-rank-union-by-size-path-compression-g-46/" },
      { name: "Disjoint Set [Union by Size]", url: "https://takeuforward.org/data-structure/disjoint-set-union-by-rank-union-by-size-path-compression-g-46/" },
      { name: "Kruskal's Algorithm", url: "https://takeuforward.org/data-structure/kruskals-algorithm-minimum-spanning-tree-g-47/", gfgUrl: "https://www.geeksforgeeks.org/problems/minimum-spanning-tree/1" },
      { name: "Number of operations to make network connected", url: "https://takeuforward.org/data-structure/number-of-operations-to-make-network-connected-dsu-g-49/", lcUrl: "https://leetcode.com/problems/number-of-operations-to-make-network-connected/" },
      { name: "Most stones removed with same rows or columns", url: "https://takeuforward.org/data-structure/most-stones-removed-with-same-row-or-column-dsu-g-53/", lcUrl: "https://leetcode.com/problems/most-stones-removed-with-same-row-or-column/" },
      { name: "Accounts merge", url: "https://takeuforward.org/data-structure/accounts-merge-dsu-g-50/", lcUrl: "https://leetcode.com/problems/accounts-merge/" },
      { name: "Number of island II", url: "https://takeuforward.org/graph/number-of-islands-ii-online-queries-dsu-g-51/" },
      { name: "Making a Large Island", url: "https://takeuforward.org/data-structure/making-a-large-island-dsu-g-52/", lcUrl: "https://leetcode.com/problems/making-a-large-island/" },
      { name: "Swim in rising water", url: "", lcUrl: "https://leetcode.com/problems/swim-in-rising-water/" },
    ],
  },
  {
    topic: "Graphs [Concepts & Problems] - Other Algorithms",
    icon: "🕸️",
    questions: [
      { name: "Bridges in Graph", url: "https://takeuforward.org/graph/bridges-in-graph-using-tarjans-algorithm-of-time-in-and-low-time-g-55/", lcUrl: "https://leetcode.com/problems/critical-connections-in-a-network/" },
      { name: "Articulation Point", url: "https://takeuforward.org/data-structure/articulation-point-in-graph-g-56/" },
      { name: "Kosaraju's Algorithm", url: "https://takeuforward.org/graph/strongly-connected-components-kosarajus-algorithm-g-54/" },
    ],
  },
  {
    topic: "Dynamic Programming [Patterns and Problems] - Introduction to DP",
    icon: "💡",
    questions: [
      { name: "Dynamic Programming Introduction", url: "https://takeuforward.org/data-structure/dynamic-programming-introduction/" },
    ],
  },
  {
    topic: "Dynamic Programming [Patterns and Problems] - 1D DP",
    icon: "💡",
    questions: [
      { name: "Climbing Stars", url: "https://takeuforward.org/data-structure/dynamic-programming-climbing-stairs/", lcUrl: "https://leetcode.com/problems/climbing-stairs/" },
      { name: "Frog Jump(DP-3)", url: "https://takeuforward.org/data-structure/dynamic-programming-frog-jump-dp-3/" },
      { name: "Frog Jump with k distances(DP-4)", url: "https://takeuforward.org/data-structure/dynamic-programming-frog-jump-with-k-distances-dp-4/" },
      { name: "Maximum sum of non-adjacent elements (DP 5)", url: "https://takeuforward.org/data-structure/maximum-sum-of-non-adjacent-elements-dp-5/" },
      { name: "House Robber (DP 6)", url: "https://takeuforward.org/data-structure/dynamic-programming-house-robber-dp-6/", lcUrl: "https://leetcode.com/problems/house-robber/" },
    ],
  },
  {
    topic: "Dynamic Programming [Patterns and Problems] - 2D/3D DP and DP on Grids",
    icon: "💡",
    questions: [
      { name: "Ninja's Training (DP 7)", url: "https://takeuforward.org/data-structure/dynamic-programming-ninjas-training-dp-7/" },
      { name: "Grid Unique Paths : DP on Grids (DP8)", url: "https://takeuforward.org/data-structure/grid-unique-paths-dp-on-grids-dp8/", lcUrl: "https://leetcode.com/problems/unique-paths/" },
      { name: "Grid Unique Paths 2 (DP 9)", url: "https://takeuforward.org/data-structure/grid-unique-paths-2-dp-9/", lcUrl: "https://leetcode.com/problems/unique-paths-ii/" },
      { name: "Minimum path sum in Grid (DP 10)", url: "https://takeuforward.org/data-structure/minimum-path-sum-in-a-grid-dp-10/", lcUrl: "https://leetcode.com/problems/minimum-path-sum/" },
      { name: "Minimum path sum in Triangular Grid (DP 11)", url: "https://takeuforward.org/data-structure/minimum-path-sum-in-triangular-grid-dp-11/", lcUrl: "https://leetcode.com/problems/triangle/" },
      { name: "Minimum/Maximum Falling Path Sum (DP-12)", url: "https://takeuforward.org/data-structure/minimum-maximum-falling-path-sum-dp-12/", lcUrl: "https://leetcode.com/problems/minimum-falling-path-sum/" },
      { name: "3-d DP : Ninja and his friends (DP-13)", url: "https://takeuforward.org/data-structure/3-d-dp-ninja-and-his-friends-dp-13/" },
    ],
  },
  {
    topic: "Dynamic Programming [Patterns and Problems] - DP on Subsequences",
    icon: "💡",
    questions: [
      { name: "Subset sum equal to target (DP- 14)", url: "https://takeuforward.org/data-structure/subset-sum-equal-to-target-dp-14/" },
      { name: "Partition Equal Subset Sum (DP- 15)", url: "https://takeuforward.org/data-structure/partition-equal-subset-sum-dp-15/", lcUrl: "https://leetcode.com/problems/partition-equal-subset-sum/" },
      { name: "Partition Set Into 2 Subsets With Min Absolute Sum Diff (DP- 16)", url: "https://takeuforward.org/data-structure/partition-set-into-2-subsets-with-min-absolute-sum-diff-dp-16/" },
      { name: "Count Subsets with Sum K (DP - 17)", url: "https://takeuforward.org/data-structure/count-subsets-with-sum-k-dp-17/" },
      { name: "Count Partitions with Given Difference (DP - 18)", url: "https://takeuforward.org/data-structure/count-partitions-with-given-difference-dp-18/" },
      { name: "Assign Cookies", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2" },
      { name: "Minimum Coins (DP - 20)", url: "https://takeuforward.org/data-structure/minimum-coins-dp-20/", lcUrl: "https://leetcode.com/problems/coin-change/" },
      { name: "Target Sum (DP - 21)", url: "https://takeuforward.org/data-structure/target-sum-dp-21/", lcUrl: "https://leetcode.com/problems/target-sum/" },
      { name: "Coin Change 2 (DP - 22)", url: "https://takeuforward.org/data-structure/coin-change-2-dp-22/", lcUrl: "https://leetcode.com/problems/coin-change-2/" },
      { name: "Unbounded Knapsack (DP - 23)", url: "https://takeuforward.org/data-structure/unbounded-knapsack-dp-23/" },
      { name: "Rod Cutting Problem | (DP - 24)", url: "https://takeuforward.org/data-structure/rod-cutting-problem-dp-24/", gfgUrl: "https://www.geeksforgeeks.org/problems/rod-cutting0840/1" },
    ],
  },
  {
    topic: "Dynamic Programming [Patterns and Problems] - DP on Strings",
    icon: "💡",
    questions: [
      { name: "Longest Common Subsequence | (DP - 25)", url: "https://takeuforward.org/data-structure/longest-common-subsequence-dp-25/", lcUrl: "https://leetcode.com/problems/longest-common-subsequence/" },
      { name: "Print Longest Common Subsequence | (DP - 26)", url: "https://takeuforward.org/data-structure/print-longest-common-subsequence-dp-26/" },
      { name: "Longest Common Substring | (DP - 27)", url: "https://takeuforward.org/data-structure/longest-common-substring-dp-27/" },
      { name: "Longest Palindromic Subsequence | (DP-28)", url: "https://takeuforward.org/data-structure/longest-palindromic-subsequence-dp-28/", lcUrl: "https://leetcode.com/problems/longest-palindromic-subsequence/" },
      { name: "Minimum insertions to make string palindrome | DP-29", url: "https://takeuforward.org/data-structure/minimum-insertions-to-make-string-palindrome-dp-29/", lcUrl: "https://leetcode.com/problems/minimum-insertion-steps-to-make-a-string-palindrome/" },
      { name: "Minimum Insertions/Deletions to Convert String | (DP- 30)", url: "https://takeuforward.org/data-structure/minimum-insertions-deletions-to-convert-string-dp-30/" },
      { name: "Shortest Common Supersequence | (DP - 31)", url: "https://takeuforward.org/data-structure/shortest-common-supersequence-dp-31/", lcUrl: "https://leetcode.com/problems/shortest-common-supersequence/" },
      { name: "Distinct Subsequences| (DP-32)", url: "https://takeuforward.org/data-structure/distinct-subsequences-dp-32/", lcUrl: "https://leetcode.com/problems/distinct-subsequences/" },
      { name: "Edit Distance | (DP-33)", url: "https://takeuforward.org/data-structure/edit-distance-dp-33/", lcUrl: "https://leetcode.com/problems/edit-distance/" },
      { name: "Wildcard Matching | (DP-34)", url: "https://takeuforward.org/data-structure/wildcard-matching-dp-34/", lcUrl: "https://leetcode.com/problems/wildcard-matching/" },
    ],
  },
  {
    topic: "Dynamic Programming [Patterns and Problems] - DP on Stocks",
    icon: "💡",
    questions: [
      { name: "Best Time to Buy and Sell Stock |(DP-35)", url: "https://takeuforward.org/data-structure/stock-buy-and-sell-dp-35/", lcUrl: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/" },
      { name: "Buy and Sell Stock - II|(DP-36)", url: "https://takeuforward.org/data-structure/buy-and-sell-stock-ii-dp-36/", lcUrl: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/" },
      { name: "Buy and Sell Stocks III|(DP-37)", url: "https://takeuforward.org/data-structure/buy-and-sell-stock-iii-dp-37/", lcUrl: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/" },
      { name: "Buy and Stock Sell IV |(DP-38)", url: "https://takeuforward.org/data-structure/buy-and-sell-stock-iv-dp-38/", lcUrl: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/" },
      { name: "Buy and Sell Stocks With Cooldown|(DP-39)", url: "https://takeuforward.org/data-structure/buy-and-sell-stocks-with-cooldown-dp-39/", lcUrl: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/" },
      { name: "Buy and Sell Stocks With Transaction Fee|(DP-40)", url: "https://takeuforward.org/data-structure/buy-and-sell-stocks-with-transaction-fees-dp-40/", lcUrl: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-transaction-fee/" },
    ],
  },
  {
    topic: "Dynamic Programming [Patterns and Problems] - DP on LIS",
    icon: "💡",
    questions: [
      { name: "Longest Increasing Subsequence |(DP-41)", url: "https://takeuforward.org/data-structure/longest-increasing-subsequence-dp-41/", lcUrl: "https://leetcode.com/problems/longest-increasing-subsequence/" },
      { name: "Printing Longest Increasing Subsequence|(DP-42)", url: "https://takeuforward.org/data-structure/printing-longest-increasing-subsequence-dp-42/" },
      { name: "Longest Increasing Subsequence |(DP-43)", url: "https://takeuforward.org/data-structure/longest-increasing-subsequence-binary-search-dp-43/", lcUrl: "https://leetcode.com/problems/longest-increasing-subsequence/" },
      { name: "Largest Divisible Subset|(DP-44)", url: "https://takeuforward.org/data-structure/longest-divisible-subset-dp-44/", lcUrl: "https://leetcode.com/problems/largest-divisible-subset/" },
      { name: "Longest String Chain|(DP-45)", url: "https://takeuforward.org/data-structure/longest-string-chain-dp-45/", lcUrl: "https://leetcode.com/problems/longest-string-chain/" },
      { name: "Longest Bitonic Subsequence |(DP-46)", url: "https://takeuforward.org/data-structure/longest-bitonic-subsequence-dp-46/" },
      { name: "Number of Longest Increasing Subsequences|(DP-47)", url: "https://takeuforward.org/data-structure/number-of-longest-increasing-subsequences-dp-47/", lcUrl: "https://leetcode.com/problems/number-of-longest-increasing-subsequences/" },
    ],
  },
  {
    topic: "Dynamic Programming [Patterns and Problems] - MCM DP | Partition DP",
    icon: "💡",
    questions: [
      { name: "Matrix Chain Multiplication|(DP-48)", url: "https://takeuforward.org/dynamic-programming/matrix-chain-multiplication-dp-48/", gfgUrl: "https://www.geeksforgeeks.org/problems/matrix-chain-multiplication0303/1" },
      { name: "Matrix Chain Multiplication | Bottom-Up|(DP-49)", url: "https://takeuforward.org/data-structure/matrix-chain-multiplication-tabulation-method-dp-49/" },
      { name: "Minimum Cost to Cut the Stick|(DP-50)", url: "https://takeuforward.org/data-structure/minimum-cost-to-cut-the-stick-dp-50/", lcUrl: "https://leetcode.com/problems/minimum-cost-to-cut-a-stick/" },
      { name: "Burst Balloons|(DP-51)", url: "https://takeuforward.org/data-structure/burst-balloons-partition-dp-dp-51/", lcUrl: "https://leetcode.com/problems/burst-balloons/" },
      { name: "Evaluate Boolean Expression to True|(DP-52)", url: "https://takeuforward.org/data-structure/evaluate-boolean-expression-to-true-partition-dp-dp-52/" },
      { name: "Palindrome Partitioning - II|(DP-53)", url: "https://takeuforward.org/data-structure/palindrome-partitioning-ii-front-partition-dp-53/", lcUrl: "https://leetcode.com/problems/palindrome-partitioning-ii/" },
      { name: "Partition Array for Maximum Sum|(DP-54)", url: "https://takeuforward.org/data-structure/partition-array-for-maximum-sum-front-partition-dp-54/", lcUrl: "https://leetcode.com/problems/partition-array-for-maximum-sum/" },
    ],
  },
  {
    topic: "Dynamic Programming [Patterns and Problems] - DP on Squares",
    icon: "💡",
    questions: [
      { name: "Maximum Rectangle Area with all 1's|(DP-55)", url: "https://takeuforward.org/data-structure/maximum-rectangle-area-with-all-1s-dp-on-rectangles-dp-55/", lcUrl: "https://leetcode.com/problems/maximal-rectangle/" },
      { name: "Count Square Submatrices with All Ones|(DP-56)", url: "https://takeuforward.org/data-structure/count-square-submatrices-with-all-1s-dp-on-rectangles-dp-56/", lcUrl: "https://leetcode.com/problems/count-square-submatrices-with-all-ones/" },
    ],
  },
  {
    topic: "Tries - Theory",
    icon: "🔤",
    questions: [
      { name: "Implement TRIE | INSERT | SEARCH | STARTSWITH", url: "https://takeuforward.org/data-structure/implement-trie-1/", lcUrl: "https://leetcode.com/problems/implement-trie-prefix-tree/" },
    ],
  },
  {
    topic: "Tries - Problems",
    icon: "🔤",
    questions: [
      { name: "Implement Trie - 2 (Prefix Tree)", url: "https://takeuforward.org/data-structure/implement-trie-ii/" },
      { name: "Longest String with All Prefixes", url: "" },
      { name: "Number of Distinct Substrings in a String", url: "https://takeuforward.org/data-structure/number-of-distinct-substrings-in-a-string-using-trie/" },
      { name: "Bit PreRequisites for TRIE Problems", url: "" },
      { name: "Maximum XOR of two numbers in an array", url: "https://takeuforward.org/data-structure/maximum-xor-of-two-numbers-in-an-array/", lcUrl: "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/" },
      { name: "Maximum XOR With an Element From Array", url: "https://takeuforward.org/trie/maximum-xor-queries-trie/", lcUrl: "https://leetcode.com/problems/maximum-xor-with-an-element-from-array/" },
    ],
  },
  {
    topic: "Strings - Hard Problems",
    icon: "📝",
    questions: [
      { name: "Minimum number of bracket reversals needed to make an expression balanced", url: "" },
      { name: "Count and say", url: "", lcUrl: "https://leetcode.com/problems/count-and-say/" },
      { name: "Hashing In Strings | Theory", url: "" },
      { name: "Rabin Karp", url: "" },
      { name: "Z-Function", url: "" },
      { name: "KMP algo / LPS(pi) array", url: "" },
      { name: "Shortest Palindrome", url: "", lcUrl: "https://leetcode.com/problems/shortest-palindrome/" },
      { name: "Longest happy prefix", url: "", lcUrl: "https://leetcode.com/problems/longest-happy-prefix/" },
      { name: "Count palindromic subsequence in given string", url: "" },
    ],
  },
];