const STRIVER_SDE_DATA = [
  {
    topic: "Arrays I",
    icon: "📊",
    questions: [
      { name: "Set Matrix Zeros", url: "https://leetcode.com/problems/set-matrix-zeroes/" },
      { name: "Pascal's Triangle", url: "https://leetcode.com/problems/pascals-triangle/" },
      { name: "Next Permutation", url: "https://leetcode.com/problems/next-permutation/" },
      { name: "Kadane's Algorithm", url: "https://leetcode.com/problems/maximum-subarray/" },
      { name: "Sort an array of 0's, 1's and 2's", url: "https://leetcode.com/problems/sort-colors/" },
      { name: "Stock Buy and Sell", url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/" },
    ],
  },
  {
    topic: "Arrays II",
    icon: "📊",
    questions: [
      { name: "Rotate Matrix", url: "https://leetcode.com/problems/rotate-image/" },
      { name: "Merge Overlapping Subintervals", url: "https://leetcode.com/problems/merge-intervals/" },
      { name: "Merge two sorted arrays without extra space", url: "https://leetcode.com/problems/merge-sorted-array/" },
      { name: "Find the duplicate in an array of N+1 integers", url: "https://leetcode.com/problems/find-the-duplicate-number/" },
      { name: "Repeat and Missing Number", url: "https://takeuforward.org/data-structure/find-the-repeating-and-missing-numbers/" },
      { name: "Inversion of Array (Pre-req: Merge Sort)", url: "https://takeuforward.org/data-structure/count-inversions-in-an-array/" },
    ],
  },
  {
    topic: "Arrays III",
    icon: "📊",
    questions: [
      { name: "Search in a 2 D matrix", url: "https://leetcode.com/problems/search-a-2d-matrix/" },
      { name: "Pow(x, n)", url: "https://leetcode.com/problems/powx-n/" },
      { name: "Majority Element (>n/2 times)", url: "https://leetcode.com/problems/majority-element/" },
      { name: "Majority Element (n/3 times)", url: "https://leetcode.com/problems/majority-element-ii/" },
      { name: "Grid Unique Paths", url: "https://leetcode.com/problems/unique-paths/" },
      { name: "Reverse Pairs (Leetcode)", url: "https://leetcode.com/problems/reverse-pairs/" },
    ],
  },
  {
    topic: "Arrays IV",
    icon: "📊",
    questions: [
      { name: "2Sum Problem", url: "https://leetcode.com/problems/two-sum/" },
      { name: "4-Sum Problem", url: "https://leetcode.com/problems/4sum/" },
      { name: "Longest Consecutive Sequence", url: "https://leetcode.com/problems/longest-consecutive-sequence/" },
      { name: "Largest Subarray with K sum", url: "https://takeuforward.org/data-structure/length-of-the-longest-subarray-with-zero-sum/" },
      { name: "Count number of subarrays with given xor K", url: "https://takeuforward.org/data-structure/count-the-number-of-subarrays-with-given-xor-k/" },
      { name: "Longest Substring without repeat", url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/" },
    ],
  },
  {
    topic: "Linked List I",
    icon: "🔗",
    questions: [
      { name: "Reverse a LinkedList", url: "https://leetcode.com/problems/reverse-linked-list/" },
      { name: "Find the middle of LinkedList", url: "https://leetcode.com/problems/middle-of-the-linked-list/" },
      { name: "Merge two sorted Linked List (use method used in mergeSort)", url: "https://leetcode.com/problems/merge-two-sorted-lists/" },
      { name: "Remove N-th node from back of LinkedList", url: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/" },
      { name: "Add two numbers as LinkedList", url: "https://leetcode.com/problems/add-two-numbers/" },
      { name: "Delete a given Node when a node is given.(0(1) solution)", url: "https://leetcode.com/problems/delete-node-in-a-linked-list/" },
    ],
  },
  {
    topic: "Linked List II",
    icon: "🔗",
    questions: [
      { name: "Find intersection point of Y LinkedList", url: "https://leetcode.com/problems/intersection-of-two-linked-lists/" },
      { name: "Detect a cycle in Linked List", url: "https://leetcode.com/problems/linked-list-cycle/" },
      { name: "Reverse a LinkedList in groups of size k.", url: "https://leetcode.com/problems/reverse-nodes-in-k-group/" },
      { name: "Check if a LinkedList is palindrome or not.", url: "https://leetcode.com/problems/palindrome-linked-list/" },
      { name: "Find the starting point of the Loop of LinkedList", url: "https://leetcode.com/problems/linked-list-cycle-ii/" },
      { name: "Flattening of a LinkedList", url: "https://takeuforward.org/data-structure/flattening-a-linked-list/" },
    ],
  },
  {
    topic: "Linked List & Arrays",
    icon: "🔗",
    questions: [
      { name: "Rotate a LinkedList", url: "https://leetcode.com/problems/rotate-list/description/" },
      { name: "Clone a Linked List with random and next pointer", url: "https://leetcode.com/problems/copy-list-with-random-pointer/" },
      { name: "3 sum", url: "https://leetcode.com/problems/3sum/" },
      { name: "Trapping Rainwater", url: "https://leetcode.com/problems/trapping-rain-water/" },
      { name: "Remove Duplicate from Sorted array", url: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/" },
      { name: "Max consecutive ones", url: "https://leetcode.com/problems/max-consecutive-ones/" },
    ],
  },
  {
    topic: "Greedy",
    icon: "💰",
    questions: [
      { name: "N meetings in one room", url: "https://takeuforward.org/data-structure/n-meetings-in-one-room/" },
      { name: "Minimum number of platforms required for a railway", url: "https://takeuforward.org/data-structure/minimum-number-of-platforms-required-for-a-railway/" },
      { name: "Job sequencing Problem", url: "https://takeuforward.org/data-structure/job-sequencing-problem/" },
      { name: "Fractional Knapsack Problem", url: "https://takeuforward.org/data-structure/fractional-knapsack-problem-greedy-approach/" },
      { name: "Greedy algorithm to find minimum number of coins", url: "https://takeuforward.org/data-structure/find-minimum-number-of-coins/" },
      { name: "Assign Cookies", url: "https://leetcode.com/problems/assign-cookies/" },
    ],
  },
  {
    topic: "Recursion",
    icon: "🔄",
    questions: [
      { name: "Subset Sums", url: "https://takeuforward.org/data-structure/subset-sum-sum-of-all-subsets/" },
      { name: "Subset-II", url: "https://leetcode.com/problems/subsets-ii/" },
      { name: "Combination sum-1", url: "https://leetcode.com/problems/combination-sum/" },
      { name: "Combination sum-2", url: "https://leetcode.com/problems/combination-sum-ii/" },
      { name: "Palindrome Partitioning", url: "https://leetcode.com/problems/palindrome-partitioning/" },
      { name: "K-th permutation Sequence", url: "https://leetcode.com/problems/permutation-sequence/" },
    ],
  },
  {
    topic: "Backtracking",
    icon: "🔄",
    questions: [
      { name: "Print all permutations of a string/array", url: "https://leetcode.com/problems/permutations/" },
      { name: "N queens Problem", url: "https://leetcode.com/problems/n-queens/" },
      { name: "Sudoko Solver", url: "https://leetcode.com/problems/sudoku-solver/" },
      { name: "M Coloring Problem", url: "https://takeuforward.org/data-structure/m-coloring-problem/" },
      { name: "Rat in a Maze", url: "https://takeuforward.org/data-structure/rat-in-a-maze/" },
      { name: "Word Break (print all ways)", url: "" },
    ],
  },
  {
    topic: "Binary Search",
    icon: "🔍",
    questions: [
      { name: "The N-th root of an integer", url: "https://takeuforward.org/data-structure/nth-root-of-a-number-using-binary-search/" },
      { name: "Matrix Median", url: "https://takeuforward.org/data-structure/median-of-row-wise-sorted-matrix/" },
      { name: "Find the element that appears once in a sorted array, and the rest element appears twice (Binary search)", url: "https://leetcode.com/problems/single-element-in-a-sorted-array/" },
      { name: "Search element in a sorted and rotated array/ find pivot where it is rotated", url: "https://leetcode.com/problems/search-in-rotated-sorted-array/" },
      { name: "Median of 2 sorted arrays", url: "https://leetcode.com/problems/median-of-two-sorted-arrays/" },
      { name: "K-th element of two sorted arrays", url: "https://takeuforward.org/data-structure/k-th-element-of-two-sorted-arrays/" },
      { name: "Allocate Minimum Number of Pages", url: "https://takeuforward.org/data-structure/allocate-minimum-number-of-pages/" },
      { name: "Aggressive Cows", url: "https://takeuforward.org/data-structure/aggressive-cows-detailed-solution/" },
    ],
  },
  {
    topic: "Heaps",
    icon: "⚙️",
    questions: [
      { name: "Max heap, Min Heap Implementation (Only for interviews)", url: "" },
      { name: "Kth Largest Element", url: "https://leetcode.com/problems/kth-largest-element-in-an-array/" },
      { name: "Maximum Sum Combination", url: "" },
      { name: "Find Median from Data Stream", url: "https://leetcode.com/problems/find-median-from-data-stream/" },
      { name: "Merge K sorted arrays", url: "" },
      { name: "K most frequent elements", url: "https://leetcode.com/problems/top-k-frequent-elements/" },
    ],
  },
  {
    topic: "Stack & Queue I",
    icon: "📚",
    questions: [
      { name: "Implement Stack using Arrays", url: "https://takeuforward.org/data-structure/implement-stack-using-array/" },
      { name: "Implement Queue using Arrays", url: "https://takeuforward.org/data-structure/implement-queue-using-array/" },
      { name: "Implement Stack using Queue (using single queue)", url: "https://leetcode.com/problems/implement-stack-using-queues/" },
      { name: "Implement Queue using Stack (0(1) amortized method)", url: "https://leetcode.com/problems/implement-queue-using-stacks/" },
      { name: "Check for balanced parentheses", url: "https://leetcode.com/problems/valid-parentheses/" },
      { name: "Next Greater Element", url: "https://leetcode.com/problems/next-greater-element-i/" },
      { name: "Sort a Stack", url: "" },
    ],
  },
  {
    topic: "Stack & Queue II",
    icon: "📚",
    questions: [
      { name: "Next Smaller Element", url: "" },
      { name: "LRU cache (IMPORTANT)", url: "https://leetcode.com/problems/lru-cache/" },
      { name: "LFU cache", url: "https://leetcode.com/problems/lfu-cache/" },
      { name: "Largest rectangle in a histogram", url: "https://leetcode.com/problems/largest-rectangle-in-histogram/" },
      { name: "Sliding Window maximum", url: "https://leetcode.com/problems/sliding-window-maximum/" },
      { name: "Implement Min Stack", url: "https://leetcode.com/problems/min-stack/" },
      { name: "Rotten Orange (Using BFS)", url: "https://leetcode.com/problems/rotting-oranges/" },
      { name: "Stock span problem", url: "https://leetcode.com/problems/online-stock-span/" },
      { name: "Find the maximum of minimums of every window size", url: "" },
      { name: "The Celebrity Problem", url: "https://takeuforward.org/interviews/strivers-sde-sheet-top-coding-interview-problems/" },
    ],
  },
  {
    topic: "String I",
    icon: "📝",
    questions: [
      { name: "Reverse Words in a String", url: "https://leetcode.com/problems/reverse-words-in-a-string/" },
      { name: "Longest Palindrome in a string", url: "https://leetcode.com/problems/longest-palindromic-substring/" },
      { name: "Roman Number to Integer and vice versa", url: "https://leetcode.com/problems/roman-to-integer/" },
      { name: "Implement ATOI/STRSTR", url: "https://leetcode.com/problems/string-to-integer-atoi/" },
      { name: "Longest Common Prefix", url: "https://leetcode.com/problems/longest-common-prefix/" },
      { name: "Rabin Karp", url: "https://leetcode.com/problems/repeated-string-match/discuss/416144/Rabin-Karp-algorithm-C%2B%2B-implementation" },
    ],
  },
  {
    topic: "String II",
    icon: "📝",
    questions: [
      { name: "Z-Function", url: "https://leetcode.com/problems/implement-strstr/" },
      { name: "KMP algo / LPS(pi) array", url: "https://leetcode.com/problems/implement-strstr/" },
      { name: "Minimum characters needed to be inserted in the beginning to make it palindromic", url: "" },
      { name: "Check for Anagrams", url: "https://leetcode.com/problems/valid-anagram/" },
      { name: "Count and say", url: "https://leetcode.com/problems/count-and-say/" },
      { name: "Compare version numbers", url: "https://leetcode.com/problems/compare-version-numbers/" },
    ],
  },
  {
    topic: "Binary Tree I",
    icon: "🌳",
    questions: [
      { name: "Inorder Traversal", url: "https://leetcode.com/problems/binary-tree-inorder-traversal/" },
      { name: "Preorder Traversal", url: "https://leetcode.com/problems/binary-tree-preorder-traversal/" },
      { name: "Postorder Traversal", url: "https://leetcode.com/problems/binary-tree-postorder-traversal/" },
      { name: "Morris Inorder Traversal", url: "https://leetcode.com/problems/binary-tree-inorder-traversal/" },
      { name: "Morris Preorder Traversal", url: "https://takeuforward.org/data-structure/morris-preorder-traversal-of-a-binary-tree/" },
      { name: "LeftView Of Binary Tree", url: "https://takeuforward.org/data-structure/right-left-view-of-binary-tree/" },
      { name: "Bottom View of Binary Tree", url: "https://takeuforward.org/data-structure/bottom-view-of-a-binary-tree/" },
      { name: "Top View of Binary Tree", url: "https://takeuforward.org/data-structure/top-view-of-a-binary-tree/" },
      { name: "Preorder inorder postorder in a single traversal", url: "https://takeuforward.org/data-structure/preorder-inorder-postorder-traversals-in-one-traversal/" },
      { name: "Vertical order traversal", url: "https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/" },
      { name: "Root to Node Path in Binary Tree", url: "https://takeuforward.org/data-structure/print-root-to-node-path-in-a-binary-tree/" },
      { name: "Max width of a Binary Tree", url: "https://leetcode.com/problems/maximum-width-of-binary-tree/" },
    ],
  },
  {
    topic: "Binary Tree II",
    icon: "🌳",
    questions: [
      { name: "Level order Traversal / Level order traversal in spiral form", url: "https://leetcode.com/problems/binary-tree-level-order-traversal/" },
      { name: "Height of a Binary Tree", url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/" },
      { name: "Diameter of Binary Tree", url: "https://leetcode.com/problems/diameter-of-binary-tree/" },
      { name: "Check if the Binary tree is height-balanced or not", url: "https://leetcode.com/problems/balanced-binary-tree/" },
      { name: "LCA in Binary Tree", url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/" },
      { name: "Check if two trees are identical or not", url: "https://leetcode.com/problems/same-tree/" },
      { name: "Zig Zag Traversal of Binary Tree", url: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/" },
      { name: "Boundary Traversal of Binary Tree", url: "https://leetcode.com/problems/boundary-of-binary-tree/" },
    ],
  },
  {
    topic: "Binary Tree III",
    icon: "🌳",
    questions: [
      { name: "Maximum path sum", url: "https://leetcode.com/problems/binary-tree-maximum-path-sum/" },
      { name: "Construct Binary Tree from inorder and preorder", url: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/" },
      { name: "Construct Binary Tree from Inorder and Postorder", url: "https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/" },
      { name: "Symmetric Binary Tree", url: "https://leetcode.com/problems/symmetric-tree/" },
      { name: "Flatten Binary Tree to LinkedList", url: "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/" },
      { name: "Check if Binary Tree is the mirror of itself or not", url: "" },
      { name: "Check for Children Sum Property", url: "https://takeuforward.org/data-structure/check-for-children-sum-property-in-a-binary-tree/" },
    ],
  },
  {
    topic: "BST I",
    icon: "🌲",
    questions: [
      { name: "Populate Next Right pointers of Tree", url: "https://leetcode.com/problems/populating-next-right-pointers-in-each-node/" },
      { name: "Search given Key in BST", url: "https://leetcode.com/problems/search-in-a-binary-search-tree/" },
      { name: "Construct BST from given keys", url: "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/" },
      { name: "Construct a BST from a preorder traversal", url: "https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/" },
      { name: "Check is a BT is BST or not", url: "https://leetcode.com/problems/validate-binary-search-tree/" },
      { name: "Find LCA of two nodes in BST", url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/" },
      { name: "Find the inorder predecessor/successor of a given Key in BST.", url: "" },
    ],
  },
  {
    topic: "BST II",
    icon: "🌲",
    questions: [
      { name: "Floor in a BST", url: "" },
      { name: "Ceil in a BST", url: "" },
      { name: "Find K-th smallest element in BST", url: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/" },
      { name: "Find K-th largest element in BST", url: "https://takeuforward.org/data-structure/kth-largest-smallest-element-in-binary-search-tree/" },
      { name: "Find a pair with a given sum in BST", url: "https://leetcode.com/problems/two-sum-iv-input-is-a-bst/" },
      { name: "BST iterator", url: "https://leetcode.com/problems/binary-search-tree-iterator/" },
      { name: "Size of the largest BST in a Binary Tree", url: "https://leetcode.com/problems/maximum-sum-bst-in-binary-tree/" },
      { name: "Serialize and deserialize Binary Tree", url: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/" },
    ],
  },
  {
    topic: "Mixed Problems",
    icon: "🎲",
    questions: [
      { name: "Binary Tree to Double Linked List", url: "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/" },
      { name: "Find median in a stream of running integers.", url: "https://leetcode.com/problems/find-median-from-data-stream/" },
      { name: "K-th largest element in a stream.", url: "https://leetcode.com/problems/kth-largest-element-in-a-stream/" },
      { name: "Distinct numbers in Window.", url: "" },
      { name: "K-th largest element in an unsorted array.", url: "https://leetcode.com/problems/kth-largest-element-in-an-array/" },
      { name: "Flood-fill Algorithm", url: "https://leetcode.com/problems/flood-fill/" },
    ],
  },
  {
    topic: "Graph I",
    icon: "🕸️",
    questions: [
      { name: "Clone a graph (Not that easy as it looks)", url: "https://leetcode.com/problems/clone-graph/" },
      { name: "DFS", url: "https://takeuforward.org/data-structure/depth-first-search-dfs/" },
      { name: "BFS", url: "https://takeuforward.org/graph/breadth-first-search-bfs-level-order-traversal/" },
      { name: "Detect A cycle in Undirected Graph using BFS", url: "https://leetcode.com/problems/course-schedule/" },
      { name: "Detect A cycle in Undirected Graph using DFS", url: "https://leetcode.com/problems/course-schedule/" },
      { name: "Detect A cycle in a Directed Graph using DFS", url: "https://leetcode.com/problems/course-schedule/" },
      { name: "Detect A cycle in a Directed Graph using BFS", url: "https://leetcode.com/problems/course-schedule/" },
      { name: "Topological Sort BFS", url: "https://takeuforward.org/data-structure/topological-sort-bfs/" },
      { name: "Topological Sort DFS", url: "https://takeuforward.org/data-structure/topological-sort-using-dfs/" },
      { name: "Number of islands(Do in Grid and Graph Both)", url: "https://leetcode.com/problems/number-of-islands/" },
      { name: "Bipartite Check using BFS", url: "https://leetcode.com/problems/is-graph-bipartite/" },
      { name: "Bipartite Check using DFS", url: "https://leetcode.com/problems/is-graph-bipartite/" },
    ],
  },
  {
    topic: "Graph II",
    icon: "🕸️",
    questions: [
      { name: "Strongly Connected Component(using KosaRajuΓÇÖs algo)", url: "https://leetcode.com/problems/maximum-number-of-non-overlapping-substrings/discuss/766485/kosaraju-algorithm-on" },
      { name: "DijkstraΓÇÖs Algorithm", url: "https://takeuforward.org/data-structure/g-35-print-shortest-path-dijkstras-algorithm/" },
      { name: "Bellman-Ford Algo", url: "https://takeuforward.org/data-structure/bellman-ford-algorithm-g-41/" },
      { name: "Floyd Warshall Algorithm", url: "https://takeuforward.org/data-structure/floyd-warshall-algorithm-g-42/" },
      { name: "MST using Prim's Algo", url: "https://takeuforward.org/data-structure/prims-algorithm-minimum-spanning-tree-c-and-java-g-45/" },
      { name: "MST using KruskalΓÇÖs Algo", url: "https://takeuforward.org/data-structure/kruskals-algorithm-minimum-spanning-tree-g-47/" },
    ],
  },
  {
    topic: "DP I",
    icon: "💡",
    questions: [
      { name: "Max Product Subarray", url: "https://leetcode.com/problems/maximum-product-subarray/" },
      { name: "Longest Increasing Subsequence", url: "https://leetcode.com/problems/longest-increasing-subsequence/" },
      { name: "Longest Common Subsequence", url: "https://leetcode.com/problems/longest-common-subsequence/" },
      { name: "0-1 Knapsack", url: "https://takeuforward.org/data-structure/0-1-knapsack-dp-19/" },
      { name: "Edit Distance", url: "https://leetcode.com/problems/edit-distance/" },
      { name: "Maximum sum increasing subsequence", url: "" },
      { name: "Matrix Chain Multiplication", url: "https://takeuforward.org/dynamic-programming/matrix-chain-multiplication-dp-48/" },
    ],
  },
  {
    topic: "DP II",
    icon: "💡",
    questions: [
      { name: "Minimum sum path in the matrix, (count paths and similar type do, also backtrack to find the Minimum path)", url: "https://leetcode.com/problems/minimum-path-sum/" },
      { name: "Coin change", url: "https://leetcode.com/problems/coin-change/" },
      { name: "Subset Sum", url: "https://leetcode.com/problems/partition-equal-subset-sum/" },
      { name: "Rod Cutting", url: "https://leetcode.com/problems/minimum-cost-to-cut-a-stick/" },
      { name: "Egg Dropping", url: "" },
      { name: "Word Break", url: "https://leetcode.com/problems/word-break/" },
      { name: "Palindrome Partitioning (MCM Variation)", url: "" },
      { name: "Maximum profit in Job scheduling", url: "" },
    ],
  },
  {
    topic: "Trie",
    icon: "🔤",
    questions: [
      { name: "Implement Trie (Prefix Tree)", url: "https://leetcode.com/problems/implement-trie-prefix-tree/" },
      { name: "Implement Trie - 2 (Prefix Tree)", url: "https://takeuforward.org/data-structure/implement-trie-ii/" },
      { name: "Longest String with All Prefixes", url: "" },
      { name: "Number of Distinct Substrings in a String", url: "https://takeuforward.org/data-structure/number-of-distinct-substrings-in-a-string-using-trie/" },
      { name: "Power Set (this is very important)", url: "https://takeuforward.org/data-structure/power-set-print-all-the-possible-subsequences-of-the-string/" },
      { name: "Maximum XOR of two numbers in an array", url: "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/" },
      { name: "Maximum XOR With an Element From Array", url: "https://leetcode.com/problems/maximum-xor-with-an-element-from-array/" },
    ],
  },
];