const STRIVER_A2Z_DATA = [
  {
    topic: "Learn the basics - Things to Know in C++/Java/Python or any language",
    icon: "📘",
    questions: [
      { name: "User Input / Output", url: "https://takeuforward.org/c/c-basic-input-output/" },
      { name: "Data Types", url: "" },
      { name: "If Else statements", url: "https://takeuforward.org/if-else/if-else-statements/" },
      { name: "Switch Statement", url: "https://takeuforward.org/switch-case/switch-case-statements/" },
      { name: "What are arrays, strings?", url: "" },
      { name: "For loops", url: "https://takeuforward.org/for-loop/understanding-for-loop/" },
      { name: "While loops", url: "https://takeuforward.org/while-loop/while-loops-in-programming/" },
      { name: "Functions (Pass by Reference and Value)", url: "" },
      { name: "Time Complexity [Learn Basics, and then analyse in next Steps]", url: "https://takeuforward.org/time-complexity/time-and-space-complexity-strivers-a2z-dsa-course/" },
    ],
  },
  {
    topic: "Learn the basics - Build-up Logical Thinking",
    icon: "📘",
    questions: [
      { name: "Patterns", url: "https://takeuforward.org/strivers-a2z-dsa-course/must-do-pattern-problems-before-starting-dsa/" },
    ],
  },
  {
    topic: "Learn the basics - Learn STL/Java-Collections or similar thing in your language",
    icon: "📘",
    questions: [
      { name: "C++ STL", url: "https://takeuforward.org/c/c-stl-tutorial-most-frequent-used-stl-containers/" },
      { name: "Java Collections", url: "" },
    ],
  },
  {
    topic: "Learn the basics - Know Basic Maths",
    icon: "📘",
    questions: [
      { name: "Count Digits", url: "https://takeuforward.org/data-structure/count-digits-in-a-number/" },
      { name: "Reverse a Number", url: "https://takeuforward.org/maths/reverse-digits-of-a-number" },
      { name: "Check Palindrome", url: "https://takeuforward.org/data-structure/check-if-a-number-is-palindrome-or-not/" },
      { name: "GCD Or HCF", url: "https://takeuforward.org/data-structure/find-gcd-of-two-numbers/" },
      { name: "Armstrong Numbers", url: "https://takeuforward.org/maths/check-if-a-number-is-armstrong-number-or-not/" },
      { name: "Print all Divisors", url: "https://takeuforward.org/data-structure/print-all-divisors-of-a-given-number/" },
      { name: "Check for Prime", url: "https://takeuforward.org/data-structure/check-if-a-number-is-prime-or-not/" },
    ],
  },
  {
    topic: "Learn the basics - Learn Basic Recursion",
    icon: "📘",
    questions: [
      { name: "Understand recursion by print something N times", url: "https://takeuforward.org/recursion/introduction-to-recursion-understand-recursion-by-printing-something-n-times/" },
      { name: "Print name N times using recursion", url: "https://takeuforward.org/recursion/print-name-n-times-using-recursion/" },
      { name: "Print 1 to N using recursion", url: "https://takeuforward.org/recursion/print-1-to-n-using-recursion/" },
      { name: "Print N to 1 using recursion", url: "https://takeuforward.org/recursion/print-n-to-1-using-recursion/" },
      { name: "Sum of first N numbers", url: "https://takeuforward.org/data-structure/sum-of-first-n-natural-numbers/" },
      { name: "Factorial of N numbers", url: "https://takeuforward.org/data-structure/factorial-of-a-number-iterative-and-recursive/" },
      { name: "Reverse an array", url: "https://takeuforward.org/data-structure/reverse-a-given-array/" },
      { name: "Check if a string is palindrome or not", url: "https://takeuforward.org/data-structure/check-if-the-given-string-is-palindrome-or-not/" },
      { name: "Fibonacci Number", url: "https://takeuforward.org/arrays/print-fibonacci-series-up-to-nth-term/" },
    ],
  },
  {
    topic: "Learn the basics - Learn Basic Hashing",
    icon: "📘",
    questions: [
      { name: "Hashing Theory", url: "https://takeuforward.org/hashing/hashing-maps-time-complexity-collisions-division-rule-of-hashing-strivers-a2z-dsa-course/" },
      { name: "Counting frequencies of array elements", url: "https://takeuforward.org/data-structure/count-frequency-of-each-element-in-the-array/" },
      { name: "Find the highest/lowest frequency element", url: "https://takeuforward.org/arrays/find-the-highest-lowest-frequency-element/" },
    ],
  },
  {
    topic: "Learn Important Sorting Techniques - Sorting-I",
    icon: "🔢",
    questions: [
      { name: "Selection Sort", url: "https://takeuforward.org/sorting/selection-sort-algorithm/" },
      { name: "Bubble Sort", url: "https://takeuforward.org/data-structure/bubble-sort-algorithm/" },
      { name: "Insertion Sort", url: "https://takeuforward.org/data-structure/insertion-sort-algorithm/" },
    ],
  },
  {
    topic: "Learn Important Sorting Techniques - Sorting-II",
    icon: "🔢",
    questions: [
      { name: "Merge Sort", url: "https://takeuforward.org/data-structure/merge-sort-algorithm/" },
      { name: "Recursive Bubble Sort", url: "https://takeuforward.org/arrays/recursive-bubble-sort-algorithm/" },
      { name: "Recursive Insertion Sort", url: "https://takeuforward.org/arrays/recursive-insertion-sort-algorithm/" },
      { name: "Quick Sort", url: "https://takeuforward.org/data-structure/quick-sort-algorithm/" },
    ],
  },
  {
    topic: "Solve Problems on Arrays [Easy -> Medium -> Hard] - Easy",
    icon: "📊",
    questions: [
      { name: "Largest Element in an Array", url: "https://takeuforward.org/data-structure/find-the-largest-element-in-an-array/" },
      { name: "Second Largest Element in an Array without sorting", url: "https://takeuforward.org/data-structure/find-second-smallest-and-second-largest-element-in-an-array/" },
      { name: "Check if the array is sorted", url: "https://takeuforward.org/data-structure/check-if-an-array-is-sorted/" },
      { name: "Remove duplicates from Sorted array", url: "https://takeuforward.org/data-structure/remove-duplicates-in-place-from-sorted-array/" },
      { name: "Left Rotate an array by one place", url: "https://takeuforward.org/data-structure/left-rotate-the-array-by-one/" },
      { name: "Left rotate an array by D places", url: "https://takeuforward.org/data-structure/rotate-array-by-k-elements/" },
      { name: "Move Zeros to end", url: "https://takeuforward.org/data-structure/move-all-zeros-to-the-end-of-the-array/" },
      { name: "Linear Search", url: "https://takeuforward.org/data-structure/linear-search-in-c/" },
      { name: "Find the Union", url: "https://takeuforward.org/data-structure/union-of-two-sorted-arrays/" },
      { name: "Find missing number in an array", url: "https://takeuforward.org/arrays/find-the-missing-number-in-an-array/" },
      { name: "Maximum Consecutive Ones", url: "https://takeuforward.org/data-structure/count-maximum-consecutive-ones-in-the-array/" },
      { name: "Find the number that appears once, and other numbers twice.", url: "https://takeuforward.org/arrays/find-the-number-that-appears-once-and-the-other-numbers-twice/" },
      { name: "Longest subarray with given sum K(positives)", url: "https://takeuforward.org/data-structure/longest-subarray-with-given-sum-k/" },
      { name: "Longest subarray with sum K (Positives + Negatives)", url: "https://takeuforward.org/arrays/longest-subarray-with-sum-k-postives-and-negatives/" },
    ],
  },
  {
    topic: "Solve Problems on Arrays [Easy -> Medium -> Hard] - Medium",
    icon: "📊",
    questions: [
      { name: "2Sum Problem", url: "https://takeuforward.org/data-structure/two-sum-check-if-a-pair-with-given-sum-exists-in-array/" },
      { name: "Sort an array of 0's 1's and 2's", url: "https://takeuforward.org/data-structure/sort-an-array-of-0s-1s-and-2s/" },
      { name: "Majority Element (>n/2 times)", url: "https://takeuforward.org/data-structure/find-the-majority-element-that-occurs-more-than-n-2-times/" },
      { name: "Kadane's Algorithm, maximum subarray sum", url: "https://takeuforward.org/data-structure/kadanes-algorithm-maximum-subarray-sum-in-an-array/" },
      { name: "Print subarray with maximum subarray sum (extended version of above problem)", url: "https://takeuforward.org/data-structure/kadanes-algorithm-maximum-subarray-sum-in-an-array/" },
      { name: "Stock Buy and Sell", url: "https://takeuforward.org/data-structure/stock-buy-and-sell/" },
      { name: "Rearrange the array in alternating positive and negative items", url: "https://takeuforward.org/arrays/rearrange-array-elements-by-sign/" },
      { name: "Next Permutation", url: "https://takeuforward.org/data-structure/next_permutation-find-next-lexicographically-greater-permutation/" },
      { name: "Leaders in an Array problem", url: "https://takeuforward.org/data-structure/leaders-in-an-array/" },
      { name: "Longest Consecutive Sequence in an Array", url: "https://takeuforward.org/data-structure/longest-consecutive-sequence-in-an-array/" },
      { name: "Set Matrix Zeros", url: "https://takeuforward.org/data-structure/set-matrix-zero/" },
      { name: "Rotate Matrix by 90 degrees", url: "https://takeuforward.org/data-structure/rotate-image-by-90-degree/" },
      { name: "Print the matrix in spiral manner", url: "https://takeuforward.org/data-structure/spiral-traversal-of-matrix/" },
      { name: "Count subarrays with given sum", url: "https://takeuforward.org/arrays/count-subarray-sum-equals-k/" },
    ],
  },
  {
    topic: "Solve Problems on Arrays [Easy -> Medium -> Hard] - Hard",
    icon: "📊",
    questions: [
      { name: "Pascal's Triangle", url: "https://takeuforward.org/data-structure/program-to-generate-pascals-triangle/" },
      { name: "Majority Element (n/3 times)", url: "https://takeuforward.org/data-structure/majority-elementsn-3-times-find-the-elements-that-appears-more-than-n-3-times-in-the-array/" },
      { name: "3-Sum Problem", url: "https://takeuforward.org/data-structure/3-sum-find-triplets-that-add-up-to-a-zero/" },
      { name: "4-Sum Problem", url: "https://takeuforward.org/data-structure/4-sum-find-quads-that-add-up-to-a-target-value/" },
      { name: "Largest Subarray with 0 Sum", url: "https://takeuforward.org/data-structure/length-of-the-longest-subarray-with-zero-sum/" },
      { name: "Count number of subarrays with given xor K", url: "https://takeuforward.org/data-structure/count-the-number-of-subarrays-with-given-xor-k/" },
      { name: "Merge Overlapping Subintervals", url: "https://takeuforward.org/data-structure/merge-overlapping-sub-intervals/" },
      { name: "Merge two sorted arrays without extra space", url: "https://takeuforward.org/data-structure/merge-two-sorted-arrays-without-extra-space/" },
      { name: "Find the repeating and missing number", url: "https://takeuforward.org/data-structure/find-the-repeating-and-missing-numbers/" },
      { name: "Count Inversions", url: "https://takeuforward.org/data-structure/count-inversions-in-an-array/" },
      { name: "Reverse Pairs", url: "https://takeuforward.org/data-structure/count-reverse-pairs/" },
      { name: "Maximum Product Subarray", url: "https://takeuforward.org/data-structure/maximum-product-subarray-in-an-array/" },
    ],
  },
  {
    topic: "Binary Search [1D, 2D Arrays, Search Space] - BS on 1D Arrays",
    icon: "🔍",
    questions: [
      { name: "Binary Search to find X in sorted array", url: "https://takeuforward.org/data-structure/binary-search-explained/" },
      { name: "Implement Lower Bound", url: "https://takeuforward.org/arrays/implement-lower-bound-bs-2/" },
      { name: "Implement Upper Bound", url: "https://takeuforward.org/arrays/implement-upper-bound/" },
      { name: "Search Insert Position", url: "https://takeuforward.org/arrays/search-insert-position/" },
      { name: "Floor/Ceil in Sorted Array", url: "https://takeuforward.org/arrays/floor-and-ceil-in-sorted-array/" },
      { name: "Find the first or last occurrence of a given number in a sorted array", url: "https://takeuforward.org/data-structure/last-occurrence-in-a-sorted-array/" },
      { name: "Count occurrences of a number in a sorted array with duplicates", url: "https://takeuforward.org/data-structure/count-occurrences-in-sorted-array/" },
      { name: "Search in Rotated Sorted Array I", url: "https://takeuforward.org/data-structure/search-element-in-a-rotated-sorted-array/" },
      { name: "Search in Rotated Sorted Array II", url: "https://takeuforward.org/arrays/search-element-in-rotated-sorted-array-ii/" },
      { name: "Find minimum in Rotated Sorted Array", url: "https://takeuforward.org/data-structure/minimum-in-rotated-sorted-array/" },
      { name: "Find out how many times has an array been rotated", url: "https://takeuforward.org/arrays/find-out-how-many-times-the-array-has-been-rotated/" },
      { name: "Single element in a Sorted Array", url: "https://takeuforward.org/data-structure/search-single-element-in-a-sorted-array/" },
      { name: "Find peak element", url: "https://takeuforward.org/data-structure/peak-element-in-array/" },
    ],
  },
  {
    topic: "Binary Search [1D, 2D Arrays, Search Space] - BS on Answers",
    icon: "🔍",
    questions: [
      { name: "Find square root of a number in log n", url: "https://takeuforward.org/binary-search/finding-sqrt-of-a-number-using-binary-search/" },
      { name: "Find the Nth root of a number using binary search", url: "https://takeuforward.org/data-structure/nth-root-of-a-number-using-binary-search/" },
      { name: "Koko Eating Bananas", url: "https://takeuforward.org/binary-search/koko-eating-bananas/" },
      { name: "Minimum days to make M bouquets", url: "https://takeuforward.org/arrays/minimum-days-to-make-m-bouquets/" },
      { name: "Find the smallest Divisor", url: "https://takeuforward.org/arrays/find-the-smallest-divisor-given-a-threshold/" },
      { name: "Capacity to Ship Packages within D Days", url: "https://takeuforward.org/arrays/capacity-to-ship-packages-within-d-days/" },
      { name: "Kth Missing Positive Number", url: "https://takeuforward.org/arrays/kth-missing-positive-number/" },
      { name: "Aggressive Cows", url: "https://takeuforward.org/data-structure/aggressive-cows-detailed-solution/" },
      { name: "Book Allocation Problem", url: "https://takeuforward.org/data-structure/allocate-minimum-number-of-pages/" },
      { name: "Split array - Largest Sum", url: "https://takeuforward.org/arrays/split-array-largest-sum/" },
      { name: "Painter's partition", url: "https://takeuforward.org/arrays/painters-partition-problem/" },
      { name: "Minimize Max Distance to Gas Station", url: "https://takeuforward.org/arrays/minimise-maximum-distance-between-gas-stations/" },
      { name: "Median of 2 sorted arrays", url: "https://takeuforward.org/data-structure/median-of-two-sorted-arrays-of-different-sizes/" },
      { name: "Kth element of 2 sorted arrays", url: "https://takeuforward.org/data-structure/k-th-element-of-two-sorted-arrays/" },
    ],
  },
  {
    topic: "Binary Search [1D, 2D Arrays, Search Space] - BS on 2D Arrays",
    icon: "🔍",
    questions: [
      { name: "Find the row with maximum number of 1's", url: "https://takeuforward.org/arrays/find-the-row-with-maximum-number-of-1s/" },
      { name: "Search in a 2 D matrix", url: "https://takeuforward.org/data-structure/search-in-a-sorted-2d-matrix/" },
      { name: "Search in a row and column wise sorted matrix", url: "https://takeuforward.org/arrays/search-in-a-row-and-column-wise-sorted-matrix/" },
      { name: "Find Peak Element (2D Matrix)", url: "" },
      { name: "Matrix Median", url: "https://takeuforward.org/data-structure/median-of-row-wise-sorted-matrix/" },
    ],
  },
  {
    topic: "Strings [Basic and Medium] - Basic and Easy String Problems",
    icon: "📝",
    questions: [
      { name: "Remove outermost Paranthesis", url: "" },
      { name: "Reverse words in a given string / Palindrome Check", url: "https://takeuforward.org/data-structure/reverse-words-in-a-string/" },
      { name: "Largest odd number in a string", url: "" },
      { name: "Longest Common Prefix", url: "" },
      { name: "Isomorphic String", url: "" },
      { name: "check whether one string is a rotation of another", url: "" },
      { name: "Check if two strings are anagram of each other", url: "https://takeuforward.org/data-structure/check-if-two-strings-are-anagrams-of-each-other/" },
    ],
  },
  {
    topic: "Strings [Basic and Medium] - Medium String Problems",
    icon: "📝",
    questions: [
      { name: "Sort Characters by frequency", url: "" },
      { name: "Maximum Nesting Depth of Paranthesis", url: "" },
      { name: "Roman Number to Integer and vice versa", url: "" },
      { name: "Implement Atoi", url: "" },
      { name: "Count Number of Substrings", url: "" },
      { name: "Longest Palindromic Substring[Do it without DP]", url: "" },
      { name: "Sum of Beauty of all substring", url: "" },
      { name: "Reverse Every Word in A String", url: "" },
    ],
  },
  {
    topic: "Learn LinkedList [Single LL, Double LL, Medium, Hard Problems] - Learn 1D LinkedList",
    icon: "🔗",
    questions: [
      { name: "Introduction to LinkedList, learn about struct, and how is node represented", url: "https://takeuforward.org/linked-list/linked-list-introduction" },
      { name: "Inserting a node in LinkedList", url: "https://takeuforward.org/linked-list/insert-at-the-head-of-a-linked-list" },
      { name: "Deleting a node in LinkedList", url: "https://takeuforward.org/data-structure/delete-last-node-of-linked-list/" },
      { name: "Find the length of the linkedlist [learn traversal]", url: "https://takeuforward.org/linked-list/find-the-length-of-a-linked-list" },
      { name: "Search an element in the LL", url: "https://takeuforward.org/linked-list/search-an-element-in-a-linked-list" },
    ],
  },
  {
    topic: "Learn LinkedList [Single LL, Double LL, Medium, Hard Problems] - Learn Doubly LinkedList",
    icon: "🔗",
    questions: [
      { name: "Introduction to DLL, learn about struct, and how is node represented", url: "https://takeuforward.org/linked-list/introduction-to-doubly-linked-list" },
      { name: "Insert a node in DLL", url: "https://takeuforward.org/data-structure/insert-at-end-of-doubly-linked-list/" },
      { name: "Delete a node in DLL", url: "https://takeuforward.org/data-structure/delete-last-node-of-a-doubly-linked-list/" },
      { name: "Reverse a DLL", url: "https://takeuforward.org/data-structure/reverse-a-doubly-linked-list/" },
    ],
  },
  {
    topic: "Learn LinkedList [Single LL, Double LL, Medium, Hard Problems] - Medium Problems of LL",
    icon: "🔗",
    questions: [
      { name: "Middle of a LinkedList [TortoiseHare Method]", url: "https://takeuforward.org/data-structure/find-middle-element-in-a-linked-list/" },
      { name: "Reverse a LinkedList [Iterative]", url: "https://takeuforward.org/data-structure/reverse-a-linked-list/" },
      { name: "Reverse a LL [Recursive]", url: "https://takeuforward.org/data-structure/reverse-a-linked-list/" },
      { name: "Detect a loop in LL", url: "https://takeuforward.org/data-structure/detect-a-cycle-in-a-linked-list/" },
      { name: "Find the starting point in LL", url: "https://takeuforward.org/data-structure/starting-point-of-loop-in-a-linked-list/" },
      { name: "Length of Loop in LL", url: "https://takeuforward.org/linked-list/length-of-loop-in-linked-list" },
      { name: "Check if LL is palindrome or not", url: "https://takeuforward.org/data-structure/check-if-given-linked-list-is-plaindrome/" },
      { name: "Segrregate odd and even nodes in LL", url: "https://takeuforward.org/data-structure/segregate-even-and-odd-nodes-in-linkedlist" },
      { name: "Remove Nth node from the back of the LL", url: "https://takeuforward.org/data-structure/remove-n-th-node-from-the-end-of-a-linked-list/" },
      { name: "Delete the middle node of LL", url: "https://takeuforward.org/linked-list/delete-the-middle-node-of-the-linked-list" },
      { name: "Sort LL", url: "https://takeuforward.org/linked-list/sort-a-linked-list" },
      { name: "Sort a LL of 0's 1's and 2's by changing links", url: "" },
      { name: "Find the intersection point of Y LL", url: "https://takeuforward.org/data-structure/find-intersection-of-two-linked-lists/" },
      { name: "Add 1 to a number represented by LL", url: "" },
      { name: "Add 2 numbers in LL", url: "https://takeuforward.org/data-structure/add-two-numbers-represented-as-linked-lists/" },
    ],
  },
  {
    topic: "Learn LinkedList [Single LL, Double LL, Medium, Hard Problems] - Medium Problems of DLL",
    icon: "🔗",
    questions: [
      { name: "Delete all occurrences of a key in DLL", url: "" },
      { name: "Find pairs with given sum in DLL", url: "" },
      { name: "Remove duplicates from sorted DLL", url: "" },
    ],
  },
  {
    topic: "Learn LinkedList [Single LL, Double LL, Medium, Hard Problems] - Hard Problems of LL",
    icon: "🔗",
    questions: [
      { name: "Reverse LL in group of given size K", url: "https://takeuforward.org/data-structure/reverse-linked-list-in-groups-of-size-k/" },
      { name: "Rotate a LL", url: "https://takeuforward.org/data-structure/rotate-a-linked-list/" },
      { name: "Flattening of LL", url: "https://takeuforward.org/data-structure/flattening-a-linked-list/" },
      { name: "Clone a Linked List with random and next pointer", url: "https://takeuforward.org/data-structure/clone-linked-list-with-random-and-next-pointer/" },
    ],
  },
  {
    topic: "Recursion [PatternWise] - Get a Strong Hold",
    icon: "🔄",
    questions: [
      { name: "Recursive Implementation of atoi()", url: "" },
      { name: "Pow(x, n)", url: "https://takeuforward.org/data-structure/implement-powxn-x-raised-to-the-power-n/" },
      { name: "Count Good numbers", url: "" },
      { name: "Sort a stack using recursion", url: "" },
      { name: "Reverse a stack using recursion", url: "" },
    ],
  },
  {
    topic: "Recursion [PatternWise] - Subsequences Pattern",
    icon: "🔄",
    questions: [
      { name: "Generate all binary strings", url: "" },
      { name: "Generate Paranthesis", url: "" },
      { name: "Print all subsequences/Power Set", url: "https://takeuforward.org/data-structure/power-set-print-all-the-possible-subsequences-of-the-string/" },
      { name: "Learn All Patterns of Subsequences (Theory)", url: "" },
      { name: "Count all subsequences with sum K", url: "" },
      { name: "Check if there exists a subsequence with sum K", url: "" },
      { name: "Combination Sum", url: "https://takeuforward.org/data-structure/combination-sum-1/" },
      { name: "Combination Sum-II", url: "https://takeuforward.org/data-structure/combination-sum-ii-find-all-unique-combinations/" },
      { name: "Subset Sum-I", url: "https://takeuforward.org/data-structure/subset-sum-sum-of-all-subsets/" },
      { name: "Subset Sum-II", url: "https://takeuforward.org/data-structure/subset-ii-print-all-the-unique-subsets/" },
      { name: "Combination Sum - III", url: "" },
      { name: "Letter Combinations of a Phone number", url: "" },
    ],
  },
  {
    topic: "Recursion [PatternWise] - Trying out all Combos / Hard",
    icon: "🔄",
    questions: [
      { name: "Palindrome Partitioning", url: "https://takeuforward.org/data-structure/palindrome-partitioning/" },
      { name: "Word Search", url: "https://takeuforward.org/data-structure/word-search-leetcode/" },
      { name: "N Queen", url: "https://takeuforward.org/data-structure/n-queen-problem-return-all-distinct-solutions-to-the-n-queens-puzzle/" },
      { name: "Rat in a Maze", url: "https://takeuforward.org/data-structure/rat-in-a-maze/" },
      { name: "Word Break", url: "" },
      { name: "M Coloring Problem", url: "https://takeuforward.org/data-structure/m-coloring-problem/" },
      { name: "Sudoko Solver", url: "https://takeuforward.org/data-structure/sudoku-solver/" },
      { name: "Expression Add Operators", url: "" },
    ],
  },
  {
    topic: "Bit Manipulation [Concepts & Problems] - Learn Bit Manipulation",
    icon: "🧮",
    questions: [
      { name: "Introduction to Bit Manipulation [Theory]", url: "" },
      { name: "Check if the i-th bit is set or not", url: "" },
      { name: "Check if a number is odd or not", url: "" },
      { name: "Check if a number is power of 2 or not", url: "" },
      { name: "Count the number of set bits", url: "" },
      { name: "Set/Unset the rightmost unset bit", url: "" },
      { name: "Swap two numbers", url: "" },
      { name: "Divide two integers without using multiplication, division and mod operator", url: "" },
    ],
  },
  {
    topic: "Bit Manipulation [Concepts & Problems] - Interview Problems",
    icon: "🧮",
    questions: [
      { name: "Count number of bits to be flipped to convert A to B", url: "" },
      { name: "Find the number that appears odd number of times", url: "" },
      { name: "Power Set", url: "" },
      { name: "Find xor of numbers from L to R", url: "" },
      { name: "Find the two numbers appearing odd number of times", url: "" },
    ],
  },
  {
    topic: "Bit Manipulation [Concepts & Problems] - Advanced Maths",
    icon: "🧮",
    questions: [
      { name: "Print Prime Factors of a Number", url: "" },
      { name: "All Divisors of a Number", url: "" },
      { name: "Sieve of Eratosthenes", url: "" },
      { name: "Find Prime Factorisation of a Number using Sieve", url: "" },
      { name: "Power(n, x)", url: "" },
    ],
  },
  {
    topic: "Stack and Queues [Learning, Pre-In-Post-fix, Monotonic Stack, Implementation] - Learning",
    icon: "📚",
    questions: [
      { name: "Implement Stack using Arrays", url: "https://takeuforward.org/data-structure/implement-stack-using-array/" },
      { name: "Implement Queue using Arrays", url: "https://takeuforward.org/data-structure/implement-queue-using-array/" },
      { name: "Implement Stack using Queue", url: "https://takeuforward.org/data-structure/implement-stack-using-single-queue/" },
      { name: "Implement Queue using Stack", url: "https://takeuforward.org/data-structure/implement-queue-using-stack/" },
      { name: "Implement stack using Linkedlist", url: "https://takeuforward.org/data-structure/implement-stack-using-linked-list/" },
      { name: "Implement queue using Linkedlist", url: "https://takeuforward.org/data-structure/implement-queue-using-linked-list/" },
      { name: "Check for balanced paranthesis", url: "https://takeuforward.org/data-structure/check-for-balanced-parentheses/" },
      { name: "Implement Min Stack", url: "https://takeuforward.org/data-structure/implement-min-stack-o2n-and-on-space-complexity/" },
    ],
  },
  {
    topic: "Stack and Queues [Learning, Pre-In-Post-fix, Monotonic Stack, Implementation] - Prefix, Infix, PostFix Conversion Problems",
    icon: "📚",
    questions: [
      { name: "Infix to Postfix Conversion using Stack", url: "https://takeuforward.org/data-structure/infix-to-postfix/" },
      { name: "Prefix to Infix Conversion", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2" },
      { name: "Prefix to Postfix Conversion", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2" },
      { name: "Postfix to Prefix Conversion", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2" },
      { name: "Postfix to Infix", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2" },
      { name: "Convert Infix To Prefix Notation", url: "https://takeuforward.org/data-structure/infix-to-prefix/" },
    ],
  },
  {
    topic: "Stack and Queues [Learning, Pre-In-Post-fix, Monotonic Stack, Implementation] - Monotonic Stack/Queue Problems [VVV. Imp]",
    icon: "📚",
    questions: [
      { name: "Next Greater Element", url: "https://takeuforward.org/data-structure/next-greater-element-using-stack/" },
      { name: "Next Greater Element 2", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2" },
      { name: "Next Smaller Element", url: "" },
      { name: "Number of NGEs to the right", url: "" },
      { name: "Trapping Rainwater", url: "https://takeuforward.org/data-structure/trapping-rainwater/" },
      { name: "Sum of subarray minimum", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2" },
      { name: "Asteroid Collision", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2" },
      { name: "Sum of subarray ranges", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2" },
      { name: "Remove k Digits", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2" },
      { name: "Largest rectangle in a histogram", url: "https://takeuforward.org/data-structure/area-of-largest-rectangle-in-histogram/" },
      { name: "Maximal Rectangles", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2" },
    ],
  },
  {
    topic: "Stack and Queues [Learning, Pre-In-Post-fix, Monotonic Stack, Implementation] - Implementation Problems",
    icon: "📚",
    questions: [
      { name: "Sliding Window maximum", url: "https://takeuforward.org/data-structure/sliding-window-maximum/" },
      { name: "Stock span problem", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2" },
      { name: "The Celebrity Problem", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2" },
      { name: "LRU cache (IMPORTANT)", url: "https://takeuforward.org/data-structure/implement-lru-cache/" },
      { name: "LFU cache", url: "" },
    ],
  },
  {
    topic: "Sliding Window & Two Pointer Combined Problems - Medium Problems",
    icon: "🪟",
    questions: [
      { name: "Longest Substring Without Repeating Characters", url: "https://takeuforward.org/data-structure/length-of-longest-substring-without-any-repeating-character/" },
      { name: "Max Consecutive Ones III", url: "" },
      { name: "Fruit Into Baskets", url: "" },
      { name: "longest repeating character replacement", url: "" },
      { name: "Binary subarray with sum", url: "" },
      { name: "Count number of nice subarrays", url: "" },
      { name: "Number of substring containing all three characters", url: "" },
      { name: "Maximum point you can obtain from cards", url: "" },
    ],
  },
  {
    topic: "Sliding Window & Two Pointer Combined Problems - Hard Problems",
    icon: "🪟",
    questions: [
      { name: "Longest Substring with At Most K Distinct Characters", url: "" },
      { name: "Subarray with k different integers", url: "" },
      { name: "Minimum Window Substring", url: "" },
      { name: "Minimum Window Subsequence", url: "" },
    ],
  },
  {
    topic: "Heaps [Learning, Medium, Hard Problems] - Learning",
    icon: "⚙️",
    questions: [
      { name: "Introduction to Priority Queues using Binary Heaps", url: "" },
      { name: "Min Heap and Max Heap Implementation", url: "" },
      { name: "Check if an array represents a min-heap or not", url: "" },
      { name: "Convert min Heap to max Heap", url: "" },
    ],
  },
  {
    topic: "Heaps [Learning, Medium, Hard Problems] - Medium Problems",
    icon: "⚙️",
    questions: [
      { name: "Kth largest element in an array [use priority queue]", url: "https://takeuforward.org/data-structure/kth-largest-smallest-element-in-an-array/" },
      { name: "Kth smallest element in an array [use priority queue]", url: "https://takeuforward.org/data-structure/kth-largest-smallest-element-in-an-array/" },
      { name: "Sort K sorted array", url: "" },
      { name: "Merge M sorted Lists", url: "" },
      { name: "Replace each array element by its corresponding rank", url: "https://takeuforward.org/data-structure/replace-elements-by-its-rank-in-the-array/" },
      { name: "Task Scheduler", url: "" },
      { name: "Hands of Straights", url: "" },
    ],
  },
  {
    topic: "Heaps [Learning, Medium, Hard Problems] - Hard Problems",
    icon: "⚙️",
    questions: [
      { name: "Design twitter", url: "" },
      { name: "Connect `n` ropes with minimal cost", url: "" },
      { name: "Kth largest element in a stream of running integers", url: "" },
      { name: "Maximum Sum Combination", url: "" },
      { name: "Find Median from Data Stream", url: "" },
      { name: "K most frequent elements", url: "" },
    ],
  },
  {
    topic: "Greedy Algorithms [Easy, Medium/Hard] - Easy Problems",
    icon: "💰",
    questions: [
      { name: "Assign Cookies", url: "https://takeuforward.org/Greedy/assign-cookies" },
      { name: "Fractional Knapsack Problem", url: "https://takeuforward.org/data-structure/fractional-knapsack-problem-greedy-approach/" },
      { name: "Greedy algorithm to find minimum number of coins", url: "https://takeuforward.org/data-structure/find-minimum-number-of-coins/" },
      { name: "Lemonade Change", url: "https://takeuforward.org/Greedy/lemonade-change" },
      { name: "Valid Paranthesis Checker", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2" },
    ],
  },
  {
    topic: "Greedy Algorithms [Easy, Medium/Hard] - Medium/Hard",
    icon: "💰",
    questions: [
      { name: "N meetings in one room", url: "https://takeuforward.org/data-structure/n-meetings-in-one-room/" },
      { name: "Jump Game", url: "https://takeuforward.org/Greedy/jump-game-i" },
      { name: "Jump Game 2", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2" },
      { name: "Minimum number of platforms required for a railway", url: "https://takeuforward.org/data-structure/minimum-number-of-platforms-required-for-a-railway/" },
      { name: "Job sequencing Problem", url: "https://takeuforward.org/data-structure/job-sequencing-problem/" },
      { name: "Candy", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2" },
      { name: "Program for Shortest Job First (or SJF) CPU Scheduling", url: "https://takeuforward.org/Greedy/shortest-job-first-or-sjf-cpu-scheduling" },
      { name: "Program for Least Recently Used (LRU) Page Replacement Algorithm", url: "" },
      { name: "Insert Interval", url: "https://takeuforward.org/?s=Insert+Interval" },
      { name: "Merge Intervals", url: "https://takeuforward.org/data-structure/merge-overlapping-sub-intervals/" },
      { name: "Non-overlapping Intervals", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2" },
    ],
  },
  {
    topic: "Binary Trees [Traversals, Medium and Hard Problems] - Traversals",
    icon: "🌳",
    questions: [
      { name: "Introduction to Trees", url: "https://takeuforward.org/binary-tree/introduction-to-trees/" },
      { name: "Binary Tree Representation in C++", url: "https://takeuforward.org/binary-tree/binary-tree-representation-in-c/" },
      { name: "Binary Tree Representation in Java", url: "https://takeuforward.org/binary-tree/binary-tree-representation-in-java/" },
      { name: "Binary Tree Traversals in Binary Tree", url: "https://takeuforward.org/binary-tree/binary-tree-traversal-inorder-preorder-postorder/" },
      { name: "Preorder Traversal of Binary Tree", url: "https://takeuforward.org/data-structure/preorder-traversal-of-binary-tree/" },
      { name: "Inorder Traversal of Binary Tree", url: "https://takeuforward.org/data-structure/inorder-traversal-of-binary-tree/" },
      { name: "Post-order Traversal of Binary Tree", url: "https://takeuforward.org/data-structure/post-order-traversal-of-binary-tree/" },
      { name: "Level order Traversal / Level order traversal in spiral form", url: "https://takeuforward.org/data-structure/level-order-traversal-of-a-binary-tree/" },
      { name: "Iterative Preorder Traversal of Binary Tree", url: "https://takeuforward.org/data-structure/iterative-preorder-traversal-of-binary-tree" },
      { name: "Iterative Inorder Traversal of Binary Tree", url: "https://takeuforward.org/data-structure/inorder-traversal-of-binary-tree/" },
      { name: "Post-order Traversal of Binary Tree using 2 stack", url: "https://takeuforward.org/data-structure/iterative-postorder-traversal-of-binary-tree-using-2-stack" },
      { name: "Post-order Traversal of Binary Tree using 1 stack", url: "https://takeuforward.org/data-structure/post-order-traversal-of-binary-tree/" },
      { name: "Preorder, Inorder, and Postorder Traversal in one Traversal", url: "https://takeuforward.org/data-structure/preorder-inorder-postorder-traversals-in-one-traversal/" },
    ],
  },
  {
    topic: "Binary Trees [Traversals, Medium and Hard Problems] - Medium Problems",
    icon: "🌳",
    questions: [
      { name: "Height of a Binary Tree", url: "https://takeuforward.org/data-structure/maximum-depth-of-a-binary-tree/" },
      { name: "Check if the Binary tree is height-balanced or not", url: "https://takeuforward.org/data-structure/check-if-the-binary-tree-is-balanced-binary-tree/" },
      { name: "Diameter of Binary Tree", url: "https://takeuforward.org/data-structure/calculate-the-diameter-of-a-binary-tree/" },
      { name: "Maximum path sum", url: "https://takeuforward.org/data-structure/maximum-sum-path-in-binary-tree/" },
      { name: "Check if two trees are identical or not", url: "https://takeuforward.org/data-structure/check-if-two-trees-are-identical/" },
      { name: "Zig Zag Traversal of Binary Tree", url: "https://takeuforward.org/data-structure/zig-zag-traversal-of-binary-tree/" },
      { name: "Boundary Traversal of Binary Tree", url: "https://takeuforward.org/data-structure/boundary-traversal-of-a-binary-tree/" },
      { name: "Vertical Order Traversal of Binary Tree", url: "https://takeuforward.org/data-structure/vertical-order-traversal-of-binary-tree/" },
      { name: "Top View of Binary Tree", url: "https://takeuforward.org/data-structure/top-view-of-a-binary-tree/" },
      { name: "Bottom View of Binary Tree", url: "https://takeuforward.org/data-structure/bottom-view-of-a-binary-tree/" },
      { name: "Right/Left View of Binary Tree", url: "https://takeuforward.org/data-structure/right-left-view-of-binary-tree/" },
      { name: "Symmetric Binary Tree", url: "https://takeuforward.org/data-structure/check-for-symmetrical-binary-tree/" },
    ],
  },
  {
    topic: "Binary Trees [Traversals, Medium and Hard Problems] - Hard Problems",
    icon: "🌳",
    questions: [
      { name: "Root to Node Path in Binary Tree", url: "https://takeuforward.org/data-structure/print-root-to-node-path-in-a-binary-tree/" },
      { name: "LCA in Binary Tree", url: "https://takeuforward.org/data-structure/lowest-common-ancestor-for-two-given-nodes/" },
      { name: "Maximum width of a Binary Tree", url: "https://takeuforward.org/data-structure/maximum-width-of-a-binary-tree/" },
      { name: "Check for Children Sum Property", url: "https://takeuforward.org/data-structure/check-for-children-sum-property-in-a-binary-tree/" },
      { name: "Print all the Nodes at a distance of K in a Binary Tree", url: "" },
      { name: "Minimum time taken to BURN the Binary Tree from a Node", url: "" },
      { name: "Count total Nodes in a COMPLETE Binary Tree", url: "https://takeuforward.org/binary-tree/count-number-of-nodes-in-a-binary-tree/" },
      { name: "Requirements needed to construct a Unique Binary Tree | Theory", url: "" },
      { name: "Construct Binary Tree from inorder and preorder", url: "https://takeuforward.org/data-structure/construct-a-binary-tree-from-inorder-and-preorder-traversal/" },
      { name: "Construct the Binary Tree from Postorder and Inorder Traversal", url: "https://takeuforward.org/data-structure/construct-binary-tree-from-inorder-and-postorder-traversal/" },
      { name: "Serialize and deserialize Binary Tree", url: "https://takeuforward.org/data-structure/serialize-and-deserialize-a-binary-tree/" },
      { name: "Morris Preorder Traversal of a Binary Tree", url: "https://takeuforward.org/data-structure/morris-preorder-traversal-of-a-binary-tree/" },
      { name: "Morris Inorder Traversal of a Binary Tree", url: "https://takeuforward.org/data-structure/morris-inorder-traversal-of-a-binary-tree/" },
      { name: "Flatten Binary Tree to LinkedList", url: "https://takeuforward.org/data-structure/flatten-binary-tree-to-linked-list/" },
    ],
  },
  {
    topic: "Binary Search Trees [Concept and Problems] - Concepts",
    icon: "🌲",
    questions: [
      { name: "Introduction to Binary Search Tree", url: "https://takeuforward.org/binary-search-tree/introduction-to-binary-search-trees/" },
      { name: "Search in a Binary Search Tree", url: "https://takeuforward.org/data-structure/search-in-a-binary-search-tree-2/" },
      { name: "Find Min/Max in BST", url: "" },
    ],
  },
  {
    topic: "Binary Search Trees [Concept and Problems] - Practice Problems",
    icon: "🌲",
    questions: [
      { name: "Ceil in a Binary Search Tree", url: "https://takeuforward.org/binary-search-tree/ceil-in-a-binary-search-tree/" },
      { name: "Floor in a Binary Search Tree", url: "https://takeuforward.org/binary-search-tree/floor-in-a-binary-search-tree/" },
      { name: "Insert a given Node in Binary Search Tree", url: "" },
      { name: "Delete a Node in Binary Search Tree", url: "" },
      { name: "Find K-th smallest/largest element in BST", url: "https://takeuforward.org/data-structure/kth-largest-smallest-element-in-binary-search-tree/" },
      { name: "Check if a tree is a BST or BT", url: "" },
      { name: "LCA in Binary Search Tree", url: "" },
      { name: "Construct a BST from a preorder traversal", url: "" },
      { name: "Inorder Successor/Predecessor in BST", url: "" },
      { name: "Merge 2 BST's", url: "" },
      { name: "Two Sum In BST | Check if there exists a pair with Sum K", url: "" },
      { name: "Recover BST | Correct BST with two nodes swapped", url: "" },
      { name: "Largest BST in Binary Tree", url: "" },
    ],
  },
  {
    topic: "Graphs [Concepts & Problems] - Learning",
    icon: "🕸️",
    questions: [
      { name: "Graph and Types", url: "https://takeuforward.org/graph/introduction-to-graph/" },
      { name: "Graph Representation | C++", url: "https://takeuforward.org/graph/graph-representation-in-c/" },
      { name: "Graph Representation | Java", url: "" },
      { name: "Connected Components | Logic Explanation", url: "https://takeuforward.org/graph/connected-components-in-graphs/" },
      { name: "BFS", url: "https://takeuforward.org/graph/breadth-first-search-bfs-level-order-traversal/" },
      { name: "DFS", url: "https://takeuforward.org/data-structure/depth-first-search-dfs/" },
    ],
  },
  {
    topic: "Graphs [Concepts & Problems] - Problems on BFS/DFS",
    icon: "🕸️",
    questions: [
      { name: "Number of provinces (leetcode)", url: "https://takeuforward.org/data-structure/number-of-provinces/" },
      { name: "Connected Components Problem in Matrix", url: "" },
      { name: "Rotten Oranges", url: "https://takeuforward.org/data-structure/rotten-oranges-min-time-to-rot-all-oranges-bfs/" },
      { name: "Flood fill", url: "https://takeuforward.org/graph/flood-fill-algorithm-graphs/" },
      { name: "Cycle Detection in unirected Graph (bfs)", url: "https://takeuforward.org/data-structure/detect-cycle-in-an-undirected-graph-using-bfs/" },
      { name: "Cycle Detection in undirected Graph (dfs)", url: "https://takeuforward.org/data-structure/detect-cycle-in-an-undirected-graph-using-dfs/" },
      { name: "0/1 Matrix (Bfs Problem)", url: "https://takeuforward.org/graph/distance-of-nearest-cell-having-1/" },
      { name: "Surrounded Regions (dfs)", url: "https://takeuforward.org/graph/surrounded-regions-replace-os-with-xs/" },
      { name: "Number of Enclaves [flood fill implementation - multisource]", url: "https://takeuforward.org/graph/number-of-enclaves/" },
      { name: "Word ladder - 1", url: "https://takeuforward.org/graph/word-ladder-i-g-29/" },
      { name: "Word ladder - 2", url: "https://takeuforward.org/graph/g-30-word-ladder-ii/" },
      { name: "Number of Distinct Islands [dfs multisource]", url: "https://takeuforward.org/data-structure/number-of-islands/" },
      { name: "Bipartite Graph (DFS)", url: "https://takeuforward.org/graph/bipartite-graph-dfs-implementation/" },
      { name: "Cycle Detection in Directed Graph (DFS)", url: "https://takeuforward.org/data-structure/detect-cycle-in-a-directed-graph-using-dfs-g-19/" },
    ],
  },
  {
    topic: "Graphs [Concepts & Problems] - Topo Sort and Problems",
    icon: "🕸️",
    questions: [
      { name: "Topo Sort", url: "https://takeuforward.org/data-structure/topological-sort-algorithm-dfs-g-21/" },
      { name: "Kahn's Algorithm", url: "https://takeuforward.org/data-structure/kahns-algorithm-topological-sort-algorithm-bfs-g-22/" },
      { name: "Cycle Detection in Directed Graph (BFS)", url: "" },
      { name: "Course Schedule - I", url: "https://takeuforward.org/data-structure/course-schedule-i-and-ii-pre-requisite-tasks-topological-sort-g-24/" },
      { name: "Course Schedule - II", url: "https://takeuforward.org/data-structure/course-schedule-i-and-ii-pre-requisite-tasks-topological-sort-g-24/" },
      { name: "Find eventual safe states", url: "https://takeuforward.org/data-structure/find-eventual-safe-states-bfs-topological-sort-g-25/" },
      { name: "Alien dictionary", url: "https://takeuforward.org/data-structure/alien-dictionary-topological-sort-g-26/" },
    ],
  },
  {
    topic: "Graphs [Concepts & Problems] - Shortest Path Algorithms and Problems",
    icon: "🕸️",
    questions: [
      { name: "Shortest Path in UG with unit weights", url: "https://takeuforward.org/data-structure/shortest-path-in-undirected-graph-with-unit-distance-g-28/" },
      { name: "Shortest Path in DAG", url: "https://takeuforward.org/data-structure/shortest-path-in-directed-acyclic-graph-topological-sort-g-27/" },
      { name: "Djisktra's Algorithm", url: "https://takeuforward.org/data-structure/dijkstras-algorithm-using-set-g-33/" },
      { name: "Why priority Queue is used in Djisktra's Algorithm", url: "https://takeuforward.org/data-structure/dijkstras-algorithm-using-priority-queue-g-32/" },
      { name: "Shortest path in a binary maze", url: "https://takeuforward.org/data-structure/g-36-shortest-distance-in-a-binary-maze/" },
      { name: "Path with minimum effort", url: "https://takeuforward.org/data-structure/g-37-path-with-minimum-effort/" },
      { name: "Cheapest flights within k stops", url: "https://takeuforward.org/data-structure/g-38-cheapest-flights-within-k-stops/" },
      { name: "Network Delay time", url: "" },
      { name: "Number of ways to arrive at destination", url: "https://takeuforward.org/data-structure/g-40-number-of-ways-to-arrive-at-destination/" },
      { name: "Minimum steps to reach end from start by performing multiplication and mod operations with array elements", url: "https://takeuforward.org/graph/g-39-minimum-multiplications-to-reach-end/" },
      { name: "Bellman Ford Algorithm", url: "https://takeuforward.org/data-structure/bellman-ford-algorithm-g-41/" },
      { name: "Floyd Warshal Algorithm", url: "https://takeuforward.org/data-structure/floyd-warshall-algorithm-g-42/" },
      { name: "Find the city with the smallest number of neighbors in a threshold distance", url: "https://takeuforward.org/data-structure/find-the-city-with-the-smallest-number-of-neighbours-at-a-threshold-distance-g-43/" },
    ],
  },
  {
    topic: "Graphs [Concepts & Problems] - MinimumSpanningTree/Disjoint Set and Problems",
    icon: "🕸️",
    questions: [
      { name: "Minimum Spanning Tree", url: "https://takeuforward.org/data-structure/minimum-spanning-tree-theory-g-44/" },
      { name: "Prim's Algorithm", url: "https://takeuforward.org/data-structure/prims-algorithm-minimum-spanning-tree-c-and-java-g-45/" },
      { name: "Disjoint Set [Union by Rank]", url: "https://takeuforward.org/data-structure/disjoint-set-union-by-rank-union-by-size-path-compression-g-46/" },
      { name: "Disjoint Set [Union by Size]", url: "https://takeuforward.org/data-structure/disjoint-set-union-by-rank-union-by-size-path-compression-g-46/" },
      { name: "Kruskal's Algorithm", url: "https://takeuforward.org/data-structure/kruskals-algorithm-minimum-spanning-tree-g-47/" },
      { name: "Number of operations to make network connected", url: "https://takeuforward.org/data-structure/number-of-operations-to-make-network-connected-dsu-g-49/" },
      { name: "Most stones removed with same rows or columns", url: "https://takeuforward.org/data-structure/most-stones-removed-with-same-row-or-column-dsu-g-53/" },
      { name: "Accounts merge", url: "https://takeuforward.org/data-structure/accounts-merge-dsu-g-50/" },
      { name: "Number of island II", url: "https://takeuforward.org/graph/number-of-islands-ii-online-queries-dsu-g-51/" },
      { name: "Making a Large Island", url: "https://takeuforward.org/data-structure/making-a-large-island-dsu-g-52/" },
      { name: "Swim in rising water", url: "" },
    ],
  },
  {
    topic: "Graphs [Concepts & Problems] - Other Algorithms",
    icon: "🕸️",
    questions: [
      { name: "Bridges in Graph", url: "https://takeuforward.org/graph/bridges-in-graph-using-tarjans-algorithm-of-time-in-and-low-time-g-55/" },
      { name: "Articulation Point", url: "https://takeuforward.org/data-structure/articulation-point-in-graph-g-56/" },
      { name: "Kosaraju's Algorithm", url: "https://takeuforward.org/graph/strongly-connected-components-kosarajus-algorithm-g-54/" },
    ],
  },
  {
    topic: "Dynamic Programming [Patterns and Problems] - Introduction to DP",
    icon: "💡",
    questions: [
      { name: "Dynamic Programming Introduction", url: "https://takeuforward.org/data-structure/dynamic-programming-introduction/" },
    ],
  },
  {
    topic: "Dynamic Programming [Patterns and Problems] - 1D DP",
    icon: "💡",
    questions: [
      { name: "Climbing Stars", url: "https://takeuforward.org/data-structure/dynamic-programming-climbing-stairs/" },
      { name: "Frog Jump(DP-3)", url: "https://takeuforward.org/data-structure/dynamic-programming-frog-jump-dp-3/" },
      { name: "Frog Jump with k distances(DP-4)", url: "https://takeuforward.org/data-structure/dynamic-programming-frog-jump-with-k-distances-dp-4/" },
      { name: "Maximum sum of non-adjacent elements (DP 5)", url: "https://takeuforward.org/data-structure/maximum-sum-of-non-adjacent-elements-dp-5/" },
      { name: "House Robber (DP 6)", url: "https://takeuforward.org/data-structure/dynamic-programming-house-robber-dp-6/" },
    ],
  },
  {
    topic: "Dynamic Programming [Patterns and Problems] - 2D/3D DP and DP on Grids",
    icon: "💡",
    questions: [
      { name: "Ninja's Training (DP 7)", url: "https://takeuforward.org/data-structure/dynamic-programming-ninjas-training-dp-7/" },
      { name: "Grid Unique Paths : DP on Grids (DP8)", url: "https://takeuforward.org/data-structure/grid-unique-paths-dp-on-grids-dp8/" },
      { name: "Grid Unique Paths 2 (DP 9)", url: "https://takeuforward.org/data-structure/grid-unique-paths-2-dp-9/" },
      { name: "Minimum path sum in Grid (DP 10)", url: "https://takeuforward.org/data-structure/minimum-path-sum-in-a-grid-dp-10/" },
      { name: "Minimum path sum in Triangular Grid (DP 11)", url: "https://takeuforward.org/data-structure/minimum-path-sum-in-triangular-grid-dp-11/" },
      { name: "Minimum/Maximum Falling Path Sum (DP-12)", url: "https://takeuforward.org/data-structure/minimum-maximum-falling-path-sum-dp-12/" },
      { name: "3-d DP : Ninja and his friends (DP-13)", url: "https://takeuforward.org/data-structure/3-d-dp-ninja-and-his-friends-dp-13/" },
    ],
  },
  {
    topic: "Dynamic Programming [Patterns and Problems] - DP on Subsequences",
    icon: "💡",
    questions: [
      { name: "Subset sum equal to target (DP- 14)", url: "https://takeuforward.org/data-structure/subset-sum-equal-to-target-dp-14/" },
      { name: "Partition Equal Subset Sum (DP- 15)", url: "https://takeuforward.org/data-structure/partition-equal-subset-sum-dp-15/" },
      { name: "Partition Set Into 2 Subsets With Min Absolute Sum Diff (DP- 16)", url: "https://takeuforward.org/data-structure/partition-set-into-2-subsets-with-min-absolute-sum-diff-dp-16/" },
      { name: "Count Subsets with Sum K (DP - 17)", url: "https://takeuforward.org/data-structure/count-subsets-with-sum-k-dp-17/" },
      { name: "Count Partitions with Given Difference (DP - 18)", url: "https://takeuforward.org/data-structure/count-partitions-with-given-difference-dp-18/" },
      { name: "Assign Cookies", url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2" },
      { name: "Minimum Coins (DP - 20)", url: "https://takeuforward.org/data-structure/minimum-coins-dp-20/" },
      { name: "Target Sum (DP - 21)", url: "https://takeuforward.org/data-structure/target-sum-dp-21/" },
      { name: "Coin Change 2 (DP - 22)", url: "https://takeuforward.org/data-structure/coin-change-2-dp-22/" },
      { name: "Unbounded Knapsack (DP - 23)", url: "https://takeuforward.org/data-structure/unbounded-knapsack-dp-23/" },
      { name: "Rod Cutting Problem | (DP - 24)", url: "https://takeuforward.org/data-structure/rod-cutting-problem-dp-24/" },
    ],
  },
  {
    topic: "Dynamic Programming [Patterns and Problems] - DP on Strings",
    icon: "💡",
    questions: [
      { name: "Longest Common Subsequence | (DP - 25)", url: "https://takeuforward.org/data-structure/longest-common-subsequence-dp-25/" },
      { name: "Print Longest Common Subsequence | (DP - 26)", url: "https://takeuforward.org/data-structure/print-longest-common-subsequence-dp-26/" },
      { name: "Longest Common Substring | (DP - 27)", url: "https://takeuforward.org/data-structure/longest-common-substring-dp-27/" },
      { name: "Longest Palindromic Subsequence | (DP-28)", url: "https://takeuforward.org/data-structure/longest-palindromic-subsequence-dp-28/" },
      { name: "Minimum insertions to make string palindrome | DP-29", url: "https://takeuforward.org/data-structure/minimum-insertions-to-make-string-palindrome-dp-29/" },
      { name: "Minimum Insertions/Deletions to Convert String | (DP- 30)", url: "https://takeuforward.org/data-structure/minimum-insertions-deletions-to-convert-string-dp-30/" },
      { name: "Shortest Common Supersequence | (DP - 31)", url: "https://takeuforward.org/data-structure/shortest-common-supersequence-dp-31/" },
      { name: "Distinct Subsequences| (DP-32)", url: "https://takeuforward.org/data-structure/distinct-subsequences-dp-32/" },
      { name: "Edit Distance | (DP-33)", url: "https://takeuforward.org/data-structure/edit-distance-dp-33/" },
      { name: "Wildcard Matching | (DP-34)", url: "https://takeuforward.org/data-structure/wildcard-matching-dp-34/" },
    ],
  },
  {
    topic: "Dynamic Programming [Patterns and Problems] - DP on Stocks",
    icon: "💡",
    questions: [
      { name: "Best Time to Buy and Sell Stock |(DP-35)", url: "https://takeuforward.org/data-structure/stock-buy-and-sell-dp-35/" },
      { name: "Buy and Sell Stock - II|(DP-36)", url: "https://takeuforward.org/data-structure/buy-and-sell-stock-ii-dp-36/" },
      { name: "Buy and Sell Stocks III|(DP-37)", url: "https://takeuforward.org/data-structure/buy-and-sell-stock-iii-dp-37/" },
      { name: "Buy and Stock Sell IV |(DP-38)", url: "https://takeuforward.org/data-structure/buy-and-sell-stock-iv-dp-38/" },
      { name: "Buy and Sell Stocks With Cooldown|(DP-39)", url: "https://takeuforward.org/data-structure/buy-and-sell-stocks-with-cooldown-dp-39/" },
      { name: "Buy and Sell Stocks With Transaction Fee|(DP-40)", url: "https://takeuforward.org/data-structure/buy-and-sell-stocks-with-transaction-fees-dp-40/" },
    ],
  },
  {
    topic: "Dynamic Programming [Patterns and Problems] - DP on LIS",
    icon: "💡",
    questions: [
      { name: "Longest Increasing Subsequence |(DP-41)", url: "https://takeuforward.org/data-structure/longest-increasing-subsequence-dp-41/" },
      { name: "Printing Longest Increasing Subsequence|(DP-42)", url: "https://takeuforward.org/data-structure/printing-longest-increasing-subsequence-dp-42/" },
      { name: "Longest Increasing Subsequence |(DP-43)", url: "https://takeuforward.org/data-structure/longest-increasing-subsequence-binary-search-dp-43/" },
      { name: "Largest Divisible Subset|(DP-44)", url: "https://takeuforward.org/data-structure/longest-divisible-subset-dp-44/" },
      { name: "Longest String Chain|(DP-45)", url: "https://takeuforward.org/data-structure/longest-string-chain-dp-45/" },
      { name: "Longest Bitonic Subsequence |(DP-46)", url: "https://takeuforward.org/data-structure/longest-bitonic-subsequence-dp-46/" },
      { name: "Number of Longest Increasing Subsequences|(DP-47)", url: "https://takeuforward.org/data-structure/number-of-longest-increasing-subsequences-dp-47/" },
    ],
  },
  {
    topic: "Dynamic Programming [Patterns and Problems] - MCM DP | Partition DP",
    icon: "💡",
    questions: [
      { name: "Matrix Chain Multiplication|(DP-48)", url: "https://takeuforward.org/dynamic-programming/matrix-chain-multiplication-dp-48/" },
      { name: "Matrix Chain Multiplication | Bottom-Up|(DP-49)", url: "https://takeuforward.org/data-structure/matrix-chain-multiplication-tabulation-method-dp-49/" },
      { name: "Minimum Cost to Cut the Stick|(DP-50)", url: "https://takeuforward.org/data-structure/minimum-cost-to-cut-the-stick-dp-50/" },
      { name: "Burst Balloons|(DP-51)", url: "https://takeuforward.org/data-structure/burst-balloons-partition-dp-dp-51/" },
      { name: "Evaluate Boolean Expression to True|(DP-52)", url: "https://takeuforward.org/data-structure/evaluate-boolean-expression-to-true-partition-dp-dp-52/" },
      { name: "Palindrome Partitioning - II|(DP-53)", url: "https://takeuforward.org/data-structure/palindrome-partitioning-ii-front-partition-dp-53/" },
      { name: "Partition Array for Maximum Sum|(DP-54)", url: "https://takeuforward.org/data-structure/partition-array-for-maximum-sum-front-partition-dp-54/" },
    ],
  },
  {
    topic: "Dynamic Programming [Patterns and Problems] - DP on Squares",
    icon: "💡",
    questions: [
      { name: "Maximum Rectangle Area with all 1's|(DP-55)", url: "https://takeuforward.org/data-structure/maximum-rectangle-area-with-all-1s-dp-on-rectangles-dp-55/" },
      { name: "Count Square Submatrices with All Ones|(DP-56)", url: "https://takeuforward.org/data-structure/count-square-submatrices-with-all-1s-dp-on-rectangles-dp-56/" },
    ],
  },
  {
    topic: "Tries - Theory",
    icon: "🔤",
    questions: [
      { name: "Implement TRIE | INSERT | SEARCH | STARTSWITH", url: "https://takeuforward.org/data-structure/implement-trie-1/" },
    ],
  },
  {
    topic: "Tries - Problems",
    icon: "🔤",
    questions: [
      { name: "Implement Trie - 2 (Prefix Tree)", url: "https://takeuforward.org/data-structure/implement-trie-ii/" },
      { name: "Longest String with All Prefixes", url: "" },
      { name: "Number of Distinct Substrings in a String", url: "https://takeuforward.org/data-structure/number-of-distinct-substrings-in-a-string-using-trie/" },
      { name: "Bit PreRequisites for TRIE Problems", url: "" },
      { name: "Maximum XOR of two numbers in an array", url: "https://takeuforward.org/data-structure/maximum-xor-of-two-numbers-in-an-array/" },
      { name: "Maximum XOR With an Element From Array", url: "https://takeuforward.org/trie/maximum-xor-queries-trie/" },
    ],
  },
  {
    topic: "Strings - Hard Problems",
    icon: "📝",
    questions: [
      { name: "Minimum number of bracket reversals needed to make an expression balanced", url: "" },
      { name: "Count and say", url: "" },
      { name: "Hashing In Strings | Theory", url: "" },
      { name: "Rabin Karp", url: "" },
      { name: "Z-Function", url: "" },
      { name: "KMP algo / LPS(pi) array", url: "" },
      { name: "Shortest Palindrome", url: "" },
      { name: "Longest happy prefix", url: "" },
      { name: "Count palindromic subsequence in given string", url: "" },
    ],
  },
];