const STRIVER_SDE_DATA = [
  {
    topic: "Arrays I",
    icon: "📊",
    questions: [
      { name: "Set Matrix Zeros", url: "https://leetcode.com/problems/set-matrix-zeroes/", gfgUrl: "https://www.geeksforgeeks.org/problems/set-matrix-zeroes/1" },
      { name: "Pascal's Triangle", url: "https://leetcode.com/problems/pascals-triangle/", gfgUrl: "https://www.geeksforgeeks.org/problems/pascal-triangle0652/1" },
      { name: "Next Permutation", url: "https://leetcode.com/problems/next-permutation/", gfgUrl: "https://www.geeksforgeeks.org/problems/next-permutation5226/1" },
      { name: "Kadane's Algorithm", url: "https://leetcode.com/problems/maximum-subarray/", gfgUrl: "https://www.geeksforgeeks.org/problems/kadanes-algorithm-1587115620/1" },
      { name: "Sort an array of 0's, 1's and 2's", url: "https://leetcode.com/problems/sort-colors/", gfgUrl: "https://www.geeksforgeeks.org/problems/sort-an-array-of-0s-1s-and-2s4231/1" },
      { name: "Stock Buy and Sell", url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", gfgUrl: "https://www.geeksforgeeks.org/problems/buy-stock-2/1" },
    ],
  },
  {
    topic: "Arrays II",
    icon: "📊",
    questions: [
      { name: "Rotate Matrix", url: "https://leetcode.com/problems/rotate-image/", gfgUrl: "https://www.geeksforgeeks.org/problems/rotate-by-90-degree0356/1" },
      { name: "Merge Overlapping Subintervals", url: "https://leetcode.com/problems/merge-intervals/", gfgUrl: "https://www.geeksforgeeks.org/problems/overlapping-intervals--170633/1" },
      { name: "Merge two sorted arrays without extra space", url: "https://leetcode.com/problems/merge-sorted-array/", gfgUrl: "https://www.geeksforgeeks.org/problems/merge-two-sorted-arrays-1587115620/1" },
      { name: "Find the duplicate in an array of N+1 integers", url: "https://leetcode.com/problems/find-the-duplicate-number/", gfgUrl: "https://www.geeksforgeeks.org/problems/find-the-duplicate-number/1" },
      { name: "Repeat and Missing Number", url: "https://takeuforward.org/data-structure/find-the-repeating-and-missing-numbers/", gfgUrl: "https://www.geeksforgeeks.org/problems/find-missing-and-repeating2512/1" },
      { name: "Inversion of Array (Pre-req: Merge Sort)", url: "https://takeuforward.org/data-structure/count-inversions-in-an-array/", gfgUrl: "https://www.geeksforgeeks.org/problems/inversion-of-array-1587115620/1" },
    ],
  },
  {
    topic: "Arrays III",
    icon: "📊",
    questions: [
      { name: "Search in a 2 D matrix", url: "https://leetcode.com/problems/search-a-2d-matrix/", gfgUrl: "https://www.geeksforgeeks.org/problems/search-in-a-matrix17201720/1" },
      { name: "Pow(x, n)", url: "https://leetcode.com/problems/powx-n/" },
      { name: "Majority Element (>n/2 times)", url: "https://leetcode.com/problems/majority-element/", gfgUrl: "https://www.geeksforgeeks.org/problems/majority-element-1587115620/1" },
      { name: "Majority Element (n/3 times)", url: "https://leetcode.com/problems/majority-element-ii/", gfgUrl: "https://www.geeksforgeeks.org/problems/majority-vote/1" },
      { name: "Grid Unique Paths", url: "https://leetcode.com/problems/unique-paths/", gfgUrl: "https://www.geeksforgeeks.org/problems/number-of-unique-paths5339/1" },
      { name: "Reverse Pairs (Leetcode)", url: "https://leetcode.com/problems/reverse-pairs/" },
    ],
  },
  {
    topic: "Arrays IV",
    icon: "📊",
    questions: [
      { name: "2Sum Problem", url: "https://leetcode.com/problems/two-sum/", gfgUrl: "https://www.geeksforgeeks.org/problems/key-pair5616/1" },
      { name: "4-Sum Problem", url: "https://leetcode.com/problems/4sum/", gfgUrl: "https://www.geeksforgeeks.org/problems/find-all-four-sum-numbers1702/1" },
      { name: "Longest Consecutive Sequence", url: "https://leetcode.com/problems/longest-consecutive-sequence/", gfgUrl: "https://www.geeksforgeeks.org/problems/longest-consecutive-subsequence2449/1" },
      { name: "Largest Subarray with K sum", url: "https://takeuforward.org/data-structure/length-of-the-longest-subarray-with-zero-sum/", gfgUrl: "https://www.geeksforgeeks.org/problems/largest-subarray-with-0-sum/1" },
      { name: "Count number of subarrays with given xor K", url: "https://takeuforward.org/data-structure/count-the-number-of-subarrays-with-given-xor-k/" },
      { name: "Longest Substring without repeat", url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/", gfgUrl: "https://www.geeksforgeeks.org/problems/length-of-the-longest-substring3036/1" },
    ],
  },
  {
    topic: "Linked List I",
    icon: "🔗",
    questions: [
      { name: "Reverse a LinkedList", url: "https://leetcode.com/problems/reverse-linked-list/", gfgUrl: "https://www.geeksforgeeks.org/problems/reverse-a-linked-list/1" },
      { name: "Find the middle of LinkedList", url: "https://leetcode.com/problems/middle-of-the-linked-list/", gfgUrl: "https://www.geeksforgeeks.org/problems/finding-middle-element-in-a-linked-list/1" },
      { name: "Merge two sorted Linked List (use method used in mergeSort)", url: "https://leetcode.com/problems/merge-two-sorted-lists/", gfgUrl: "https://www.geeksforgeeks.org/problems/merge-two-sorted-linked-lists/1" },
      { name: "Remove N-th node from back of LinkedList", url: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/", gfgUrl: "https://www.geeksforgeeks.org/problems/nth-node-from-end-of-linked-list/1" },
      { name: "Add two numbers as LinkedList", url: "https://leetcode.com/problems/add-two-numbers/", gfgUrl: "https://www.geeksforgeeks.org/problems/add-two-numbers-represented-by-linked-lists/1" },
      { name: "Delete a given Node when a node is given.(0(1) solution)", url: "https://leetcode.com/problems/delete-node-in-a-linked-list/", gfgUrl: "https://www.geeksforgeeks.org/problems/delete-a-node-in-single-linked-list/1" },
    ],
  },
  {
    topic: "Linked List II",
    icon: "🔗",
    questions: [
      { name: "Find intersection point of Y LinkedList", url: "https://leetcode.com/problems/intersection-of-two-linked-lists/", gfgUrl: "https://www.geeksforgeeks.org/problems/intersection-point-in-y-shapped-linked-lists/1" },
      { name: "Detect a cycle in Linked List", url: "https://leetcode.com/problems/linked-list-cycle/", gfgUrl: "https://www.geeksforgeeks.org/problems/detect-loop-in-linked-list/1" },
      { name: "Reverse a LinkedList in groups of size k.", url: "https://leetcode.com/problems/reverse-nodes-in-k-group/", gfgUrl: "https://www.geeksforgeeks.org/problems/reverse-a-linked-list-in-groups-of-given-size/1" },
      { name: "Check if a LinkedList is palindrome or not.", url: "https://leetcode.com/problems/palindrome-linked-list/", gfgUrl: "https://www.geeksforgeeks.org/problems/check-if-linked-list-is-pallindrome/1" },
      { name: "Find the starting point of the Loop of LinkedList", url: "https://leetcode.com/problems/linked-list-cycle-ii/", gfgUrl: "https://www.geeksforgeeks.org/problems/find-the-first-node-of-loop-in-linked-list--170645/1" },
      { name: "Flattening of a LinkedList", url: "https://takeuforward.org/data-structure/flattening-a-linked-list/", gfgUrl: "https://www.geeksforgeeks.org/problems/flattening-a-linked-list/1" },
    ],
  },
  {
    topic: "Linked List & Arrays",
    icon: "🔗",
    questions: [
      { name: "Rotate a LinkedList", url: "https://leetcode.com/problems/rotate-list/description/", gfgUrl: "https://www.geeksforgeeks.org/problems/rotate-a-linked-list/1" },
      { name: "Clone a Linked List with random and next pointer", url: "https://leetcode.com/problems/copy-list-with-random-pointer/", gfgUrl: "https://www.geeksforgeeks.org/problems/clone-a-linked-list-with-next-and-random-pointer/1" },
      { name: "3 sum", url: "https://leetcode.com/problems/3sum/", gfgUrl: "https://www.geeksforgeeks.org/problems/triplet-sum-in-array-1587115621/1" },
      { name: "Trapping Rainwater", url: "https://leetcode.com/problems/trapping-rain-water/", gfgUrl: "https://www.geeksforgeeks.org/problems/trapping-rain-water-1587115621/1" },
      { name: "Remove Duplicate from Sorted array", url: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/", gfgUrl: "https://www.geeksforgeeks.org/problems/remove-duplicate-elements-from-sorted-array/1" },
      { name: "Max consecutive ones", url: "https://leetcode.com/problems/max-consecutive-ones/", gfgUrl: "https://www.geeksforgeeks.org/problems/max-consecutive-ones/1" },
    ],
  },
  {
    topic: "Greedy",
    icon: "💰",
    questions: [
      { name: "N meetings in one room", url: "https://takeuforward.org/data-structure/n-meetings-in-one-room/", gfgUrl: "https://www.geeksforgeeks.org/problems/n-meetings-in-one-room-1587115620/1" },
      { name: "Minimum number of platforms required for a railway", url: "https://takeuforward.org/data-structure/minimum-number-of-platforms-required-for-a-railway/", gfgUrl: "https://www.geeksforgeeks.org/problems/minimum-platforms-1587115620/1" },
      { name: "Job sequencing Problem", url: "https://takeuforward.org/data-structure/job-sequencing-problem/", gfgUrl: "https://www.geeksforgeeks.org/problems/job-sequencing-problem-1587115620/1" },
      { name: "Fractional Knapsack Problem", url: "https://takeuforward.org/data-structure/fractional-knapsack-problem-greedy-approach/", gfgUrl: "https://www.geeksforgeeks.org/problems/fractional-knapsack-1587115620/1" },
      { name: "Greedy algorithm to find minimum number of coins", url: "https://takeuforward.org/data-structure/find-minimum-number-of-coins/" },
      { name: "Assign Cookies", url: "https://leetcode.com/problems/assign-cookies/", gfgUrl: "https://www.geeksforgeeks.org/problems/assign-cookies/1" },
    ],
  },
  {
    topic: "Recursion",
    icon: "🔄",
    questions: [
      { name: "Subset Sums", url: "https://takeuforward.org/data-structure/subset-sum-sum-of-all-subsets/", gfgUrl: "https://www.geeksforgeeks.org/problems/subset-sums2234/1" },
      { name: "Subset-II", url: "https://leetcode.com/problems/subsets-ii/" },
      { name: "Combination sum-1", url: "https://leetcode.com/problems/combination-sum/", gfgUrl: "https://www.geeksforgeeks.org/problems/combination-sum-1587115620/1" },
      { name: "Combination sum-2", url: "https://leetcode.com/problems/combination-sum-ii/" },
      { name: "Palindrome Partitioning", url: "https://leetcode.com/problems/palindrome-partitioning/" },
      { name: "K-th permutation Sequence", url: "https://leetcode.com/problems/permutation-sequence/" },
    ],
  },
  {
    topic: "Backtracking",
    icon: "🔄",
    questions: [
      { name: "Print all permutations of a string/array", url: "https://leetcode.com/problems/permutations/" },
      { name: "N queens Problem", url: "https://leetcode.com/problems/n-queens/", gfgUrl: "https://www.geeksforgeeks.org/problems/n-queen-problem0315/1" },
      { name: "Sudoko Solver", url: "https://leetcode.com/problems/sudoku-solver/", gfgUrl: "https://www.geeksforgeeks.org/problems/solve-the-sudoku-1587115621/1" },
      { name: "M Coloring Problem", url: "https://takeuforward.org/data-structure/m-coloring-problem/", gfgUrl: "https://www.geeksforgeeks.org/problems/m-coloring-problem-1587115620/1" },
      { name: "Rat in a Maze", url: "https://takeuforward.org/data-structure/rat-in-a-maze/", gfgUrl: "https://www.geeksforgeeks.org/problems/rat-in-a-maze-problem/1" },
      { name: "Word Break (print all ways)", url: "" },
    ],
  },
  {
    topic: "Binary Search",
    icon: "🔍",
    questions: [
      { name: "The N-th root of an integer", url: "https://takeuforward.org/data-structure/nth-root-of-a-number-using-binary-search/" },
      { name: "Matrix Median", url: "https://takeuforward.org/data-structure/median-of-row-wise-sorted-matrix/", gfgUrl: "https://www.geeksforgeeks.org/problems/median-in-a-row-wise-sorted-matrix1527/1" },
      { name: "Find the element that appears once in a sorted array, and the rest element appears twice (Binary search)", url: "https://leetcode.com/problems/single-element-in-a-sorted-array/" },
      { name: "Search element in a sorted and rotated array/ find pivot where it is rotated", url: "https://leetcode.com/problems/search-in-rotated-sorted-array/", gfgUrl: "https://www.geeksforgeeks.org/problems/search-in-a-rotated-array4618/1" },
      { name: "Median of 2 sorted arrays", url: "https://leetcode.com/problems/median-of-two-sorted-arrays/", gfgUrl: "https://www.geeksforgeeks.org/problems/median-of-2-sorted-arrays-of-different-sizes/1" },
      { name: "K-th element of two sorted arrays", url: "https://takeuforward.org/data-structure/k-th-element-of-two-sorted-arrays/", gfgUrl: "https://www.geeksforgeeks.org/problems/k-th-element-of-two-sorted-array1317/1" },
      { name: "Allocate Minimum Number of Pages", url: "https://takeuforward.org/data-structure/allocate-minimum-number-of-pages/", gfgUrl: "https://www.geeksforgeeks.org/problems/allocate-minimum-number-of-pages0937/1" },
      { name: "Aggressive Cows", url: "https://takeuforward.org/data-structure/aggressive-cows-detailed-solution/", gfgUrl: "https://www.geeksforgeeks.org/problems/aggressive-cows/0" },
    ],
  },
  {
    topic: "Heaps",
    icon: "⚙️",
    questions: [
      { name: "Max heap, Min Heap Implementation (Only for interviews)", url: "" },
      { name: "Kth Largest Element", url: "https://leetcode.com/problems/kth-largest-element-in-an-array/", gfgUrl: "https://www.geeksforgeeks.org/problems/kth-smallest-element5635/1" },
      { name: "Maximum Sum Combination", url: "" },
      { name: "Find Median from Data Stream", url: "https://leetcode.com/problems/find-median-from-data-stream/", gfgUrl: "https://www.geeksforgeeks.org/problems/find-median-in-a-stream-1587115620/1" },
      { name: "Merge K sorted arrays", url: "" },
      { name: "K most frequent elements", url: "https://leetcode.com/problems/top-k-frequent-elements/", gfgUrl: "https://www.geeksforgeeks.org/problems/top-k-frequent-elements-in-array/1" },
    ],
  },
  {
    topic: "Stack & Queue I",
    icon: "📚",
    questions: [
      { name: "Implement Stack using Arrays", url: "https://takeuforward.org/data-structure/implement-stack-using-array/", gfgUrl: "https://www.geeksforgeeks.org/problems/implement-stack-using-array/1" },
      { name: "Implement Queue using Arrays", url: "https://takeuforward.org/data-structure/implement-queue-using-array/", gfgUrl: "https://www.geeksforgeeks.org/problems/implement-queue-using-array/1" },
      { name: "Implement Stack using Queue (using single queue)", url: "https://leetcode.com/problems/implement-stack-using-queues/", gfgUrl: "https://www.geeksforgeeks.org/problems/stack-using-two-queues/1" },
      { name: "Implement Queue using Stack (0(1) amortized method)", url: "https://leetcode.com/problems/implement-queue-using-stacks/", gfgUrl: "https://www.geeksforgeeks.org/problems/queue-using-two-stacks/1" },
      { name: "Check for balanced parentheses", url: "https://leetcode.com/problems/valid-parentheses/", gfgUrl: "https://www.geeksforgeeks.org/problems/parenthesis-checker2744/1" },
      { name: "Next Greater Element", url: "https://leetcode.com/problems/next-greater-element-i/", gfgUrl: "https://www.geeksforgeeks.org/problems/next-larger-element-1587115620/1" },
      { name: "Sort a Stack", url: "" },
    ],
  },
  {
    topic: "Stack & Queue II",
    icon: "📚",
    questions: [
      { name: "Next Smaller Element", url: "" },
      { name: "LRU cache (IMPORTANT)", url: "https://leetcode.com/problems/lru-cache/", gfgUrl: "https://www.geeksforgeeks.org/problems/lru-cache/1" },
      { name: "LFU cache", url: "https://leetcode.com/problems/lfu-cache/" },
      { name: "Largest rectangle in a histogram", url: "https://leetcode.com/problems/largest-rectangle-in-histogram/", gfgUrl: "https://www.geeksforgeeks.org/problems/maximum-rectangular-area-in-a-histogram-1587115620/1" },
      { name: "Sliding Window maximum", url: "https://leetcode.com/problems/sliding-window-maximum/" },
      { name: "Implement Min Stack", url: "https://leetcode.com/problems/min-stack/" },
      { name: "Rotten Orange (Using BFS)", url: "https://leetcode.com/problems/rotting-oranges/", gfgUrl: "https://www.geeksforgeeks.org/problems/rotten-oranges2536/1" },
      { name: "Stock span problem", url: "https://leetcode.com/problems/online-stock-span/", gfgUrl: "https://www.geeksforgeeks.org/problems/stock-span-problem-1587115621/1" },
      { name: "Find the maximum of minimums of every window size", url: "" },
      { name: "The Celebrity Problem", url: "https://takeuforward.org/interviews/strivers-sde-sheet-top-coding-interview-problems/", gfgUrl: "https://www.geeksforgeeks.org/problems/the-celebrity-problem/1" },
    ],
  },
  {
    topic: "String I",
    icon: "📝",
    questions: [
      { name: "Reverse Words in a String", url: "https://leetcode.com/problems/reverse-words-in-a-string/", gfgUrl: "https://www.geeksforgeeks.org/problems/reverse-words-in-a-given-string5459/1" },
      { name: "Longest Palindrome in a string", url: "https://leetcode.com/problems/longest-palindromic-substring/", gfgUrl: "https://www.geeksforgeeks.org/problems/longest-palindrome-in-a-string3411/1" },
      { name: "Roman Number to Integer and vice versa", url: "https://leetcode.com/problems/roman-to-integer/", gfgUrl: "https://www.geeksforgeeks.org/problems/roman-number-to-integer3201/1" },
      { name: "Implement ATOI/STRSTR", url: "https://leetcode.com/problems/string-to-integer-atoi/" },
      { name: "Longest Common Prefix", url: "https://leetcode.com/problems/longest-common-prefix/", gfgUrl: "https://www.geeksforgeeks.org/problems/longest-common-prefix-in-an-array5129/1" },
      { name: "Rabin Karp", url: "https://leetcode.com/problems/repeated-string-match/discuss/416144/Rabin-Karp-algorithm-C%2B%2B-implementation" },
    ],
  },
  {
    topic: "String II",
    icon: "📝",
    questions: [
      { name: "Z-Function", url: "https://leetcode.com/problems/implement-strstr/" },
      { name: "KMP algo / LPS(pi) array", url: "https://leetcode.com/problems/implement-strstr/" },
      { name: "Minimum characters needed to be inserted in the beginning to make it palindromic", url: "" },
      { name: "Check for Anagrams", url: "https://leetcode.com/problems/valid-anagram/", gfgUrl: "https://www.geeksforgeeks.org/problems/anagram-1587115620/1" },
      { name: "Count and say", url: "https://leetcode.com/problems/count-and-say/" },
      { name: "Compare version numbers", url: "https://leetcode.com/problems/compare-version-numbers/" },
    ],
  },
  {
    topic: "Binary Tree I",
    icon: "🌳",
    questions: [
      { name: "Inorder Traversal", url: "https://leetcode.com/problems/binary-tree-inorder-traversal/", gfgUrl: "https://www.geeksforgeeks.org/problems/inorder-traversal/1" },
      { name: "Preorder Traversal", url: "https://leetcode.com/problems/binary-tree-preorder-traversal/", gfgUrl: "https://www.geeksforgeeks.org/problems/preorder-traversal/1" },
      { name: "Postorder Traversal", url: "https://leetcode.com/problems/binary-tree-postorder-traversal/", gfgUrl: "https://www.geeksforgeeks.org/problems/postorder-traversal/1" },
      { name: "Morris Inorder Traversal", url: "https://leetcode.com/problems/binary-tree-inorder-traversal/" },
      { name: "Morris Preorder Traversal", url: "https://takeuforward.org/data-structure/morris-preorder-traversal-of-a-binary-tree/", lcUrl: "https://leetcode.com/problems/binary-tree-preorder-traversal/" },
      { name: "LeftView Of Binary Tree", url: "https://takeuforward.org/data-structure/right-left-view-of-binary-tree/", gfgUrl: "https://www.geeksforgeeks.org/problems/left-view-of-binary-tree/1" },
      { name: "Bottom View of Binary Tree", url: "https://takeuforward.org/data-structure/bottom-view-of-a-binary-tree/", gfgUrl: "https://www.geeksforgeeks.org/problems/bottom-view-of-binary-tree/1" },
      { name: "Top View of Binary Tree", url: "https://takeuforward.org/data-structure/top-view-of-a-binary-tree/", gfgUrl: "https://www.geeksforgeeks.org/problems/top-view-of-binary-tree/1" },
      { name: "Preorder inorder postorder in a single traversal", url: "https://takeuforward.org/data-structure/preorder-inorder-postorder-traversals-in-one-traversal/" },
      { name: "Vertical order traversal", url: "https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/" },
      { name: "Root to Node Path in Binary Tree", url: "https://takeuforward.org/data-structure/print-root-to-node-path-in-a-binary-tree/" },
      { name: "Max width of a Binary Tree", url: "https://leetcode.com/problems/maximum-width-of-binary-tree/", gfgUrl: "https://www.geeksforgeeks.org/problems/maximum-width-of-tree/1" },
    ],
  },
  {
    topic: "Binary Tree II",
    icon: "🌳",
    questions: [
      { name: "Level order Traversal / Level order traversal in spiral form", url: "https://leetcode.com/problems/binary-tree-level-order-traversal/", gfgUrl: "https://www.geeksforgeeks.org/problems/level-order-traversal/1" },
      { name: "Height of a Binary Tree", url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/", gfgUrl: "https://www.geeksforgeeks.org/problems/height-of-binary-tree/1" },
      { name: "Diameter of Binary Tree", url: "https://leetcode.com/problems/diameter-of-binary-tree/", gfgUrl: "https://www.geeksforgeeks.org/problems/diameter-of-binary-tree/1" },
      { name: "Check if the Binary tree is height-balanced or not", url: "https://leetcode.com/problems/balanced-binary-tree/", gfgUrl: "https://www.geeksforgeeks.org/problems/check-for-balanced-tree/1" },
      { name: "LCA in Binary Tree", url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/", gfgUrl: "https://www.geeksforgeeks.org/problems/lowest-common-ancestor-in-a-binary-tree/1" },
      { name: "Check if two trees are identical or not", url: "https://leetcode.com/problems/same-tree/", gfgUrl: "https://www.geeksforgeeks.org/problems/determine-if-two-trees-are-identical/1" },
      { name: "Zig Zag Traversal of Binary Tree", url: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/", gfgUrl: "https://www.geeksforgeeks.org/problems/zigzag-tree-traversal/1" },
      { name: "Boundary Traversal of Binary Tree", url: "https://leetcode.com/problems/boundary-of-binary-tree/", gfgUrl: "https://www.geeksforgeeks.org/problems/boundary-traversal-of-binary-tree/1" },
    ],
  },
  {
    topic: "Binary Tree III",
    icon: "🌳",
    questions: [
      { name: "Maximum path sum", url: "https://leetcode.com/problems/binary-tree-maximum-path-sum/", gfgUrl: "https://www.geeksforgeeks.org/problems/maximum-path-sum-from-any-node/1" },
      { name: "Construct Binary Tree from inorder and preorder", url: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/", gfgUrl: "https://www.geeksforgeeks.org/problems/construct-tree-1/1" },
      { name: "Construct Binary Tree from Inorder and Postorder", url: "https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/" },
      { name: "Symmetric Binary Tree", url: "https://leetcode.com/problems/symmetric-tree/", gfgUrl: "https://www.geeksforgeeks.org/problems/symmetric-tree/1" },
      { name: "Flatten Binary Tree to LinkedList", url: "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/" },
      { name: "Check if Binary Tree is the mirror of itself or not", url: "" },
      { name: "Check for Children Sum Property", url: "https://takeuforward.org/data-structure/check-for-children-sum-property-in-a-binary-tree/", gfgUrl: "https://www.geeksforgeeks.org/problems/children-sum-parent/1" },
    ],
  },
  {
    topic: "BST I",
    icon: "🌲",
    questions: [
      { name: "Populate Next Right pointers of Tree", url: "https://leetcode.com/problems/populating-next-right-pointers-in-each-node/" },
      { name: "Search given Key in BST", url: "https://leetcode.com/problems/search-in-a-binary-search-tree/" },
      { name: "Construct BST from given keys", url: "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/" },
      { name: "Construct a BST from a preorder traversal", url: "https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/" },
      { name: "Check is a BT is BST or not", url: "https://leetcode.com/problems/validate-binary-search-tree/", gfgUrl: "https://www.geeksforgeeks.org/problems/check-for-bst/1" },
      { name: "Find LCA of two nodes in BST", url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/", gfgUrl: "https://www.geeksforgeeks.org/problems/lowest-common-ancestor-in-a-bst/1" },
      { name: "Find the inorder predecessor/successor of a given Key in BST.", url: "" },
    ],
  },
  {
    topic: "BST II",
    icon: "🌲",
    questions: [
      { name: "Floor in a BST", url: "" },
      { name: "Ceil in a BST", url: "" },
      { name: "Find K-th smallest element in BST", url: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/" },
      { name: "Find K-th largest element in BST", url: "https://takeuforward.org/data-structure/kth-largest-smallest-element-in-binary-search-tree/", lcUrl: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/" },
      { name: "Find a pair with a given sum in BST", url: "https://leetcode.com/problems/two-sum-iv-input-is-a-bst/" },
      { name: "BST iterator", url: "https://leetcode.com/problems/binary-search-tree-iterator/" },
      { name: "Size of the largest BST in a Binary Tree", url: "https://leetcode.com/problems/maximum-sum-bst-in-binary-tree/", gfgUrl: "https://www.geeksforgeeks.org/problems/largest-bst/1" },
      { name: "Serialize and deserialize Binary Tree", url: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/", gfgUrl: "https://www.geeksforgeeks.org/problems/serialize-and-deserialize-a-binary-tree/1" },
    ],
  },
  {
    topic: "Mixed Problems",
    icon: "🎲",
    questions: [
      { name: "Binary Tree to Double Linked List", url: "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/", gfgUrl: "https://www.geeksforgeeks.org/problems/binary-tree-to-dll/1" },
      { name: "Find median in a stream of running integers.", url: "https://leetcode.com/problems/find-median-from-data-stream/", gfgUrl: "https://www.geeksforgeeks.org/problems/find-median-in-a-stream-1587115620/1" },
      { name: "K-th largest element in a stream.", url: "https://leetcode.com/problems/kth-largest-element-in-a-stream/" },
      { name: "Distinct numbers in Window.", url: "" },
      { name: "K-th largest element in an unsorted array.", url: "https://leetcode.com/problems/kth-largest-element-in-an-array/" },
      { name: "Flood-fill Algorithm", url: "https://leetcode.com/problems/flood-fill/", gfgUrl: "https://www.geeksforgeeks.org/problems/flood-fill-algorithm1856/1" },
    ],
  },
  {
    topic: "Graph I",
    icon: "🕸️",
    questions: [
      { name: "Clone a graph (Not that easy as it looks)", url: "https://leetcode.com/problems/clone-graph/" },
      { name: "DFS", url: "https://takeuforward.org/data-structure/depth-first-search-dfs/", gfgUrl: "https://www.geeksforgeeks.org/problems/depth-first-traversal-for-a-graph/1" },
      { name: "BFS", url: "https://takeuforward.org/graph/breadth-first-search-bfs-level-order-traversal/", gfgUrl: "https://www.geeksforgeeks.org/problems/bfs-traversal-of-graph/1" },
      { name: "Detect A cycle in Undirected Graph using BFS", url: "https://leetcode.com/problems/course-schedule/" },
      { name: "Detect A cycle in Undirected Graph using DFS", url: "https://leetcode.com/problems/course-schedule/" },
      { name: "Detect A cycle in a Directed Graph using DFS", url: "https://leetcode.com/problems/course-schedule/" },
      { name: "Detect A cycle in a Directed Graph using BFS", url: "https://leetcode.com/problems/course-schedule/" },
      { name: "Topological Sort BFS", url: "https://takeuforward.org/data-structure/topological-sort-bfs/", gfgUrl: "https://www.geeksforgeeks.org/problems/topological-sort/1" },
      { name: "Topological Sort DFS", url: "https://takeuforward.org/data-structure/topological-sort-using-dfs/", gfgUrl: "https://www.geeksforgeeks.org/problems/topological-sort/1" },
      { name: "Number of islands(Do in Grid and Graph Both)", url: "https://leetcode.com/problems/number-of-islands/", gfgUrl: "https://www.geeksforgeeks.org/problems/find-the-number-of-islands/1" },
      { name: "Bipartite Check using BFS", url: "https://leetcode.com/problems/is-graph-bipartite/", gfgUrl: "https://www.geeksforgeeks.org/problems/bipartite-graph/1" },
      { name: "Bipartite Check using DFS", url: "https://leetcode.com/problems/is-graph-bipartite/", gfgUrl: "https://www.geeksforgeeks.org/problems/bipartite-graph/1" },
    ],
  },
  {
    topic: "Graph II",
    icon: "🕸️",
    questions: [
      { name: "Strongly Connected Component(using KosaRajuΓÇÖs algo)", url: "https://leetcode.com/problems/maximum-number-of-non-overlapping-substrings/discuss/766485/kosaraju-algorithm-on", gfgUrl: "https://www.geeksforgeeks.org/problems/strongly-connected-components-kosarajus-algo/1" },
      { name: "DijkstraΓÇÖs Algorithm", url: "https://takeuforward.org/data-structure/g-35-print-shortest-path-dijkstras-algorithm/", gfgUrl: "https://www.geeksforgeeks.org/problems/implementing-dijkstra-set-1-adjacency-matrix/1" },
      { name: "Bellman-Ford Algo", url: "https://takeuforward.org/data-structure/bellman-ford-algorithm-g-41/", gfgUrl: "https://www.geeksforgeeks.org/problems/distance-from-the-source-bellman-ford-algorithm/1" },
      { name: "Floyd Warshall Algorithm", url: "https://takeuforward.org/data-structure/floyd-warshall-algorithm-g-42/", gfgUrl: "https://www.geeksforgeeks.org/problems/implementing-floyd-warshall2042/1" },
      { name: "MST using Prim's Algo", url: "https://takeuforward.org/data-structure/prims-algorithm-minimum-spanning-tree-c-and-java-g-45/", gfgUrl: "https://www.geeksforgeeks.org/problems/minimum-spanning-tree/1" },
      { name: "MST using KruskalΓÇÖs Algo", url: "https://takeuforward.org/data-structure/kruskals-algorithm-minimum-spanning-tree-g-47/", gfgUrl: "https://www.geeksforgeeks.org/problems/minimum-spanning-tree/1" },
    ],
  },
  {
    topic: "DP I",
    icon: "💡",
    questions: [
      { name: "Max Product Subarray", url: "https://leetcode.com/problems/maximum-product-subarray/", gfgUrl: "https://www.geeksforgeeks.org/problems/maximum-product-subarray3604/1" },
      { name: "Longest Increasing Subsequence", url: "https://leetcode.com/problems/longest-increasing-subsequence/", gfgUrl: "https://www.geeksforgeeks.org/problems/longest-increasing-subsequence-1587115620/1" },
      { name: "Longest Common Subsequence", url: "https://leetcode.com/problems/longest-common-subsequence/", gfgUrl: "https://www.geeksforgeeks.org/problems/longest-common-subsequence-1587115620/1" },
      { name: "0-1 Knapsack", url: "https://takeuforward.org/data-structure/0-1-knapsack-dp-19/", gfgUrl: "https://www.geeksforgeeks.org/problems/0-1-knapsack-problem0945/1" },
      { name: "Edit Distance", url: "https://leetcode.com/problems/edit-distance/", gfgUrl: "https://www.geeksforgeeks.org/problems/edit-distance3702/1" },
      { name: "Maximum sum increasing subsequence", url: "" },
      { name: "Matrix Chain Multiplication", url: "https://takeuforward.org/dynamic-programming/matrix-chain-multiplication-dp-48/", gfgUrl: "https://www.geeksforgeeks.org/problems/matrix-chain-multiplication0303/1" },
    ],
  },
  {
    topic: "DP II",
    icon: "💡",
    questions: [
      { name: "Minimum sum path in the matrix, (count paths and similar type do, also backtrack to find the Minimum path)", url: "https://leetcode.com/problems/minimum-path-sum/" },
      { name: "Coin change", url: "https://leetcode.com/problems/coin-change/", gfgUrl: "https://www.geeksforgeeks.org/problems/coin-change2448/1" },
      { name: "Subset Sum", url: "https://leetcode.com/problems/partition-equal-subset-sum/", gfgUrl: "https://www.geeksforgeeks.org/problems/subset-sum-problem-1611555638/1" },
      { name: "Rod Cutting", url: "https://leetcode.com/problems/minimum-cost-to-cut-a-stick/", gfgUrl: "https://www.geeksforgeeks.org/problems/rod-cutting0840/1" },
      { name: "Egg Dropping", url: "", gfgUrl: "https://www.geeksforgeeks.org/problems/egg-dropping-puzzle-1587115620/1" },
      { name: "Word Break", url: "https://leetcode.com/problems/word-break/", gfgUrl: "https://www.geeksforgeeks.org/problems/word-break1352/1" },
      { name: "Palindrome Partitioning (MCM Variation)", url: "" },
      { name: "Maximum profit in Job scheduling", url: "" },
    ],
  },
  {
    topic: "Trie",
    icon: "🔤",
    questions: [
      { name: "Implement Trie (Prefix Tree)", url: "https://leetcode.com/problems/implement-trie-prefix-tree/", gfgUrl: "https://www.geeksforgeeks.org/problems/trie-insert-and-search0651/1" },
      { name: "Implement Trie - 2 (Prefix Tree)", url: "https://takeuforward.org/data-structure/implement-trie-ii/" },
      { name: "Longest String with All Prefixes", url: "" },
      { name: "Number of Distinct Substrings in a String", url: "https://takeuforward.org/data-structure/number-of-distinct-substrings-in-a-string-using-trie/" },
      { name: "Power Set (this is very important)", url: "https://takeuforward.org/data-structure/power-set-print-all-the-possible-subsequences-of-the-string/", lcUrl: "https://leetcode.com/problems/subsets/" },
      { name: "Maximum XOR of two numbers in an array", url: "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/" },
      { name: "Maximum XOR With an Element From Array", url: "https://leetcode.com/problems/maximum-xor-with-an-element-from-array/" },
    ],
  },
];